### ISSUE TITLE
ReText does not load images in document directory

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#1]
ReText should load images if they are placed in document's directory.

Reported by: mandriver

Original Ticket: [retext/tickets/1](https://sourceforge.net/p/retext/tickets/1)

**Comment by fgrosshans** [comment]
I have the same problem in ReText 8.0.2 (using PyMarkups 4.0.0)/Qt 6.4.2 on Linux : 

The following path works:

* `/home/username/full/path/to/image.png`

None of he following do work (image and `.md` file in same directory)

*  `image.png`
* `./image.png`
* `~/full/path/to/image.png`
