### ISSUE TITLE
Preview error, missing module

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#104]
> Could not parse file contents, check if you have the necessary module installed!

Receiving the above error while attempting to use Preview in ReText 4.1, on a fresh install of Linux Mint 16 RC.

Reported by: tenkabuto

Original Ticket: [retext/tickets/104](https://sourceforge.net/p/retext/tickets/104)

**Comment by dajare** [comment]
I'm now getting this error with ReText 6.0.0 (using PyMarkups 2.0.0). When I click preview for a "*.md" file, I get:

> Could not parse file contents, check if you have the necessary module installed!

The message link takes me to `python-markdown`. But it is installed:

    $ sudo apt-get install python-markdown
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python-markdown is already the newest version.

On reading this thread, I tried with "python3", and get this:

    $ sudo apt-get install python3-docutils python3-markdown
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    python3-docutils is already the newest version.
    python3-markdown is already the newest version.

My guess is that this must be (?) a path problem -- at least, ReText can't find these files! In any case, any suggestions about getting a fix for this? Thanks!

**Comment by mitya57** [comment]
@dajare What is the version of Python-Markdown on your system (i.e. what does `apt-cache policy python3-markdown` output)?

The new versions of PyMarkups need Python-Markdown 2.6.

**Comment by dajare** [comment]
Thanks for quick reply! And yes -- bad!

    $ apt-cache policy python3-markdown
    python3-markdown:
      Installed: 2.4-1
      Candidate: 2.4-1
      Version table:
     *** 2.4-1 0
            500 http://gb.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
            100 /var/lib/dpkg/status

Just have to work out how to update now! (I'm on Ubuntu 14.04 LTS.) Will confirm a.s.a.p.

**Comment by mitya57** [comment]
Installing new version via pip should be safe:

    $ pip3 install --user Markdown

**Comment by dajare** [comment]
Hmmm...  Even running this with 

    $ pip3 install --user Markdown --upgrade

(as it prompted) leaves the `apt-cache policy python3-markdown` output unchanged, i.e. still at 2.4-1. Perhaps not available on 14.04? I am looking for solutions on [askubuntu.com](http://askubuntu.com/search?q=%22python3-markdown) but without success. 

If you have any other ideas? Otherwise - many thanks for the help. Hopefully the LTS upgrade isn't too far away!

**Comment by mitya57** [comment]
It is installing the new version into your home directory, it's not changing the distro package (so output of apt-cache should not change). ReText should pick up the local version and start working though.

**Comment by dajare** [comment]
You are right -- it does! Many thanks for helping me to sort this. Your support is much appreciated!
