### ISSUE TITLE
Sync the position of edit window and preview window

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#108]
I am using ReText version 4.1.0 but I still have the bug reported here: 
https://sourceforge.net/p/retext/tickets/14/

Also I think it would be very convenient for the user if the position of the edit window and the preview window are in sync, no matter in which window the user scrolls.

Reported by: spacetimewave

Original Ticket: [retext/tickets/108](https://sourceforge.net/p/retext/tickets/108)

**Comment by Griffon26** [comment]
I am going to take another look at this and my earlier implementation for it. 

Dmitry, are you fundamentally opposed to the additional HTML markers? Having HTML elements in the webkit view and knowing which part of the markdown they are associated with is the only way I can think of of making this work. Could you clarify your objections so I can think of a solution that would be acceptable?

**Comment by mitya57** [comment]
How are you going to implement the markers? I would like to avoid ugly hacks like searching for the text in the HTML. If it is a clean Markdown extension that adds some undisplayed HTML nodes then it's probably fine.

**Comment by mitya57** [comment]
This is now fixed in master, thanks to the awesome implementation by @Griffon26.
