### ISSUE TITLE
[feature request] additional recognized markdown file extensions

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#12]
I'll try and submit a patch as soon as possible but this request is such low hanging fruit I thought I would ask first. 

Would you consider adding .markdown, .mdown, .mkd & .mkdn to the supported file list? Without the change, I frequently have have change the filetype filter dropdown to "All files".

Here's a list of general standards accepted for markdown extensions:
- Vim (7.3): markdown, mdown, mkd, mkdn
- Github: markdown, mdown, mkd, mkdn, md
- Elements Markdown Editor: markdown, mdown, mdwn, md
- BBEdit: markdown, mark

Thanks for the helpful tool. Cheers, Mark S.

Reported by: markstinson

Original Ticket: [retext/tickets/12](https://sourceforge.net/p/retext/tickets/12)

**Comment by nkosi23** [comment]
I am interested in this too as I am facing the same issue, we use the ".text" extension for our markdown files. Has a solution been found?
