### ISSUE TITLE
Automatically reopen previous documents

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#135]
Hello,

I have an idea for a future version of ReText. It would be fine to have an option to automatically reopen files which were open the last time. This does not seem to be available in the current version.
Would it be possible?

Thank you in advance and keep up the good work, it's fantastic!

Reported by: banasura

Original Ticket: [retext/tickets/135](https://sourceforge.net/p/retext/tickets/135)

**Comment by rockiger** [comment]
The elementaryos hig have a good write up, why and how recreating state from last use makes sense:
https://elementary.io/en/docs/human-interface-guidelines#normal-launch
Hope this is useful

**Comment by mitya57** [comment]
Pushed with minor changes and simplifications. Thanks!
