### ISSUE TITLE
Open documents into new tab rather than new window

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#148]
When I already have a ReText window open, I'd like to be able to double-click a file in the file explorer (Gnome Files) and have it open into a new tab on the existing window. Currently a new ReText window is opened instead. Thanks!

I'm using retext-5.0.2-2 on Fedora Linux 22.

Reported by: porjo38

Original Ticket: [retext/tickets/148](https://sourceforge.net/p/retext/tickets/148)

**Comment by Mte90** [comment]
I developed a bit with PyQt and I can see that exist QtDbus also in python so I think that is possible to expose a signal.
In that way is possible to do a tiny script (or retext itself) that call dbus from retext and accept a file and will open a new tab.

**Comment by mitya57** [comment]
A pull request adding that would be very welcome.

**Comment by Mte90** [comment]
I am studying the code to see if I can do it.

I think that at https://github.com/retext-project/retext/blob/master/ReText/__main__.py#L92 I can see to emit the dbus signal when retext is started again.
Instead to the dbus listener I can use `window.openFileWrapper(fileName)` to open the file.
I can do it probably in the main file but I will let you know for updates in the next days.

**Comment by Mte90** [comment]
I did it https://github.com/retext-project/retext/pull/476 :-D

I wrote a book with ReText (mentioned in tools used) and this is to say thank you to the project :-) https://github.com/retext-project/retext/pull/476
