### ISSUE TITLE
CommonMark Support

### ISSUE THREAD

**Issue by KonomiKitten** [retext-project/retext#149]
Please consider supporting CommonMark as well as Markdown, I already ran into trouble doing separated item lists in ~~CommonMark~~ Markdown see: https://stackoverflow.com/a/24313004 for an explanation. CommonMark doesn't seem to have this problem and I suspect many other problems that Markdown has.

**Comment by mitya57** [comment]
This was discussed in waylan/Python-Markdown#338, and for the reasons stated there we will not implement CommonMark support.

The list behavior you mentioned can be turned on by enabling [sane_lists](http://pythonhosted.org/Markdown/extensions/sane_lists.html) extension (just add `sane_lists` to your `~/.config/markdown-extensions.txt`). Some other CommonMark features are also available in form of extensions.

**Comment by zhsj** [comment]
I'd like to reopen this issue.

Although Python-Markdown is not going to support CommonMark. But [rtfd/CommonMark-py](https://github.com/rtfd/CommonMark-py) is a library in Python that supports CommonMark.

I think it's easy to integrate CommonMark-py to pymarkups and retext. 

If you in favor of this, I'd like to work on it.
