### ISSUE TITLE
Replace capability

### ISSUE THREAD

**Issue by dmarrazzo** [retext-project/retext#150]
Right now, retext support just `Find`.
It would be useful add `Find & Replace`, and why not! Even Regular expressions!

**Comment by mitya57** [comment]
I will look at this at some future point. In the mean time, pull requests are welcome!

**Comment by Vdragon** [comment]
Just to add my usecase: replace all default urls to customize my README.markdown from template
![_001](https://cloud.githubusercontent.com/assets/1192163/11637326/a8cab2ae-9d5b-11e5-9ea5-a13e812c4583.png)

So sad I don't speak Pythonese so I can't help.
