### ISSUE TITLE
Markdown syntax help

### ISSUE THREAD

**Issue by dmarrazzo** [retext-project/retext#151]
It could be useful especially for newbies to have a toolbar with all markdown formatting codes.
E.g. Titles, bold, italic, list items, images, links, etc.
A good example would be the stackoverflow text box.

**Comment by mitya57** [comment]
I won't add the new toolbar (as I try to keep the design minimal), but I agree that HTML tags box should better be replaced with something more Markdown-ish.

**Comment by dmarrazzo** [comment]
If you agree, I would try to change the tags menu with Markdown syntax.
I will work on my fork then I'll propose the pull.

**Comment by mitya57** [comment]
I have now merged @dmarrazzo's changes to replace the Tags box with a Formatting box, so I think this can be closed now.
