### ISSUE TITLE
platform support

### ISSUE THREAD

**Issue by team-python** [retext-project/retext#152]
This looks like a great project, but it seems a challege to get it to work on key platforms for me.  Qt is great framework and a powerful one.  But it seems to leave the current project as focused on linux, and make OSX, WIndows, iOS and Android a real challenge.   Perhaps I am missing something?  Temptation for me is to fork the project to Kivy to enable me  to deploy it easier, but I may be missing something!

**Comment by mitya57** [comment]
Yes, we are focused on Linux. Installing it on Windows and OS X is harder but possible, I have just created a [wiki page](https://github.com/retext-project/retext/wiki/Installing-ReText#for-users-of-windows-and-mac-os-x) to document that.

iOS and Android will not be supported, as this is a desktop application.
