### ISSUE TITLE
Tried upgrading ReText 5.0.2 to 5.2.0 but it didn't "take"

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#155]
Hi,

Python 3.4.3 on Win 7 Pro 64bit

See upgrade log here: http://pastebin.com/Wtkx8PEd

I chose "Run as administrator" when I launched the CMD prompt.

retext.py is only located in the 5.0.2 directory. Should there be one in 5.2.0?

When I run ReText and do Help->About it still shows version 5.0.2.

What did I do wrong?

**Comment by mitya57** [comment]
I don't know anything about how `pip` works on Windows. Perhaps you can try to remove the old version and install the new one afresh?

**Comment by taa1** [comment]
Worth a shot. Thanks for the reply. I'll report back when I've had an opportunity to try your suggestion.

**Comment by taa1** [comment]
That worked!

~~~~
pip uninstall retext
pip install retext
~~~~
