### ISSUE TITLE
ReText's Table mode not working (?) and what else I tried

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#156]
Hi,

Using ReText 5.0.2 on Win 7 Pro 64bit because I didn't have luck upgrading to 5.2.0 (see #155).

Is there somewhere that I can read about how to use table mode? When I do Edit->Table Mode to toggle the checkmark ON, nothing seems to happen. I looked at the [ReText Wiki](https://github.com/retext-project/retext/wiki) but can't find anything there, not even in the FAQ.

Because I can't seem to get Table Mode to work, from the [ReText Wiki home page](https://github.com/retext-project/retext/wiki) I went to [Markdown Extensions](https://github.com/retext-project/retext/wiki/Markdown-extensions) and then to [Python-Markdown extensions](http://pythonhosted.org/Markdown/extensions/). There's a chart on this page that says in order to use the Tables extension I should use the name `markdown.extensions.tables`. I noticed Edit->Preferences has a place to put in extension names separated by commas, so I just put in `markdown.extensions.tables`. After I click OK, I exit ReText and re-launch it, just in case this is necessary to load the extension. But when I re-launch ReText and go to Edit->Preferences, the text box for "Markdown extensions" is blank, like it didn't save it when I clicked OK. And I don't see any new options for working with tables under the Edit menu.

I tried one more thing -- `pip search markdown` and got a huge list. I noticed BetterTableExtensions and installed it. Log is [here](http://pastebin.com/K8RdeWpi). I tried putting in `BetterTableExtensions` under Edit->Preferences, restarted ReText, but there's no new table options I can find, and Edit->Preferences has an empty "Markdown extensions" text box again.

I'm new to Python so please be kind. :-D

**Comment by mitya57** [comment]
It can be that specifying extensions globally does not work on Windows.

Can you try putting this into first line of your document, as documented in the [wiki](https://github.com/retext-project/retext/wiki/Markdown-extensions#enabling-extensions-for-a-particular-document), and check if that works?

    

Note that the table editing mode and tables extension are independent things.

**Comment by mitya57** [comment]
I have pushed a commit to PyMarkups repository which should make specifying extensions globally work too (after the next PyMarkups release).

**Comment by taa1** [comment]
Hi, I added the "" line to the beginning of my document, and toggled Table mode to be on. I don't see any visual change after doing these two steps. Where can I find instructions on how to use Table mode?

**Comment by mitya57** [comment]
There are no instructions so far (because it was not me who wrote that mode).

The idea is that you start writing a table following the [syntax rules](http://pythonhosted.org/Markdown/extensions/tables.html), and the table mode will help you to prevent the table layout from breaking.

Again, you can use tables even without the table editing mode, you just need to follow the syntax rules.

**Comment by taa1** [comment]
Toggling table mode doesn't seem to do anything at all. Or maybe it is just always enabled. I realize you're saying I don't need it and that you didn't write the mode.

I've now successfully upgraded to ReText 5.2.1 and I'm expecting the preview to show some sort of border around the tables.

If I use [this](https://michelf.ca/projects/php-markdown/extra/#table) example:


`| Item      | Value |`
`| --------- | -----:|`
`| Computer  | $1600 |`
`| Phone     |   $12 |`
`| Pipe      |    $1 |`


Notice how github renders the table with borders:

| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
| Pipe      |    $1 |

(I realize that github probably is not using php-markdown like ReText; I'm just giving an example of markdown table rendering with borders.)

But under ReText 5.2.1 it looks like this:

![retext-table-sample](https://cloud.githubusercontent.com/assets/492973/10343446/a11c5436-6cd2-11e5-9633-5b4519a1d698.png)

It renders the same whether the webkit renderer is enabled or not. It also renders the same whether `<!-- Required extensions: tables -->` is the first line of the document or not.

How do I get the table to render with borders so it looks like a table? What am I doing wrong?

**Comment by mitya57** [comment]
That can be achieved with CSS, i.e. try putting this in the beginning of the file:

```css
th, td { border: 1px solid black; }
```

**Comment by mitya57** [comment]
Also you are right: I forgot that tables extension is part of Markdown Extra and thus enabled by default.

**Comment by taa1** [comment]
For anyone else who might come across this issue, what I ended up doing was to create a new file called `retext.css` (I just picked the name arbitrarily; I'm sure it doesn't have to be called this) that has the following:

~~~~
th {
   white-space: nowrap;
}

table, th, td {
   border: 1px solid black;
}
~~~~

The first 'th' with 'nowrap' is to prevent column titles from being word/line wrapped.

After creating `retext.css` I launched ReText and did the following:

* Edit->Preferences->at the bottom set Stylesheet file to `retext.css`
* choose Edit->Use WebKit Renderer

I couldn't get the .css to apply to the preview unless I switched to the WebKit Renderer.

**Comment by dmarrazzo** [comment]
I order to get a nice table (like github) I suggest the following css:

```css
th {
   white-space: nowrap;
}

table, th, td {
   padding: 6px 13px;
   border: 1px solid #DDD;
   border-collapse: collapse;
   border-spacing: 0px;
}
```
I'd like to get this as default style. If it's not too hard to achieve, I would place a pull request.

**Comment by taa1** [comment]
dmarrazzo -- nice one! I'm going to use it.

**Comment by Griffon26** [comment]
@taa1 I've just added a page to the wiki about table editing mode that contains more or less the same information as I posted above. Please reopen this issue if that does not sufficiently answer your question. Thanks for bringing this to our attention.

**Comment by mitya57** [comment]
I have now added some basic CSS code for drawing table cell borders — please test if it works in your setup. Available only for WebKit though — the QTextBrowser doesn't understand those CSS properties.
