### ISSUE TITLE
Garbled characters are displayed when a non ASCII file's hyperlink is clicked in the preview window

### ISSUE THREAD

**Issue by Vdragon** [retext-project/retext#157]
As following reproduce video:
<https://www.youtube.com/watch?v=AOvrIBmbKqE>

Character encoding detection should be enabled if possible.
 
## Software
* ReText 5.2.1 (using PyMarkups 0.4) from PPA
* Ubuntu 14.04
* Locale: zh_TW.UTF-8

**Comment by mitya57** [comment]
Thanks for the bug report. The latest Git snapshot should fix this bug, can you confirm it?

**Comment by Vdragon** [comment]
Hi, I confirm that the bug is fixed in Webkit mode, thanks for helping!
https://youtu.be/mWC-c6Of0Fs
