### ISSUE TITLE
Text in code fences shouldn't be highlighted as headers in editor

### ISSUE THREAD

**Issue by Vdragon** [retext-project/retext#158]
As the following screenshot, the lines started with `#` are highlighted as headers. 

![readme markdown retext_008](https://cloud.githubusercontent.com/assets/1192163/10373284/147e3ab4-6e1f-11e5-8d4b-dee301e87769.png)

**Comment by Griffon26** [comment]
This is a duplicate of issue #98, so closing it as such. Please subscribe to the other issue instead if you would like to get notifications about it.
