### ISSUE TITLE
Show (web)images  in preview-mode

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#16]
Hey,
I'm new to retext (thanks for this great piece of software btw. ;) ) so maybe I just didn't see a option for my issue, yet. I hope it's okay if I ask this here anyhow..
When I use the preview-mode in retext, uploaded images are not displayed in the preview. (Screenshot: see attachment) 
If I export my text as html, the images are displayed properly, but they only local images are displayed in the preview mode or in exported pdfs. Is there a way to display these (external) pictures in the preview?
Thanks.

Reported by: pylight

Original Ticket: [retext/tickets/16](https://sourceforge.net/p/retext/tickets/16)

**Comment by scweiser** [comment]
Has this been resolved?  It's still an issue on my local version, not sure if updating something might help.

Thanks!

**Comment by mitya57** [comment]
@scweiser Of course this has been resolved. Can you please tell us which version of ReText and OS you have installed, and whether the WebKit renderer is enabled.

Also, please paste the HTML code from the “Edit &rarr; View HTML code” dialog somewhere (at least the relevant part).

**Comment by scweiser** [comment]
@mitya57 I never tried WebKit rendering, but that solved the problem!  Does preview of external images only  work with WebKit rendering?  I prefer the alternative--formatting looks better on my computer.

Not sure if this info is still necessary, but:

- Linux Mint 18.1 (Linux kernel 4.4 and an Ubuntu 16.04 package base)
- ReText 6.0.2 using PyMarkups 2.0.0

HTML Excerpt:
`<p><img alt="Screenshot of Component Selector" src="https://s3-us-west-2.amazonaws.com/cdn.ackmanlab.com/170110_1451--140509-17_SVD.png"></p>`

**Comment by mitya57** [comment]
@scweiser Sorry for the delay. Unfortunately it seems that not loading external images is a QTextBrowser limitation.

However you can save the image locally (or even paste it into ReText), and then QTextBrowser would be able to render it.

**Comment by scweiser** [comment]
@mitya57 No problem, It'd be a pain changing all the image addresses when uploading the file, so I'll just stick to WebKit rendering.  
I found the preview formatting sections, which help make the preview more readable.  Thanks for all the help!
