### ISSUE TITLE
Feature Request: input unicode characters

### ISSUE THREAD

**Issue by aletheia7** [retext-project/retext#160]
Key combination ctrl+shift+u allows inputing unicode characters in many terminals, i.e. xfce4-terminal. Could you add support for this key combination?

**Comment by mitya57** [comment]
I believe this should be implemented by the input method, not by every individual application.

For example, I managed to setup such input scheme in ibus using the following steps:

* Installing ibus, `apt-get install ibus ibus-m17n`.
* Running ibus-setup, selecting Input Method tab → Add → Other → unicode (m17n).
* (Re-)Starting ibus, `ibus-daemon --daemonize --replace`.
* Running ReText with `QT_IM_MODULE=ibus` set.

After that, I was able to use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> in ReText when “Other - unicode (m17n)” method is selected on the ibus indicator.

In normal ibus input method (i.e. “English - US)”, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> triggers *something* but I failed to figure out how to use it…

**Comment by aletheia7** [comment]
I installed ibus. ctrl-shift-u give me an underlined U but when I enter 03b1 for the Greek α, the U becomes a 0.

**Comment by mitya57** [comment]
Have you enabled the m17n input method?

Also, I want to note, that if you are using Markdown, there is an easier way to input Unicode characters. Just enter their HTML entity. I.e. `&alpha;` becomes &alpha;. That allows you to not care about their (hexa)decimal values at all.

**Comment by aletheia7** [comment]
Yes. I followed your instructions.

**Comment by mitya57** [comment]
Sorry that I didn't find the solution for your issue, but input methods is a generic thing that should be handled on desktop/toolkit level, not in every application. So I am closing this bug.
