### ISSUE TITLE
FakeVim doesn't work?

### ISSUE THREAD

**Issue by linxd5** [retext-project/retext#162]
Hello, My ReText version is 5.2.1 (using PyMarkups 0.6.1), and FakeVim doesn't work ~ below is my configuration file:

[General]
autoSave=true
highlightCurrentLine=true
previewState=true
restorePreviewState=true
saveWindowGeometry=true
spellCheck=true
useFakeVim=true
useWebKit=true
windowGeometry="@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x3\xe\0\0\0\xef\0\0\a\xa1\0\0\x4;\0\0\x3\x18\0\0\x1\x15\0\0\a\x97\0\0\x4\x31\0\0\0\0\0\0\0\0\a\x80)"

Thank you~

**Comment by mitya57** [comment]
Have you installed [FakeVim](https://github.com/hluk/FakeVim) and its Python 3 bindings?

**Comment by linxd5** [comment]
Yes, I have installed all the package and startup retext "normally";    But I don't figure out how to configure FakeVim; 
Does the FakeVim set as default while install correctly or you need to do some other configurations?  
I have installed Python2 as well as Python3 in my ubuntu15.04. Maybe the FakeVim choose Python2 as preference that I should remove Python2 ?

**Comment by mitya57** [comment]
So, ReText will work only if this command:

    python3 -c "import FakeVim; print(FakeVim.FAKEVIM_PYQT_VERSION)"

works and prints the number `5`. If the output is different for you, then this is not a ReText bug.

**Comment by mitya57** [comment]
I am closing this bug as it is most probably not an issue with ReText.
