### ISSUE TITLE
Word count feature

### ISSUE THREAD

**Issue by Sirtea** [retext-project/retext#164]
It should be desirable to have a "document word count" feature. Furthermore, a status line with line number and a column number will be great

**Comment by mitya57** [comment]
> Furthermore, a status line with line number and a column number will be great.

Line number and column number are displayed by default in the bottom-right corner of the editor (in ReText 5.1+).

For the “document word count” feature, I will implement it when I have enough time (but I don’t have it, so patches welcome).

**Comment by Sirtea** [comment]
I'm using Debian stable (retext 5.0.1), so I will need to upgrade from newer version to see this.
I'm system administrator, so I don't trust myself writing a patch; this could come from jinja2 template engine (wordcount filter). Looking forward to this
