### ISSUE TITLE
Code block inside list not properly displayed

### ISSUE THREAD

**Issue by andrewbenton** [retext-project/retext#170]
When a code block is created inside a list, it is not properly displayed in the preview window.

OS: Fedora 22
Version: 5.2.1

Example:

```markdown
1. asdf
2. jkl;

    ```bash
    echo "line 1"
    echo "line 2"
    ```

3. aeio
```

Result:

> 1. asdf
> 2. jkl;
>     bash echo "line 1" echo "line 2"
> 3. aeiou

**Comment by mitya57** [comment]
It is a known issue in Python-Markdown, see waylan/Python-Markdown#53 (assigned to 3.0 milestone). As a workaround, you can use normal code blocks (just add 4 more spaces to the indentation).

I am closing this as I can do nothing about it in ReText itself.
