### ISSUE TITLE
no export icon, nor for settings

### ISSUE THREAD

**Issue by blonchkman** [retext-project/retext#171]
Hello mitya57

First of all, many thanks for your incredibly great, small, versatile and fast tool :)
I switched from 4.x to the 5.2 for table editing and work with other fonts.

Using ubuntu 14.04.03 (mate desktop variant), i've istalled 5.2.1-1~14.04 from PPA.  
Unfortunatly, in any of the 3 toolbars, there are no icons for calling the preferences dialog, nor for exporting. Those 2 icons are just missing.

I've successfully wrotten some settings into "~/.config/ReText\ project/ReText.conf"  
but i can't figure out a way to launch the export dialog.

Would you please help me find a workaround or refine diagnostic ?

Many thanks in advance for your hand
Kindest regards

**Comment by mitya57** [comment]
Hi,
There are no toolbar buttons for those actions, they are in the menu.

**Comment by blonchkman** [comment]
Hello,
Thx for your answer.

Unfortunatly, i've no menu at all showing on my retext window.
I've suspected some issue with mate interface, but i get the same behavior
after login in Cinnamon or Fluxbox.

Any idee ?

Is there a way to launch retext with some debug option in order to see
what's going on ?

Would somebody be nice enough to confirm (or not) on an other Ubuntu 14.04
installation ?



2015-12-11 16:53 GMT+01:00 Dmitry Shachnev <notifications@github.com>:

**Comment by mitya57** [comment]
That's very strange. Can you try to run it with env `UBUNTU_MENUPROXY=0`?

**Comment by blonchkman** [comment]
Tryied with:

    $ export UBUNTU_MENUPROXY=0
    $ retext

No change. Menu still doesn't show.


2015-12-12 19:26 GMT+01:00 Dmitry Shachnev <notifications@github.com>:

**Comment by mitya57** [comment]
Then you are probably experiencing [bug 1362104](https://bugs.launchpad.net/bugs/1362104). It is fixed in newer Ubuntu versions, in older versions you can remove the `appmenu-qt5` package as a workaround.

**Comment by blonchkman** [comment]
Removing appmenu-qt5 made it *:)*

Thank you very much for your help, Dmitry


2015-12-12 20:49 GMT+01:00 Dmitry Shachnev <notifications@github.com>:
