### ISSUE TITLE
Retext on Debian, not working well

### ISSUE THREAD

**Issue by rmaddox** [retext-project/retext#173]
Please give me a clue, why Retext on Debian is not working well. I don't even see icons on the window. Other programs are working.

Here is link to the picture:
<img src="http://rcdrun.com/images/upload/git/retext-2015-12-21.png">

**Comment by mitya57** [comment]
Hi, the bug with missing icons was fixed in ReText 5.2.1 (and newer). Are you using that version or an earlier one?

Anyway, as a workaround you can open the preferences dialog and set the icon theme manually.

**Comment by rmaddox** [comment]
Alright, this now really works, I used github version now. And I can even change editor fonts correctly. Thank you.
<img src="http://rcdrun.com/images/upload/git/retext-2015-12-21-working.png">
