### ISSUE TITLE
Triggering ReText's HTML export from the command line

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#174]
I'm using ReText to handle nearly all my documentation needs now (so THANKS for your superb program!). :D 

Is there a way to launch ReText from the command line, specify the markdown input file and have it export to HTML? The goal is to create a Makefile to handle it automatically for maybe a hundred files (at least for the current project I'm working on). I would want it to take advantage of the extensions, css, etc. that I've configured under the ReText GUI.

Can this be done, and if so, how?

Edited: This export to HTML would be done under Fedora 21.

**Comment by mitya57** [comment]
That is not currently possible. However, it is very easy to write such a script using the [PyMarkups API](http://pythonhosted.org/Markups/). Feel free to ask me for help if you need it.

Also if you work only with Markdown files, you can try using the [Python-Markdown API](http://pythonhosted.org/Markdown/reference.html) directly (or even the `python3 -m markdown` commandline interface).

I am closing this as I don't see any point to have such a generator in ReText itself.

**Comment by taa1** [comment]
Hi mitya57,

I *do* understand why you closed this issue.

I am sorry to have to ask for your help in creating a script using PyMarkups API. I just don't know enough about python to do it myself. I do want to be sure the script uses all of the same enabled extensions that ReText uses so that I get the same rendered output. Thanks in advance.

**Comment by mitya57** [comment]
Try this script: https://github.com/retext-project/pymarkups/blob/master/markup2html.py (I've just written it).
