### ISSUE TITLE
different tab names for different files even if the filename is the same

### ISSUE THREAD

**Issue by tcpaiva** [retext-project/retext#175]
Different files with same name in different folders have the same tab names. I can suggest two ways to make it a little bit more clear:

*  display the path (or a piece of that like vim tabs), not only the filename
* display the title instead of the filename 

What do you think?

**Comment by mitya57** [comment]
I can display the full file path as the tab tooltip, this should make them easily distinguishable.

**Comment by Vdragon** [comment]
Hi, I would really prefer using the <h1> header as the tab name instead of filename and path(which can be the fall-back option), it is possible?
