### ISSUE TITLE
BibTeX references

### ISSUE THREAD

**Issue by tcpaiva** [retext-project/retext#177]
Is that possible to include support for bibtex references?

Sphinx already has an alternative for it, please take a look in this [link](http://build-me-the-docs-please.readthedocs.org/en/latest/Using_Sphinx/UsingBibTeXCitationsInSphinx.html#using-sphinx-bibtex-extension).

**Comment by mitya57** [comment]
I don't see what this has to do with ReText. Maybe you want a Markdown extension or a custom reStructuredText directive?

**Comment by tcpaiva** [comment]
Actually, I don't know how you generate the output from restructuredtext (I don't use markdown). Sphinx is a tool that is built over restructuredtext also and I believed that maybe it was possible to use their elegant solution for this. But you are right, citations are [still not defined](http://docutils.sourceforge.net/docs/ref/rst/directives.html#citations) for restructured directives.

Anyway, the use of an external bib file makes much easier to export the document from restructuredtext to other formats. Are you open for non-standard definitions?

**Comment by mitya57** [comment]
ReText currently uses plain docutils. It's impossible to use any extensions developed for Sphinx…

If it is possible to implement that functionality as a custom directive (see [this page](http://docutils.sourceforge.net/docs/howto/rst-directives.html) for details), then I'll maybe find a way to hook it into ReText code.

**Comment by tcpaiva** [comment]
Right. I'll take a look on that.

**Comment by mitya57** [comment]
So, if there is a reStructuredText directive that implements the behavior you want, please file a bug (or pull request) against PyMarkups and I'll consider it. Closing this bug for now.
