### ISSUE TITLE
How to find out the version# of the python-markdown 'tables' extension?

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#179]
ReText is rendering tables correctly but another app I'm trying does not. I'd like to tell the developer of the other app which 'tables' version works successfully in ReText.

**Comment by mitya57** [comment]
ReText uses the [tables extension](http://pythonhosted.org/Markdown/extensions/tables.html) that ships with Python-Markdown. The latest version of Python-Markdown is 2.6.5, and it definitely works.
