### ISSUE TITLE
No menu bar on Ubuntu 14.04 after pip install

### ISSUE THREAD

**Issue by donnekgit** [retext-project/retext#181]
The latest version of retext in the Ubuntu repositories is 4.1.2, and I installed retext using:
`pip install retext`
The required packages listed on the README (python3, python3-markups, python3-markdown, python3-docutils, python3-enchant, python3-pyqt5) are all installed.  However, python3-pyqt5.webkit is also required before Retext will start.

When it does start, the menu bar is missing - only the icon bar is showing.  Adjusting preferences (eg the font for the live preview) is therefore impossible.

**Comment by mitya57** [comment]
If you are not using Unity, remove `appmenu-qt5` package. It had a [known bug](https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1362104) in Ubuntu 14.04 which prevented applications from showing their menus.

Hope that helps.

**Comment by donnekgit** [comment]
Excellent - works fine now.  Thanks!
