### ISSUE TITLE
Possible bugs: UTF-8 and Ctrl+S

### ISSUE THREAD

**Issue by donnekgit** [retext-project/retext#182]
I've come across what seem to be two bugs on Ubuntu 14.04 and Retext 5.3.0:
(1) If I type in "Māori", the a-macron gets converted in live preview to a triangle (and double linespace for that line).  If I open the file in Geany, it contains "SOH" instead of the macron.  I edit it there to give a macron.  If I reopen in Retext, it replaces the macron with a triangle, and reopening in Geany shows the macron has disappeared and been replaced with "SOH" again.  Is Retext using UTF-8 for the preview/pdf export?  I see no way to check the encoding, or change it.
(2) If I open a file in Retext, and make some changes, the File ->Save option remains greyed out.  Pressing Ctrl+S to save merely adds an s to the text.

**Comment by mitya57** [comment]
@donnekgit That's quite strange.

By default ReText should use the system locale, which is UTF-8 on Ubuntu. Did you change anything in the configuration file? Can you please attach the wrong file created by ReText?

Finally, does ReText print any errors on the command line, when started?

**Comment by mitya57** [comment]
Closing because of no response.
