### ISSUE TITLE
Editing while preview

### ISSUE THREAD

**Issue by moshpirit** [retext-project/retext#185]
Allowing the user editing the file as is already shown the preview would be amazing. 

Like: `**something**` and when I press the last `*` the word "something" gets automatically bold.

**Comment by mitya57** [comment]
Sorry, I don't understand what exactly you mean. It does already get bold (that's a feature of the highlighter), doesn't it?

**Comment by moshpirit** [comment]
Yes, sorry I explained it really bad.

Right now we have 2 sides: one for typing and another for viewing it. What I mean is having them both mixed in one: the preview side but we could edit the content making it cleaner and simpler. 

E.g.: For writing "This is **M↓**" we would see:

![captura de pantalla_2016-01-23_13-37-02](https://cloud.githubusercontent.com/assets/7888062/12530201/e62e0674-c1d6-11e5-9436-b2716c0d44f9.png)
![captura de pantalla_2016-01-23_13-37-50](https://cloud.githubusercontent.com/assets/7888062/12530202/e631d9c0-c1d6-11e5-9831-e387408aff93.png)
![captura de pantalla_2016-01-23_13-38-43](https://cloud.githubusercontent.com/assets/7888062/12530203/e6332bd6-c1d6-11e5-95f0-50cd2ac14def.png)

We should have a button to see the "code" highlighting the current line.

**Comment by mitya57** [comment]
> Right now we have 2 sides: one for typing and another for viewing it. What I mean is having them both mixed in one: the preview side but we could edit the content making it cleaner and simpler.

Sorry, I'm not going to turn ReText into a WYSIWYG. The very idea of ReText is that the source is always visible. (And, also, the behavior you are suggested will be unimplementable in ReText because it doesn't really know anything about Markdown and leaves the actual processing to a third-party library).

I think the live preview suits needs of most people who want to edit text and view the result simultaneously.

**Comment by moshpirit** [comment]
Oh, OK then, thanks anyway for this great program and for the explanation :)

**Comment by dessalines** [comment]
> Sorry, I'm not going to turn ReText into a WYSIWYG. The very idea of ReText is that the source is always visible. 

In all WYSIWYG editors (marktext, typora), there is a source code mode where you can see the source really easily. This is pretty much the one feature preventing me from switching to retext. I think this is possible to do using GTK contentEditable.

**Comment by mitya57** [comment]
> In all WYSIWYG editors (marktext, typora)

ReText is not a WYSIWYG editor :)

> I think this is possible to do using GTK contentEditable.

…and it is not using GTK.
