### ISSUE TITLE
Retext crashes when opening a file with spellcheck enabled

### ISSUE THREAD

**Issue by T3RM1NU5** [retext-project/retext#193]
When I open a document with retext with spellcheck enabled retext crashes.  The only solution is to turn of spellchecking before opening a document then turning it back on.  I am using retext 5.3.0-3 on Arch Linux. 

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ReText/highlighter.py", line 129, in highlightBlock
    if not self.dictionary.check(match.group(0)):
  File "/usr/lib/python3.5/site-packages/enchant/__init__.py", line 634, in check
    self._check_this()
  File "/usr/lib/python3.5/site-packages/enchant/__init__.py", line 606, in _check_this
    _EnchantObject._check_this(self,msg)
  File "/usr/lib/python3.5/site-packages/enchant/__init__.py", line 176, in _check_this
    raise Error(msg)
enchant.errors.Error: Dict unusable: the underlying C-library object has been freed.
[1]    23783 abort (core dumped)  retext

```

**Comment by mitya57** [comment]
This should be already fixed in the current master. Can you please test that?

**Comment by T3RM1NU5** [comment]
My apologize, I should have pulled the master before reporting the bug.  I have gone head and marked the package as out of date on the Arch package page.

**Comment by mitya57** [comment]
It's not outdated. I'm going to do a new bugfix release soon, but it's not ready yet. Maybe it'll be next week.

Closing this bug anyway.

**Comment by farseerfc** [comment]
I have just released [retext-5.3.0-4](https://projects.archlinux.org/svntogit/community.git/commit/trunk?h=packages/retext&id=ac4eae9048d83e633d0cfae683ff384771b76370) to [[community]](https://www.archlinux.org/packages/community/any/retext/) that have backport https://github.com/retext-project/retext/commit/39603255072313423a17d9207c6b1ec613d9825b commit, which should fix this problem.
Waiting for a new release!

PS: A stable release that have not keep up with master branch is usually not considered as out-of-date in Arch Linux.

**Comment by T3RM1NU5** [comment]
Thanks for that, just starting to get my feet wet with contributing back to the community.

**Comment by mitya57** [comment]
ReText 5.3.1 is now released. It took much longer than expected…
