### ISSUE TITLE
"Display right margin at column:" is ambiguous?

### ISSUE THREAD

**Issue by Vdragon** [retext-project/retext#194]
Hi ReText developers, I wonder what do the preference setting: "Display right margin at column:" actually does?  According to the configuration page it states: "enable drawing of vertical line on defined position (or 0 to disable)" and IMO it seems like helping user with the markup indentation, but why it's named "*right* margin" instead of "left margin" or simply "vertical line"?

**Comment by mitya57** [comment]
It was meant to help not with indentation, but with wrapping the text at i.e. 80 characters. But if it's useful for other cases too, I can rename it to &ldquo;Draw vertical line at column&rdquo; as you suggest.

**Comment by Vdragon** [comment]
Since I'm not following that tradition I'm not sure what term would be better, what about "wrap indicator"?
