### ISSUE TITLE
i couldn't run the retext.error msg:" No module named 'markups.web'"

### ISSUE THREAD

**Issue by dengfengdecao** [retext-project/retext#195]
error message:

```
dengfengdecao:~$ retext
Traceback (most recent call last):
  File "/usr/bin/retext", line 24, in <module>
    from ReText.window import ReTextWindow
  File "/usr/share/retext/ReText/window.py", line 11, in <module>
    from ReText.webpages import wpInit, wpUpdateAll
  File "/usr/share/retext/ReText/webpages.py", line 9, in <module>
    from markups.web import WebLibrary
ImportError: No module named 'markups.web'
```

I install the retext by command:
`sudo apt-get install retext`

and my os is ubuntu 64bit.

**Comment by mitya57** [comment]
Looks like you are mixing a distro version of ReText with a newer (unpackaged) version of PyMarkups. You shouldn't do that. So either use a new ReText or PyMarkups shipped by the distro.

**Comment by dengfengdecao** [comment]
@mitya57 
aleady installed,but can't enter Chinese

![_001](https://cloud.githubusercontent.com/assets/10655188/13546363/b1ff3db0-e2e6-11e5-9ba8-2eb4b80d9e6c.png)

**Comment by mitya57** [comment]
That probably means Google Pinyin doesn't work with Qt, and you need to use something else (i.e. ibus or fcitx).

**Comment by dengfengdecao** [comment]
@mitya57 
OK.
It's already running,and can enter chinese.Thank you for patient answers my question!
