### ISSUE TITLE
I can't start Retext anymore...

### ISSUE THREAD

**Issue by lugarparaler** [retext-project/retext#196]
Hi!

I was using Retext for one month or two. But today, when I tryied to open the editor, this error message was shown:

Using configuration file: /home/librarian/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/bin/retext", line 23, in <module>
    from ReText.window import ReTextWindow
  File "/usr/lib/python3.5/site-packages/ReText/window.py", line 22, in <module>
    from ReText.tab import ReTextTab, PreviewNormal, PreviewLive
  File "/usr/lib/python3.5/site-packages/ReText/tab.py", line 32, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: /usr/lib/libQt5Network.so.5: undefined symbol: SSLv2_client_method

How can I fix it?

I don't wanna change my editor, I really like Retext...

**Comment by mitya57** [comment]
This looks like a problem with your distro's Qt libraries. Are you running Debian? Do you have the latest updates installed?

**Comment by lugarparaler** [comment]
I use Arch Linux. I update it everyday, using Octopi... I tryied to remove the editor and then reinstall it again, using "pip install retext", pacman, and the AUR repositories, but all the installations show the same problem when I launch the editor...

well, I will try to reinstall the QT5 then... thank you!

**Comment by lugarparaler** [comment]
Hi again!

Everythin is fine now!

I've replaced qt5-base-git for qt5-base and retext came back to load.
(I had installed qt-base-git because I wanted to see the papyrus shell in action).

Bye-bye,

Alexandre.

**Comment by mitya57** [comment]
OK. I don't know why I thought it's Debian: it was definitely something different according to the paths :)
