### ISSUE TITLE
Mac OSx: ReText does not render the toolbar

### ISSUE THREAD

**Issue by zoran-rajic** [retext-project/retext#198]
Using Apple Mac OSX El Capitan 10.11.3, and Python3.4 installed via [MacPorts](https://guide.macports.org/), the ReText does not render the toolbar icons  (issue identical to https://www.svenbit.com/2012/05/fix-missing-toolbar-icon-in-retext/ -- please check the screenshots).

The probable root-cause is an invalid icons search path (ie. the icons are not installed where the QT is looking for them).  The following patch fixes the issue:

```diff
--- /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ReText/window.py.orig    2015-12-20 06:44:00.000000000 -0800
+++ /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ReText/window.py    2016-03-11 18:35:03.000000000 -0800
@@ -49,6 +49,8 @@
             self.move((screenRect.width()-self.width())/2, (screenRect.height()-self.height())/2)
         if not screenRect.contains(self.geometry()):
             self.showMaximized()
+        if sys.platform == "darwin":
+            QIcon.setThemeSearchPaths(["/opt/local/share/icons"])
         if globalSettings.iconTheme:
             QIcon.setThemeName(globalSettings.iconTheme)
         if QIcon.themeName() in ('hicolor', ''):
```

I understand that this is not necessarily the ReText issue, but I wonder if something can still be done to fix this? (ie. perhaps automatically detect icon's paths on Mac, or by default add a few alternative search-paths?)

Note that [MacPorts](https://guide.macports.org/) and [Homebrew](http://brew.sh/)
are the two most popular package managers on Mac, so by adding 2 SearchPaths (1 MacPort's and 1 Homebrew's) one might be able to fix most of the Mac installs. Sadly, I'm not quite sure where Homebrew package manager installs the icons.

Thanks,
             Zoran

**Comment by mitya57** [comment]
Can you please tell me what exaxtly is in your `/opt/local/share/icons`? Is there some standard icon theme (like on Linux), or just ReText-specific icons? Which package manager did you use to install that?

If it's some standard icon theme, is there any way for ReText to automatically figure out its name (I suppose just the path isn't enough)?

**Comment by zoran-rajic** [comment]
Hello Mitya,

The _/opt/local/share/icons/_ is the location where the MacPorts installs the GNOME icons.  Ie. the [Adwaita icons theme](https://www.macports.org/ports.php?by=library&substr=adwaita-icon-theme) gets installed at:

 /opt/local/share/icons/Adwaita/22x22/status/image-loading.png
 /opt/local/share/icons/Adwaita/22x22/status/image-missing.png
 /opt/local/share/icons/Adwaita/22x22/status/mail-attachment.png
 /opt/local/share/icons/Adwaita/22x22/status/mail-read.png
 /opt/local/share/icons/Adwaita/22x22/status/mail-replied.png [...]

As I suggested earlier, since large majority of Apple Mac OSX people get their Gnome/QT packages either via [MacPorts](https://www.macports.org/) or via [HomeBrew](http://brew.sh/), perhaps it would make sense to check for a few extra dirs, and fix the broken system IconPaths.

Thanks,
            Zoran

**Comment by mitya57** [comment]
OK, thanks. I will add that a bit later.
