### ISSUE TITLE
LivePreviewByDefault (v5.3.0)

### ISSUE THREAD

**Issue by p404** [retext-project/retext#201]
Hi,
Everything works great but I cannot make the live preview as a default work.
I'm using ReText 5.3.0 on Ubuntu 16.04.

Some options of my **ReText.conf**
```
livePreviewByDefault=true
restorePreviewState=true
```
The strange part is that the other configuration options work as intended. 

e.g.
```
editorFont=Monospace
editorFontSize=14
font=Ubuntu
fontSize=11
hideToolBar=true
```

Cheers!

**Comment by mitya57** [comment]
This is fixed in the current Git. I will try to prepare an update for 5.3 branch, but no promises because I have very limited time.

**Comment by mitya57** [comment]
ReText 5.3.1 is now released, with this bug fixed.

**Comment by farseerfc** [comment]
Could you please create a tagged release of 5.3.1 so distributions can package it. Thank you!

**Comment by mitya57** [comment]
Oops, forgot about the tag, done now.

Distributions can also use the tarballs from PyPI — these include pre-compiled translation files, which may be helpful.
