### ISSUE TITLE
markdown extensions issues

### ISSUE THREAD

**Issue by blonchkman** [retext-project/retext#203]
Dear all
i'm reporting some issues related to ReText v5.2.1 (ppa) and markdown extensions on ubuntu 15.10.

1. Comma separated extensions list won't work 
    * works: `<!-- Required extensions: wikilinks toc -->`
    * not working: `<!-- Required extensions: wikilinks, toc -->`
2. Space in string params won't work
   * works: `<!-- Required extensions: toc(title=Content) -->`
   * not working: `<!-- Required extensions: toc(title="Table of content") -->`
   * not working: `<!-- Required extensions: toc(title='Table of content') -->`
   * not working: `<!-- Required extensions: toc(title=Table of content) -->`
3. Multiple params in extensions won't work
   * not working:  `<!-- Required extensions: toc(title=Content, baselevel=2) -->`
4. Configuring an extension with multiple params (trough config or directly in   
`markdown-extensions.txt`) result in ReText crash or not starting.

Always reproducible (at least for me).  
ReText is a fantastic works and i can live with this thread, but a short word in wiki doc might be fine ;)

kind regards

**Comment by mitya57** [comment]
Fixed in PyMarkups git (if you could test it, that would be appreciated).

Separating extensions by comma is not needed, the spaces should be enough. Params with spaces and multiple params now should work correctly.

**Comment by blonchkman** [comment]
@mitya57 **it works like a charm :-)**

Although separating extensions with comma seams to be needed as soon as you mix multiple extensions, with and without params.

### 1st Try (works as expected):
Preferences -> markdown : `toc(title=Table des Matières, baselevel=1), wikilinks`

Resulting markdown-extensions.txt file:
```
toc(title=Table des Matières
baselevel=1)
wikilinks
```

### 2nd test (don't works, but don't crash ;-) ):
Restart ReText after change.  
Preferences -> markdown : `toc(title=Table des Matières, baselevel=1) wikilinks`

Resulting markdown-extensions.txt file:
```
toc(title=Table des Matières
baselevel=1) wikilinks
```

Kind regards

**Comment by mitya57** [comment]
@blonchkman Extension lines in ReText preferences and in the Markdown files have different syntax (and are parsed by different code pieces).

My commit should only fix the second case (what you called the header comments). Did you really use the latest Git snapshot of [PyMarkups](https://github.com/retext-project/pymarkups) library?

For the extensions in ReText preferences, can you try this: `toc(title=Table des Matières,baselevel=1), wikilinks` (with no space after Matières)? I think it should work.

**Comment by blonchkman** [comment]
@mitya57 -

My guilt: PyMarkup was installed from master branch but only for python2,
so i reinstalled the lib for python3.5.

* Now, the **Required extensions** comment works as expected, and is very
lazy about spaces. Both spaces and commas are usable as separators for
extensions.
* Comma is mandatory in *preferences*. Space won't work. Furthermore in
multi-options, ReText adds a space if it's missing after the comma.

All works perfectly and i won't ask you for possible new issues until i
have migrated.
In the mean time, please, fill free to request if you might still need some
testing on outdated ;) material.

Many thanks for all your help.
Kind regards


2016-04-25 15:18 GMT+02:00 Dmitry Shachnev <notifications@github.com>:

**Comment by mitya57** [comment]
Right, in the preferences comma is mandatory, while in the files it is not. Thanks for testing!
