### ISSUE TITLE
Abbr markdown extension not working

### ISSUE THREAD

**Issue by blonchkman** [retext-project/retext#204]
Hello, all

There is no way for me to get the **abbr** extension working on ubuntu 15.10 / ReText 5.2.1 (Unfortunately, I can not migrate before the update of several third-party software).

Installed librairies:
```
ii python3 3.4.3-4ubuntu1
ii python3.4 3.4.3-9ubuntu1
ii python3.5 3.5.0-3
ii python3-docutils 0.12+dfsg-1
ii python3-enchant 1.6.6-2
ii python3-markdown 2.6.2-1
ii python3-markups 0.6.3-1
ii python3-markupsafe 0.23-2build1
ii python3-pyqt5 5.4.2+dfsg-1build3
ii python3-pyqt5.qtwebkit 5.4.2+dfsg-1build3
ii python-markdown 2.6.2-1
ii python-pyqt5 5.4.2+dfsg-1build3
ii python-pyqt5.qtsvg 5.4.2+dfsg-1build3
ii python-pyqt5.qtwebkit 5.4.2+dfsg-1build3
```

Following snippet:
```
<!-- Required extensions: abbr  -->

  * HTML: Hypertext Markup
  * XML: Extensible Markup Language

Do we speak HTML or XML here ?
```
Render as:
```
<!-- Required extensions: abbr  -->

<ul>
<li>HTML: Hypertext Markup</li>
<li>XML: Extensible Markup Language</li>
</ul>
<p>Do we speak HTML or XML here ?</p>
```

Although I can live with that without problems, would anyone still be kind enough to confirm or refute this behavior for ReText v5.3.x ?
Do i missed something ?

Many thanks in advance for your tips.
Kind regards

**Comment by mitya57** [comment]
Hi @blonchkman,

You are using it wrong, please see the [syntax example in the documentation](http://pythonhosted.org/Markdown/extensions/abbreviations.html#syntax).

**Comment by blonchkman** [comment]
@mitya57 - Sorry for the typo. Anyway, as you noticed i used a wrong syntax. Removing space between bullet mark and square bracket resolve this. Thank you very much for your hand.

Working snippet:
```
<!-- Required extensions: abbr  -->

*[HTML]: Hypertext Markup
*[XML]: Extensible Markup Language

Do we speak HTML or XML here ?
```
