### ISSUE TITLE
Change paper size for PDF export

### ISSUE THREAD

**Issue by stephenjjohnson** [retext-project/retext#205]
The PDF export seems to default to A4, with no obvious (to me) way to change it.

I can print to PDF and change the paper to e.g. letter, and set up margins. Is there a UI or text file that stores default values for the more direct "Export" option?

**Comment by mitya57** [comment]
There is no option to set the default paper size at the moment.

I can implement it if needed, though probably after 6.0 release.

**Comment by stephenjjohnson** [comment]
It would be a nice feature. Either that, or persistent selections for paper size and margins in the print dialog. They have yet to embrace iso paper sizes here in the US. :-)

**Comment by mitya57** [comment]
This was implemented in #335 and will be available in the next release.

You can use `paperSize` setting in the [configuration file](https://github.com/retext-project/retext/blob/master/configuration.md), e.g. `paperSize=Letter`.
