### ISSUE TITLE
add option to stop automated reformatting files

### ISSUE THREAD

**Issue by matkoniecz** [retext-project/retext#216]
This program has annoying habit of reformatting file. It is invisible in normal use, changes are not harmful. It is annoying during making pull requests, as it results in patch polluted by tiny, unintended and unwanted changes.

I produced testcase at https://github.com/matkoniecz/ReText-problem/commit/52aab65f2592012d1a79898bcba6e5829a566743 - based on real problem encountered during making https://github.com/rails/rails/pull/25052

**Comment by matkoniecz** [comment]
In this case it is caused by reformatting how `U+2028 LINE SEPARATOR` is saved in markdown file. This conversion may typically make sense but I prefer to have ability to stop such conversions.

**Comment by mitya57** [comment]
Looks like the line break is added by `QTextDocument::toPlainText()`, so I don't know any way to fix it…

Maybe you can submit a bug about this to Qt upstream?

**Comment by mitya57** [comment]
I have pushed a workaround to this issue, now U+2028 is no longer replaced. U+2029 is still replaced, but this is unavoidable…

**Comment by mitya57** [comment]
For some reason my commit fails on Travis. It looks like `cursor.selectedText()` sometimes replaces U+000A `\n` with U+0029 `)` and U+2028 with U+0028 `(`.

I cannot reproduce it, maybe this was a bug in an earlier Qt version, in this case I would need to revert my change.
