### ISSUE TITLE
[Feature Request] VIM Bindings

### ISSUE THREAD

**Issue by moorepants** [retext-project/retext#219]
I'd be more apt to use the software if it had it had optional vim bindings for basic text input.

**Comment by mitya57** [comment]
There is already a FakeVim mode, though maybe it's not very easy to set up…

@hluk If you are still interested in it, maybe you could write a wiki page explaining how to use it?

**Comment by hluk** [comment]
List of available emulated commands are at https://github.com/hluk/FakeVim/blob/master/README.md .

I'm not sure if there is anything specific for the library that needs clarification from user point of view.

Perhaps it's worth mentioning that the plugin here tries to [parse configuration at start](https://github.com/retext-project/retext/blob/c2aac655af166b5b70c5570c99b72ad9a8436c22/ReText/fakevimeditor.py#L178) from `$HOME/.vimrc` (`%HOMEPATH%\.vimrc` on Windows) so you can put some key bindings and commands there.

**Comment by moorepants** [comment]
It isn't clear how I would use FakeVim. Do I need to compile retext with support for it or something?

**Comment by hluk** [comment]
To install Python bindings for FakeVim you need to run following commands.

(You may need to install additional development packages on your system.)

```bash
git clone https://github.com/hluk/FakeVim.git
cd FakeVim
qmake && make
cd python && ./configure.py && qmake && make install
```

After successful installation you should be able to `import FakeVim` in python interpreter.

**Comment by mitya57** [comment]
I would add to @hluk's comment that to build FakeVim, you need to have PyQt5 development files installed. On Debian/Ubuntu, install `pyqt5-dev` package for that.

**Comment by mitya57** [comment]
I have just created a [wiki page](https://github.com/retext-project/retext/wiki/FakeVim-mode) about the FakeVim mode and pushed some fixed to master to make it work with the latest FakeVim.

So closing this issue.
