### ISSUE TITLE
[Feature Request] Option for one file one window with NO tabs

### ISSUE THREAD

**Issue by Menci** [retext-project/retext#223]
I like to use ReText on Linux, but one thing not perfect is the UI is too messy.

I want to put each file to a separate window and do NOT want the TabBar to show, like [MacDown](http://macdown.uranusjr.com/).

I tried to modify the source code but I am not so good in Python and Qt.

Can you add the option for it ? Thanks.

**Comment by mitya57** [comment]
I have added a `tabBarAutoHide` configuration option that will hide the tab bar when there is only one tab open. I hope this suits your needs.

To enable it, add this line to your configuration file (path is printed on startup):

    tabBarAutoHide=true

**Comment by Menci** [comment]
Good! Thanks!
