### ISSUE TITLE
Encoding of ReText's changelog.md is detected as iso-8895-2, not UTF-8

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#225]
ReText now detects is own `changelog.md` file as iso-8895-2 (with confidence 0.8317), not as UTF-8 which it really is, which makes the quotes appear incorrectly.

@starofrainnight, any ideas on how to deal with this?
Maybe bump the confidence threshold to a higher value like 0.85?

**Comment by starofrainnight** [comment]
I checked on my *.rst files, all encodings UTF8, GB2312, GBK and BIG5 are in confidence 0.99.
I think it's fine to change threshold above 0.90 or more (may be 0.95).
