### ISSUE TITLE
[Feature Request] The DOT Language (Graphviz)

### ISSUE THREAD

**Issue by p404** [retext-project/retext#226]
Hi,
It would be really cool if we can use the dot language to render graphs.

Thank you for your hard work!

**Comment by mitya57** [comment]
Are you requesting this as a separate markup, as a Markdown syntax extension, or as a reStructuredText directive?

**Comment by p404** [comment]
Sorry, a Markdown syntax extension

Cheers!

**Comment by mitya57** [comment]
Unfortunately I don't have any time to work on this. If someone writes a Markdown extension for this (see [the official documentation](http://pythonhosted.org/Markdown/extensions/api.html) for how to do that), I will make sure it integrates with ReText.

So closing the issue.
