### ISSUE TITLE
Use of Chinese writing Markdown and save, when open the file will be garbled

### ISSUE THREAD

**Issue by JadenTseng** [retext-project/retext#227]
The use of Chinese writing Markdown and save, when open the file will be garbled
1. Enter "中国" string
2. Save as Markdown file
3. Open previously saved Markdown file
4. We will see the interface appear garbled string

please help me! thanks

**Comment by starofrainnight** [comment]
I think this problem already solved in latest git master (6.1.0). 
Have tried in ubuntu 16.04, this situation does not happen.

Could you try install from git master ?

**Comment by Lin-Buo-Ren** [comment]
I use ReText everyday writing Chinese documents and not noticing this issue.
I'd suggest closing this issue as works-for-me

**Comment by starofrainnight** [comment]
@mitya57 This issue have no response from reporter for a year, and at least two people (I and @Lin-Buo-Ren)  confirmed this issue has gone (fixed), suggest closing this issue.
