### ISSUE TITLE
Not support the syntax "toctree" and  "only" for .RST

### ISSUE THREAD

**Issue by tidyjiang8** [retext-project/retext#228]
# Not support the syntax "toctree" and  "only" for .RST
I found that the retext doesn't support the syntax `toctree` and `only` for reStructuredText.
I'm not sure it's the retext issue or docutils issue.
![image 2](https://cloud.githubusercontent.com/assets/16730636/17081960/70906f94-519e-11e6-9e22-34627feef3ab.png)

**Comment by mitya57** [comment]
This are not standard reStructuredText directives, but rather Sphinx-specific extensions.

I agree it would be nice to have Sphinx support in ReText, but it is non-trivial to implement and is not something we claim to support at the moment.

**Comment by tidyjiang8** [comment]
Got it, Thanks anyway.
