### ISSUE TITLE
Disable for click Webkit renderer

### ISSUE THREAD

**Issue by cosmoscalibur** [retext-project/retext#230]
“Edit → Use WebKit renderer” menu is disable for click. Impossible to enable math in preview and in export options.
ReText version 6.0.1 and PyMarkups 2.0.0

**Comment by mitya57** [comment]
Hi,

This probably means that you do not have PyQt5.QtWebKit installed. Check with this command:

    $ python3
    >>> from PyQt5 import QtWebKit

If you are on a Debian/Ubuntu system, install the `python3-pyqt5.qtwebkit` package.

**Comment by cosmoscalibur** [comment]
Thanks!

**Comment by RoyiAvital** [comment]
Anyway to have it built in within the program?

For Windows users it will make things much easier.

Thank You.

**Comment by mitya57** [comment]
@RoyiAvital No, WebKit is a very huge thing, it makes no sense to embed it into ReText. You can find some pre-compiled binaries for Windows at https://github.com/annulen/webkit/releases/.

Alternatively, ReText 7 now supports Qt WebEngine renderer, which is built into PyQt wheels.

**Comment by RoyiAvital** [comment]
OK, Let's say I downloaded from https://github.com/annulen/webkit/releases/.

Where should I put it in order for ReText to be aware of it?

**Comment by RoyiAvital** [comment]
Any assistance?

Thank You.

**Comment by RoyiAvital** [comment]
@mwayne created amazing Portable Version of ReText:

https://portableapps.com/node/56132

It includes the WebKit Renderer needed for MathJax, Amazing!

Thank You.

**Comment by mitya57** [comment]
Looks like it was @2wayne (different nickname). So thanks should go to him :)

Anyone who wants to use the official version of ReText rather than a portable app, can just use the WebEngine renderer. Please report any bugs you find in it.

**Comment by RoyiAvital** [comment]
@mitya57 , What do you mean use "can just use the WebEngine renderer"?  
It's not available in Windows.

If you mean what you linked above, where can the user put the files in order to ReText to use them?

**Comment by mitya57** [comment]
@RoyiAvital If you install the latest versions of PyQt5 and ReText from PyPI, there should be a “Edit &rarr; Enable WebEngine (Chromium) renderer” option available.

**Comment by RoyiAvital** [comment]
I see.
I don't like the idea of installing too many things.
It doesn't work well on Windows (Portable packages are the way to go in my opinion).

The Portable version seems to be the thing I was looking for.

Thank You.

**Comment by Fugeny** [comment]
I have the same problem in manjaro(Arch). I found I have qtwebkit  2.3.4-7 in system, but there was not QtWebKit in python3.
from PyQt5 import qtwebkit
> cannot import name 'qtwebkit' from 'PyQt5'
There are any difference between qtwebkit  2.3.4-7 in pacman repository and python3? How can I install the qtwebkit in python3 to solve the problem.

**Comment by mitya57** [comment]
@Fugeny 2.3.4-7 is some very old version, maybe it was for Qt 4…

I do not use ArchLinux, but [this page](https://www.archlinux.org/packages/extra/x86_64/python-pyqt5/) suggests that if you install `qt5-webkit` and `python-pyqt5` then the import will work.

**Comment by PetersOtto** [comment]
I have the same problem after updating ReText and pip.

I use:
Ubuntu 16.04
ReText 7.04
pip/pip3 19.1.1

I did:
sudo apt-get install python3-pyqt5.qtwebkit

Have I to set a path from QT Webkit to ReText?

**Comment by mitya57** [comment]
@PetersOtto: If you installed PyQt5 from PyPI then it does not have Qt WebKit support.

You need to remove the PyQt5 installed from PyPI and let ReText use the distribution package.

Alternatively, you can install [PyQtWebEngine](https://pypi.org/project/PyQtWebEngine/) from PyPI, which also ReText can also use instead of WebKit.

**Comment by PetersOtto** [comment]
I installed PyQtWebEngine and it works :) 
Thank you!
