### ISSUE TITLE
synchronized scrolling for markdown

### ISSUE THREAD

**Issue by mock** [retext-project/retext#231]
i have enabled synchronized scrolling for markdown in version 6.0.1, and the preview is not automatically scrolling with the edit window. is there another plugin required to make this work? i've tried toggling the control with no difference.

**Comment by mitya57** [comment]
Hi,

You need to enable the WebKit renderer. Unfortunately it's not documented anywhere, but I'll make sure to update the wiki.

**Comment by mitya57** [comment]
Added a [note](https://github.com/retext-project/retext/wiki/FAQ#can-i-use-synchronized-scrolling) about this to the FAQ page.
