### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by N46AN** [retext-project/retext#232]
Hello, I'm using Retext 6.0.1 on Debian stretch and having trouble using markdown extensions.
I've followed these steps:
```sudo apt install retext```
```pip install markdown```
```pip install MarkdownSuperscript```
```echo "superscript" > ~/.config/markdown-extensions.txt```
Start Retext and type ```2^10^ is 1024.```

Expected behaviour: Get html output ```<p>2<sup>10</sup> is 1024.</p>```
Actual behaviour: Get html output ```<p>2^10^ is 1024.</p>```

This extension works fine in python: ```markdown('2^10^ is 1024.', ['superscript'])```

Any insight on what I'm doing wrong? #Thanks!

Edit: Changed extension name from 'superscript' to 'mdx_superscript' and it's still not working.
Edit: Using git-cloned 6.1.0 does not help either.

**Comment by mitya57** [comment]
Hi,
If you are on Debian, you should use `pip3` instead of `pip` (available in `python3-pip` package). For example:

    $ pip3 install MarkdownSuperscript --user

After that,  any of `superscript` and `mdx_superscript` should work.
Installing `markdown` is not needed as it is provided by a distro package.

**Comment by N46AN** [comment]
I followed your advice and it worked flawlessly.
Thanks very much for your attention on this issue!
