### ISSUE TITLE
silent crash when no language support installed

### ISSUE THREAD

**Issue by azrdev** [retext-project/retext#233]
Install retext (from archlinux repositories), but none of the language backends (python-markdown, python-docutils). Start retext from the GUI: nothing happens. Start it from the terminal: it quits with a traceback:

~~~
$  retext
Using configuration file: (...)
Warning: no markups are available!
Traceback (most recent call last):
  File "/usr/bin/retext", line 96, in <module>
    main()
  File "/usr/bin/retext", line 74, in main
    window = ReTextWindow()
  File "/usr/lib/python3.5/site-packages/ReText/window.py", line 210, in __init__
    self.setDefaultMarkup(defaultMarkup)
  File "/usr/lib/python3.5/site-packages/ReText/window.py", line 1118, in setDefaultMarkup
    defaultName = markups.get_available_markups()[0].name
IndexError: list index out of range
~~~

Especially when starting via a DE menu, a (graphical) error message would be better.

**Comment by mitya57** [comment]
Thanks for the report!
Can you please verify that the latest commit in `retext-6.0` branch fixes this?

**Comment by farseerfc** [comment]
Hi, I tested `retext-6.0`, it now quits with these tracebacks:
```
Using configuration file: /home/farseerfc/.config/ReText project/ReText.conf
Warning: no markups are available!
Traceback (most recent call last):
  File "retext.py", line 96, in <module>
    main()
  File "retext.py", line 90, in main
    window.createNew(inputData)
  File "/home/farseerfc/github/retext/ReText/window.py", line 642, in createNew
    self.createTab("")
  File "/home/farseerfc/github/retext/ReText/window.py", line 460, in createTab
    self.currentTab = ReTextTab(self, fileName, self.defaultMarkup,
AttributeError: 'ReTextWindow' object has no attribute 'defaultMarkup'
```

**Comment by mitya57** [comment]
@farseerfc Whoops :) What about now?

**Comment by farseerfc** [comment]
@mitya57 It can start properly now, with the preview panel says "Could not parse file contents, check if you have the necessary module installed!". Thanks!
Should I package this fix into the Arch Linux repository now? Or should I wait for a bug-fix release (maybe 6.0.2)?

**Comment by mitya57** [comment]
Can you make the Arch package depend on Python-Markdown instead?

I am not going to make a new release soon.

**Comment by farseerfc** [comment]
Both `python-markdown` and `python-docutils` are optional dependencies for `retext` for now.
https://www.archlinux.org/packages/community/any/retext/
The problem is `pacman` will not install optdepends automatically, therefore users will only see a notice during the install. They are expected to manually install at least one of them.
I don't want to specify a hard dependency as installing either one is sufficient.
I will contact the maintainers for these packages to see whether we can introduce a virtual dependency here.

**Comment by mitya57** [comment]
Then please backport the fixes from retext-6.0 branch, I don't think I will make a 6.0.2 release in the near future.

**Comment by farseerfc** [comment]
Thanks for the suggestion, I have backport the fixes.

**Comment by mitya57** [comment]
@farseerfc Thanks for your work on packaging ReText! :)
