### ISSUE TITLE
option to disable inclusion of extra extension

### ISSUE THREAD

**Issue by bearsh** [retext-project/retext#235]
according to the [wiki](../wiki/Markdown-extensions) the extra extension is enabled by default. Unfortunately according to [pymdown-extensions/usage_notes](http://facelessuser.github.io/pymdown-extensions/usage_notes/) the extra extension is not compatible with some extensions from that packages. 

So it would be nice to have an easy way to disable the inclusion of the extra extension.

**Comment by mitya57** [comment]
Just add `remove_extra` to the list of extensions. I will document that a bit later.

**Comment by bearsh** [comment]
thanks! seems to work fine 😄

**Comment by mitya57** [comment]
The wiki page is now updated.
