### ISSUE TITLE
Unknown directive type "graphviz".

### ISSUE THREAD

**Issue by NikitaEgorov** [retext-project/retext#238]
What can i do with message "Unknown directive type "graphviz"."?

**Comment by mitya57** [comment]
It says what it says: ReText does not currently support this directive (in fact, it supports only what it documented in the [official reStructuredText specification](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html)).

Maybe there will be support for graphviz in some future version, but I cannot give any promises on this.

**Comment by NikitaEgorov** [comment]
Could you suppress this error message, and show directive content as text?

**Comment by mitya57** [comment]
You can suppress the error, but you can't show the content as text.

To suppress the errors, put this in your `~/.docutils`:

```ini
[standalone reader]
report_level = 5
halt_level = 5
```

**Comment by chadyred** [comment]
As see here in doc of python, in your project, you have to install this package
```
pip install graphviz
```

**Comment by mitya57** [comment]
Can you please test the linked PyMarkups commit (in `wip/graphviz` branch) and check if it works for you?

**Comment by mitya57** [comment]
I had to revert my changes because they rely too much on internals of Sphinx and can cause crashes when Sphinx is updated.

So the status of this bug is “won’t fix” for now.
