### ISSUE TITLE
New locale: es_CO

### ISSUE THREAD

**Issue by sirgazil** [retext-project/retext#240]
Hi,

This is a [retext_es_CO.ts][1] translation file for Colombian Spanish. I didn't attach it to this issue because GitHub says it is not supported (ReText FAQ needs to be updated in that regard).

I tested the locale in ReTex 6.0.1, and I'm already using it.

Thanks,

[1]: https://bitbucket.org/sirgazil/dnd/downloads/retext_es_CO.ts

**Comment by mitya57** [comment]
Thanks a lot for the translation! I will be able to commit it next week.

Also indeed the documentation is outdated (comes from times when we were on SourceForge). Maybe I should update it to recommend using pull requests.
