### ISSUE TITLE
Feature Request: change the text size (zoom in/out)

### ISSUE THREAD

**Issue by dmarrazzo** [retext-project/retext#244]
It would be nice having the option to change the editor text size.
If you give me some hint, I can try to implement it.

**Comment by mitya57** [comment]
Edit &rarr; Change editor font. Isn’t this what you need?

**Comment by dmarrazzo** [comment]
Yes, it's exactly what I was looking for!
I was expecting to find it in the preferences.
Anyway, what about of adding a couple of button on the toolbar.
I don't know if it's too difficult but it would be nice to react to "CTRL+scroll" (like in the browsers)
