### ISSUE TITLE
Toolbar icons are missing on Windows

### ISSUE THREAD

**Issue by yaomtc** [retext-project/retext#246]
On OS X I see there's workarounds, but on Windows I'm totally stuck. These seem to be the standard paths:

> "/usr/local/share/icons", "/usr/share/icons", "/usr/share/pixmaps", ":/icons"

None of the first three exist on Windows. As for the last one, I assume it means inside the application directory? Like this?

> C:\Users\chris\AppData\Local\Programs\Python\Python35-32\share\retext\icons

If that's correct, then a theme should go there. I had a difficult time finding one I could just download onto Windows, but I did find this: https://github.com/pasnox/oxygen-icons-png/

I extracted the folder from the ZIP and put it at the aforementioned location. Then I went into ReText preferences and tried to get it to see the theme. Name "Oxygen", stylesheet "oxygen.qrc", no dice. Is there supposed to be a .qss file? Is a stylesheet necessary? Am I putting stuff in the wrong place? Is ReText just broken on Windows right now? I'm lost.

**Comment by mitya57** [comment]
Hi,

The paths depend on how you installed Python and/or ReText. You can check where the `retext.png` file is installed, and that would be the right directory.

Then, there is no concept of icon themes on Windows. So you should just unpack the contents of the [icons pack](https://sourceforge.net/projects/retext/files/Icons/) into that directory. It should work on next start, without any need to edit stylesheet or settings.

**Comment by yaomtc** [comment]
That fixed it, thanks!

**Comment by f8ttyc8t** [comment]
Tried above steps without success, Mainly because location to store icons mentioned by @mitya57 was not clear to me.
Dropping them to folder 

> /Users/[username]/Library/Application Support/retext/icons/ 

solved it for me. (you maybe need to create /retext/icons/ folder by yourself)

Anyway, great tool - thanks!
