### ISSUE TITLE
Save not working correctly

### ISSUE THREAD

**Issue by elija** [retext-project/retext#250]
ReText 6.0.0
openSUSE Leap 42.2 Plasma 5

Pressing Ctrl + S pops up a File box for Save as, rather than saving the file as named.

**Comment by mitya57** [comment]
Can you please take a screenshot of the window when you are trying to press Ctrl+S?

Also, do you have auto-save or other non-standard options enabled? If you could attach your configuration file (ReText prints path to it to stdout on start), that would be also nice.

**Comment by elija** [comment]
Yeah no worries.

![first-save-ok](https://cloud.githubusercontent.com/assets/2338264/21679341/835fd910-d33b-11e6-9f52-d847fcd01639.jpg)
The first time I hit Ctrl+S, it works as expected.

![second-save-not-ok](https://cloud.githubusercontent.com/assets/2338264/21679361/9e45de46-d33b-11e6-982c-39d474346187.jpg)
The second time, it doesn't register that the file has already been saved.

![second-save-exists](https://cloud.githubusercontent.com/assets/2338264/21679378/b376b434-d33b-11e6-98e0-645c9b49f93d.jpg)
It basically does the same thing as Save As.

I do use quite a few custom settings. I had to add a .txt extension to get the configuration file to upload.

[ReText..conf.txt](https://github.com/retext-project/retext/files/687150/ReText.conf.txt)

**Comment by mitya57** [comment]
According to your configuration file, you have auto-save enabled. There was a known bug with broken auto-save in ReText 6.0.0 (#208), it was fixed in 6.0.1. Please upgrade to the new version.

**Comment by elija** [comment]
Brilliant. Thank you.
