### ISSUE TITLE
org-mode as additional markup?

### ISSUE THREAD

**Issue by kiuuik** [retext-project/retext#256]
just an idea: there are many die-hard fans of emacs org-mode. Sometimes files need to be shared with people who don't use emacs. For these people it would be great if they could edit and preview org files in ReText. (I don't mean advanced features of org like task scheduling. I'm only talking about the standard syntax for headlines, links, code blocks, bold/italic/underline etc.) At the moment I can't find any other easy-to-use editor for lightweight markup languages that supports org-mode. Vim isn't an alternative for most people and many people won't pay for the closed source SublimeText which requires abandoned org-mode extensions/packages.
I don't see any good alternatives. I think it is too hard to customize emacs in a way so that it behaves exactly like a "standard" editor. And people might accidently break such a configuration. Converting org files to md and back multiple times isn't a good option either.
I only post this idea here because ReText is the only editor among the many MD-Editors that offers other markup languages like reST. Offering org-mode would strengthen ReTexts reputation as a universal lightweight markup editor. ReText is part of many Linux distributions so that in the end many people would benefit from this feature.

**Comment by mitya57** [comment]
Hi @kiuuik!

Do you know any library or a script that can convert Org Mode to HTML? So far I found only Pandoc, but I never used Org Mode myself so I cannot measure how much of the features are implemented or not implemented there.

**Comment by kiuuik** [comment]
Sorry for the late answer. At the moment I'm not at home. 

About a library: I don't. When I need some html I use exporter that is built in emacs-orgmode. My first thought would have been pandoc, too. Maybe the [github-markup](https://github.com/github/markup#markups) library which supports org-to-html? But I'm just a user and don't know much about programming.
