### ISSUE TITLE
Feature request: configuration option to start ReText in Preview mode instead of editing mode

### ISSUE THREAD

**Issue by keesse** [retext-project/retext#257]
Since notes are being written to be reread later, I most of the time want to read them and not edit them, therefor I would like to have an option in the configuration to start in Preview mode

**Comment by mitya57** [comment]
With the current code you can:

* Open files in preview mode by passing `--preview` before their names on the command line;
* Enable _live_ preview by default using the `livePreviewByDefault` configuration option.

**Comment by samuliasmala** [comment]
If you want to open the files in preview mode when opening them from file browser you can run to following command to create .desktop entry with `--preview` flag (tested in Ubuntu 18.04):

`sed '/Exec/ s/retext.py/retext.py --preview/' /usr/share/applications/me.mitya57.ReText.desktop > ~/.local/share/applications/me.mitya57.ReText.desktop`

**Comment by mitya57** [comment]
This option was added in #435. Now (with the latest commit from master branch) you can set `defaultPreviewState=normal-preview` in your [configuration file](https://github.com/retext-project/retext/blob/master/configuration.md) and new tabs will be opened in preview mode by default.
