### ISSUE TITLE
LoadLibrary failed with error 1114

### ISSUE THREAD

**Issue by masbicudo** [retext-project/retext#258]
When I run `retext.bat` it shows a dialog with this message: LoadLibrary failed with error 1114.

My environment:
- Windows 10
- Python 3.6 32 bits, installed at `C:\Python\Python36\`
- command used to install `pip3 install ReText`

Installed without errors.

When I run `retext.bat`, it's just the message box. Nothing in `stderr` nor `stdout`.

Path items: containing "python" string:
```
C:\Users\Miguel Angelo>pathlist | findstr /i python
C:\Python\Python36-32\Scripts\
C:\Python\Python36-32\
C:\Python27\Lib\site-packages\PyQt4
C:\Python27
C:\Python27\DLLs
C:\Python27\Scripts
C:\Python27\gnuplot\binary
C:\Program Files (x86)\pythonxy\SciTE-3.5.1-4
C:\Program Files (x86)\pythonxy\console
```

Unfortunately I don't have a clue on how to debug it to be more helpful... but I can do that if someone tells me how.
Thanks!

**Comment by mitya57** [comment]
I am not using Windows, so I have no clue what this error code is about.

Can you please try running Python and checking whether you can enter `import PyQt5.QtCore` or `import ReText` there?

**Comment by masbicudo** [comment]
I have discovered that the problem is with my computer. It's an HP notebook with dual graphics, one low profile, and another high profile. The problem occurs only when the system is using the low profile graphics card.

This depends on the power configurations of the computer (the setup screen) and also of the specific OS, in my case WIndows 10. I can manually switch the graphics card being used by switching Windows power plan.

This is probably due to Qt using some sort of graphic acceleration that gets confused by the dual graphics configuration of this notebook.

All I have to say is that this is a bizarre consequence of this dual graphics thing.
