### ISSUE TITLE
Document does not display accents in Spanish

### ISSUE THREAD

**Issue by ManuelPimienta** [retext-project/retext#263]
I am using the program in Spanish, when editing the text the 
accent mark are shown, but when opening the document again they do not appear.
For example: 

> aplicaci?n

Thanks for the program.

**Comment by mitya57** [comment]
Hi @ManuelPimienta!
Please be more verbose and specify:

* Which version of ReText are you using, and on which OS?
* What is the encoding of the source document? (Maybe you can attach it?)
* Does it change when you open it for the first time and for the second time? If it changes, then how?
* Does the problem occur if you disable encoding auto-detection? (I.e. add `detectEncoding=false` to the configuration file).

Without answers to (at least some of) these questions it is impossible to guess what is happening on your system.

**Comment by ManuelPimienta** [comment]
ReText 7.0.0(PyMarkups 2.0.0)
Antergos Linux x86_64 
Linux 4.9.8-1-ARCH
The encoding is set by default in the program.
`$ file -i Ideasdeproyectos.md`
> Ideasdeproyectos.md: text/plain; charset=us-ascii

Whenever I open the document does not show the accents. And finally I can't find the configuration file.

Thanks

**Comment by mitya57** [comment]
Can you please attach the document? Or base64 and paste it here?

The path to configuration file is printed to stdout when you start ReText.

**Comment by ManuelPimienta** [comment]
Well I think the problem was that I created the file with _**Kate Editor**_, and opening it with **ReText** shows that error. Anyway here is the file.
[texto.zip](https://github.com/retext-project/retext/files/839988/texto.zip)
Thanks for your attention.

**Comment by mitya57** [comment]
Sorry but your file contains a literal question mark (`?`, byte 0x3f). There is no surprise that ReText shows it.

Do you have this error when you create your file in ReText, not in Kate?

**Comment by ManuelPimienta** [comment]
Okay, I did a test.
I created two documents, one with Kate and one with Retext, and I wrote some words in Spanish. Then I opened both documents with Kate and Retext. Retext still shows the errors in both documents but Kate does not.
I opened Retext for the first time with a .md document previously created with Kate, but it did not show me the configuration options.
![screenshot_20170315_114505](https://cloud.githubusercontent.com/assets/20049211/23961005/90642374-0977-11e7-96fc-c8dfc62bd4a8.png)
These are the files:
[test.zip](https://github.com/retext-project/retext/files/845391/test.zip)

**Comment by mitya57** [comment]
It looks like ReText (for some reason) detected encoding as ISO/IEC 8859-11. Can you try disabling encoding auto-detection and see if it helps? To do so, close ReText, run this command in a console and start ReText again.
```bash
echo "detectEncoding=false" >> "$HOME/.config/ReText project/ReText.conf"
```

If that does not help, please force ReText to use UTF-8 encoding (Archivo → Establecer codificación, select “UTF-8”, press OK) and tell me if *that* helps.
