### ISSUE TITLE
After successful install with `pip3...`, I cannot launch executable.

### ISSUE THREAD

**Issue by dajare** [retext-project/retext#266]
I'm quite sure this is user error, not a ReText bug -- but I'm not sure where else to turn.

**Environment**
Ubuntu 16.04LTS using Xfce desktop.

**What I did**  
- I installed latest ReText using command `pip3 install ReText`.
- It installed swiftly and successfully, and launched at that point. I have used ReText before, and opened a couple Markdown files to see how the new version was looking. All good!
- I closed ReText and carried on with other things.

**What happened next**  
- When I tried to start ReText later ... nothing. There is no ReText entry in the menu system, and running ReText from the command line tells me that `The program 'retext' is currently not installed.`
- When I look in `~/.local/lib/python3.5/site-packages/markdown` there is quite a bit of stuff, all with the correct time-stamp.

[![Imgur](http://i.imgur.com/8k1zYtmm.png)][1]

There must be a method of launching ReText having installed it this way -- but I cannot find it. Any help appreciated!

[1]: http://i.imgur.com/8k1zYtm.png  "Click for full-sized image"

**Comment by dajare** [comment]
Doh! It was a PATH problem -- found the information I needed on [AskUbuntu](http://askubuntu.com/q/799302/38585). Just in case anyone else needs the kind of help I needed:

- executable is in `~/.local/bin/`
- that directory needs to be [added to the `PATH` environment](http://askubuntu.com/q/60218/38585).

**Comment by mitya57** [comment]
Right, I just wanted to say the same :)

Also if you are using Ubuntu, the easier way to install ReText would be to get it from Ubuntu repositories (using apt or the Software Center).

**Comment by dajare** [comment]
@mitya57 Thanks! I thought about installing from PPA, but it is still at version 5.3.1, and I was looking forward to using the latest and greatest version. :grin: 

I've got a couple other funny things happening (no `syncScroll` behaviour; always opens maximized even though `saveWindowGeometry` is set to `true`), but I'm pretty sure that's some weirdness on my system, and not a ReText issue.

**Comment by mitya57** [comment]
> always opens maximized even though `saveWindowGeometry` is set to `true`

ReText itself does not maximize your window. It is probably done by your window manager…

> And I'm not sure how to hook-up ReText's icon -- do I need to create a `retext.desktop` file?

You should have a `~/.local/share/applications/me.mitya57.ReText.desktop` file — can you please check if it exists? If for some reason Xfce does not pick it up (even after re-login), try using the full path to `retext` executable in the `Exec=` line.
