### ISSUE TITLE
Missing application icon in Xfce menus after `pip3...` install

### ISSUE THREAD

**Issue by dajare** [retext-project/retext#267]
After installing ReText 7.0 using `pip3...` in Ubuntu 16.04LTS+Xfce desktop, I was getting the ReText icon in the "panel", but not in the menus (Xfce's own application menu, and ClassicMenu Indicator).

This was [mentioned while piggy-backing on a previous issue][1], but it seems worth an entry of its own.

I can confirm:
- there is a `~/.local/share/applications/me.mitya57.ReText.desktop` file created;
- giving the absolute path for the `Exec=` line did **not** make any difference;
- I tried omitting the `%F` argument, enclosing in quotes, giving full path for the `Icon=` line ... none of these made any difference.

There might be something about an icon cache lurking here, but I've solved it with this workaround for the moment, having seen these items:
- [Some icons are broken in the application menu][2]
- [PyQt not showing QSystemTrayIcon on XFCE / Ubuntu 16.04 Xenial Xerus][3]
- and "Desktop" documetation on  "[Extra actions][4a]" + "[Application icons][4b]"

The **workaround** was to save a copy of [ReText's `svg` icon][ico] as `~/.local/share/icons/hicolor/scalable/apps/retext.svg`, and that has satisfied both the Xfce menu, and ClassicMenu Indicator.

[ico]: https://github.com/retext-project/retext/blob/master/icons/retext.svg
[2]: http://unix.stackexchange.com/q/140179/99759
[3]: http://stackoverflow.com/q/34054092/232251
[4a]: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions
[4b]: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#install_icons
[1]: https://github.com/retext-project/retext/issues/266#issuecomment-283023774

**Comment by mitya57** [comment]
> The **workaround** was to save a copy of [ReText's `svg` icon](https://github.com/retext-project/retext/blob/master/icons/retext.svg) as `~/.local/share/icons/hicolor/scalable/apps/retext.svg`, and that has satisfied both the Xfce menu, and ClassicMenu Indicator.

Thanks for the hint, I will make setup.py install such a copy.
