### ISSUE TITLE
Weird artifacts on Ubuntu/XFCE when using Chromium renderer

### ISSUE THREAD

**Issue by xgouchet** [retext-project/retext#269]
When a preview is displayed using the Chromium renderer, the top part of the window blinks between normal and black (see screenshot attached). The black area changes everytime the mouse overs a new element, and the size of the area changes (it's sometimes just one pixel high, but on the whole width of the window, sometimes as big as on the screenshot). 

![Screenshot](http://i.imgur.com/P15JSVg.png)

**Comment by xgouchet** [comment]
Ok the bug seems to have disappeared after updating my OS.

**Comment by mitya57** [comment]
It still sounds weird to me. If WebEngine can access something outside its widget, it is either a serious bug or a vulnerability…
