### ISSUE TITLE
Window geometry not saved, ReText always launches maximized

### ISSUE THREAD

**Issue by dajare** [retext-project/retext#271]
Like the subject says, whenever I launch ReText, it opens maximized, even though I have set `windowGeometry=true` in my ReText.conf file. All other settings load properly.

The window geometry line itself currently reads:

    windowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\x1\x6\0\0\0T\0\0\x4\x8a\0\0\x3\x1a\0\0\x1\a\0\0\0l\0\0\x4\x89\0\0\x3\x19\0\0\0\x1\0\0\0\0\x6\x90)

I'm using Ubuntu 16.04LTS with the Xfce desktop; ReText is version 7.0.0 (using PyMarkups 2.0.0). I have a dual-monitor set up with that computer, if that makes a difference.

**Comment by mitya57** [comment]
Can you please try the branch `issue271` (the commit is linked) and see if it fixes your bug?

**Comment by dajare** [comment]
I have to wait for Monday, but will let you know a.s.a.p. Thanks for the reply!

**Comment by dajare** [comment]
That fixed it! (Was it really simply additional indent?!) Thanks for the help!

**Comment by mitya57** [comment]
Indents are significant in Python :)

I have now merged this into master.
