### ISSUE TITLE
Keyboard layout switching not work

### ISSUE THREAD

**Issue by andrewanswer** [retext-project/retext#272]
I install ReText 7.0.0 on fresh Ubuntu 16.04 LTS via pip:

`sudo apt install python3-pip`
`pip3 install ReText`

and run it. I haven't app icon, but more annoying what I cannot switch keyboard layout (EN/RU) with Ctrl+Shift. ReText always use layout which set on application start.

Please fix it.

**Comment by mitya57** [comment]
Hi @andrewanswer!

Do you have (Py)Qt5 installed from the Ubuntu repositories, or from PyPI?
Also, which desktop are you using? Unity?

**Comment by andrewanswer** [comment]
Hi, I use Qt5 installed:
`$ pip3 list
...
PyQt5 (5.8.2)
...
ReText (7.0.0)
...
`
and
`
$ apt list *qt* --installed
...
libqt5core5a/xenial-updates,now 5.5.1+dfsg-16ubuntu7.2 amd64
...
libqtcore4/xenial,now 4:4.8.7+dfsg-5ubuntu2 amd64
...
`

**Comment by andrewanswer** [comment]
Today, I install ReText to another computer, with Ubuntu 16.04 LTS too, and stuck where it's located after installation. Typing 'retext' in terminal suggest me install retext via apt. Searching 'retext' find executable script in '~/.local/bin'. Finally, I run it, and check keyboard layout switching. No success, problem still exist :(

**Comment by mitya57** [comment]
Please try using PyQt5 from the distro packages, not from PyPI. The PyPI package is missing some important platform integration plugins.

(Sorry for not responding earlier.)

**Comment by mitya57** [comment]
If you installed PyQt5 5.8.x from PyPI, then most likely you are hit by [QTBUG-59064](https://bugreports.qt.io/browse/QTBUG-59064). It is already fixed in Qt 5.9, however there is no 5.9-based PyQt wheel yet.

Closing as it is a Qt bug, not a ReText one.
