### ISSUE TITLE
conflict with retext 5.0 debian jessie

### ISSUE THREAD

**Issue by profjlg** [retext-project/retext#275]
How could I uninstall retext 7.0 ?

**Comment by profjlg** [comment]
I go on with this issue to clarify the word "conflict". 
I'd like to use retext 7.0 with debian jessie so I tried to install it according the steps described. The problem is how to reconcile python 2.7 and
python 3 requested by Retext ?

Now,  I must do \usr\bin\retext to execute retext 5.0 because by writing "retext" in the terminal I get "PyMarkups 2 is needed". But what il the correct way to install PyMarkups ?

**Comment by mitya57** [comment]
How did you install ReText 7.0?

If you used `pip3 install ReText --user` (the recommended way), then the correct way to uninstall it would be `pip3 uninstall ReText`. But in that case `pip3` would also install PyMarkups 2, which looks like it didn’t happen.

If you installed it using `setup.py install` from this repository, then you can get the missing dependency using `pip3 install "Markups>2.0" user`.

**Comment by profjlg** [comment]
by pip3 install ReText --user I get 

`Requirement already satisfied (use --upgrade to upgrade): ReText in /usr/local/lib/python3.4/dist-packages
Cleaning up..`

and then

$ retext 
Error: ReText needs PyMarkups 2.0 or newer to run.

**Comment by mitya57** [comment]
Try what I suggested:

    pip3 install "Markups>2.0" --user

**Comment by profjlg** [comment]
> Downloading/unpacking

>  Markups>2.0
>  Could not find a version that satisfies the requirement Markups>2.0 (from versions: 2.0.0, 1.0.0, 0.2.2, >0.3, 0.2.1, 0.2.3, 0.5.0, 0.6.1, 0.5.2, 0.5.1, 0.6.0, 0.2.4, 0.4, 1.0.1, 0.6.3, 0.2)
>Cleaning up...
>No distributions matching the version for Markups>2.0

**Comment by mitya57** [comment]
Hm, pip has an unusual understanding of versions…

Try `pip install Markups==2.0.0 --user` then.

**Comment by mitya57** [comment]
> The necessary modules aren't automatically installed ?

They would be installed if you installed ReText with `pip install ReText`. Now you can add them manually with `pip3 install Markdown docutils --user`.

**Comment by profjlg** [comment]
Sorry Dmitry I get the same message by Retext. 
In the terminal it's said 
'Requirement already satisfied (use...etc) Markdown in usr/lib/python3/dist-packages'
And the same for docutils




Envoyé de mon Galaxy S5 4G+ Orange

-------- Message d'origine --------
De : Dmitry Shachnev <notifications@github.com> 
Date : 16/04/2017  22:34  (GMT+01:00) 
À : retext-project/retext <retext@noreply.github.com> 
Cc : profjlg <jean-louis.gallinari@orange.fr>, Author <author@noreply.github.com> 
Objet : Re: [retext-project/retext] conflict with retext 5.0 debian jessie
  (#275) 


The necessary modules aren't automatically installed ?

They would be installed if you installed ReText with pip install ReText. Now you can add them manually with pip3 install Markdown docutils --user.

**Comment by profjlg** [comment]
Well it seems I can't install retext so I give up.
In fact I must say it's not clear at all how to install retext another way that by apt retext.
Now I can't use retext 5.0 any more...
There's a mix between retext and ReText and I don't see wich one exactly...

**Comment by mitya57** [comment]
As I am the developer of both ReText and Debian, I want to clarify what is going on here:

1. The distribution packages are always the preferred way of installing software. The package manager takes care of all dependencies and makes sure all components are compatible with each other.
2. PyPI sometimes contains newer versions of software. But if you want to use pip, you must know how it works. In particular:
    * You should never run pip or `setup.py` as root (i.e. `sudo pip install …`). It can mess up with your system pretty badly. See pypa/pip#1872 for details.
    * If you ran it as root by mistake, please clean the contents of `/usr/local/bin` and `/usr/local/lib/python*` directories.
    * When you run pip (or `setup.py`) as `--user` ([default](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=725848) in Debian Stretch), it will install stuff to your `~/.local` directory instead. That directory is much easier to clean up. If something that you installed there does not work, please clean the contents of `~/.local/bin` (with care) and `~/.local/lib/python*` directories.

Now you say that there is some problem with Markdown. I guess this happens because you have [Python-Markdown 2.5.2](https://packages.debian.org/jessie/python-markdown) from Debian Stretch, but the new PyMarkups requires version at least 2.6.

Then it is quite easy to fix: just run `pip3 install "Markdown>2.6" --user`

**Comment by mitya57** [comment]
You also tell that “it's not clear at all how to install retext another way that by apt retext”.
Actually we have a dedicated page in the wiki for installation issues. See [Installing ReText][1].
In my opinion it contains the needed information (i.e. the first command will just work if you don’t have any conflicts with the system packages). But if you can suggest some improvements, they will be welcome.

[1]: https://github.com/retext-project/retext/wiki/Installing-ReText

**Comment by profjlg** [comment]
thanks for these details.

> If you ran it as root by mistake, please clean the contents of /usr/local/bin and /usr/local/lib/python* directories.

I'm not sure I did it but...
could you say precisely which files must be deleted : 

![2017-04-23-141013_1366x768_scrot](https://cloud.githubusercontent.com/assets/20831904/25313492/f7b79700-282f-11e7-8365-f51feb362fdd.png)


> When you run pip (or setup.py) as --user (default in Debian Stretch), it will install etc...

And then 

```
ls ~/.local/lib/
python3.4
```

`ls ~/.local/bin/
markdown_py`

and now

`~$ retext
Traceback (most recent call last):
  File "/usr/bin/retext", line 25, in <module>
    from ReText.window import ReTextWindow
  File "/usr/share/retext/ReText/window.py", line 12, in <module>
    from ReText.webpages import wpInit, wpUpdateAll
  File "/usr/share/retext/ReText/webpages.py", line 10, in <module>
    from markups.web import WebLibrary
ImportError: No module named 'markups.web'`

> Then it is quite easy to fix: just run pip3 install "Markdown>2.6" --user, and the problem should be solved.

I did it...But I don't understand what's wrong...
I can run ReText as root only

Thanks for your advices

**Comment by mitya57** [comment]
Your last comment indicates that you installed PyMarkups from PyPI, but ReText from Debian packages.

As I already told, you should not mix the versions. Either:
* remove `~/.local/lib/` and `~/.local/bin/` directories and use everything from Debian (the easiest variant),
* or install ReText from PyPI properly (if pip is missing on your system, then it is available in `python3-pip` package).

**Comment by profjlg** [comment]
Thanks a lot

What do you mean by "properly" ? 

when I try the command pip list I get a message saying pip in not known and when I try to install python3-pip I get python3-pip is already installed on my system...

I finally use Geany and all is fine

**Comment by mitya57** [comment]
The command name for Python 3 is `pip3`, not `pip`.

**Comment by profjlg** [comment]
Well

let's try to begin a correct way...

as it is said [here](https://github.com/retext-project/retext/wiki/Installing-ReText) I used the command

`$ python3 -m pip install ReText  --user`

which gives

`/usr/local/bin/python3: No module named pip`

what have I to do now ?

**Comment by mitya57** [comment]
What is `/usr/local/bin/python3`? If you have this file, you are having more problems because it takes preference over system Python 3 and is incompatible with system modules.

If you need a custom interpreter somewhere, I would suggest you to use a virtualenv, not install it globally.

**Comment by profjlg** [comment]
![2017-05-30-102013_408x40_scrot](https://cloud.githubusercontent.com/assets/20831904/26574556/12001c7c-4522-11e7-9b98-8cf5b9363ef1.png)
