### ISSUE TITLE
Where are the menu icones ?

### ISSUE THREAD

**Issue by profjlg** [retext-project/retext#276]
Debian 8 : retext 5.0

the menu icones are not visible as shown

![2017-04-12-091118_1366x768_scrot](https://cloud.githubusercontent.com/assets/20831904/24945900/578cb606-1f61-11e7-8c81-9204d3fcee88.png)

**Comment by mitya57** [comment]
The automatic icon theme detection was implemented in ReText 5.2, please upgrade to that version or a newer one.

If you want to stick to 5.0, you can use the workaround: open Edit → Preferences, and enter your icon theme name there.
