### ISSUE TITLE
\varnothing not recognised

### ISSUE THREAD

**Issue by profjlg** [retext-project/retext#277]
As written in the title, the LaTeX expression $\varnothing$ is not recognised ; 
How should I do to use $\varnothing $ instead of $\emptyset$ which is not very nice though it can be used by Retext ? 
Thanks

**Comment by mitya57** [comment]
This will be fixed in the next pymarkups release. As a temporary workaround, you can add this on top of your Markdown file:
```html
<script type="text/javascript">
MathJax.Hub.Config({
  TeX: { extensions: ["AMSmath.js", "AMSsymbols.js"] }
});
</script>
```

**Comment by profjlg** [comment]
Done and it's okay
Thanks
