### ISSUE TITLE
Feature request: Jekyll YAML front matter

### ISSUE THREAD

**Issue by rfinnie** [retext-project/retext#279]
I use ReText to edit Jekyll markdown posts, and it works well for this task.  One minor issue is the [YAML front matter](https://jekyllrb.com/docs/frontmatter/) at the top of the posts, which is rendered in the preview as a single paragraph.  Some nice features for ReText would be:

* Recognize YAML front matter
* Render it as preformatted text in the preview
* Have an option to hide it in the preview
* Parse and validate the front matter as valid YAML, to avoid formatting errors while writing

Thanks!

**Comment by mitya57** [comment]
YAML front matter support was once part of Python-Markdown, but then got dropped as a result of waylan/Python-Markdown#390.

However there is a [third-party extension](https://github.com/teoric/python-markdown-yaml-meta-data) which works for me. You just need to copy it to your Python path, i.e. <code>~/.local/lib/python3.*x*/site-packages/</code>, and then add `meta` and `meta_yaml` to the Markdown extensions list in ReText configuration dialog.

If the YAML can be parsed, it just hides the metadata. If there are errors, it acts like if it were not front matter. Is this behavior good for you?
