### ISSUE TITLE
Provide uniform look in GNOME Shell

### ISSUE THREAD

**Issue by theel0ja** [retext-project/retext#280]
ReText's layout isn't uniform in GNOME Shell.

![image](https://cloud.githubusercontent.com/assets/5832930/25591380/f63646b8-2ebc-11e7-9187-709f8b36f081.png)
GNOME Shell ([Flat-Plat](https://github.com/nana-4/Flat-Plat) theme and [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icons)

![image](https://cloud.githubusercontent.com/assets/5832930/25591419/1795e1e2-2ebd-11e7-8560-ac018941bef8.png)
Cinnamon ([Flat-Plat](https://github.com/nana-4/Flat-Plat) theme and [Numix](https://github.com/numixproject/numix-icon-theme) icons)

**Comment by mitya57** [comment]
Sorry, but what do you mean by “uniform look”? Do you mean that the Preview button has no icon?

Or you mean that ReText should have no menubar, or something else?
