### ISSUE TITLE
Question: Math support: How to let ReText support \implies ?

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [retext-project/retext#282]
Currently `\implies` command renders to `Undefined control sequence \implies` in preview panel, but it is listed as supported via AMSsymbols extension in [Mathjax's documentation](http://docs.mathjax.org/en/latest/tex.html#supported-latex-commands), how to support this command in ReText?

Current extension settings: codehilite, inlinehilite, github  
Retext version: 5.3.1

**Comment by mitya57** [comment]
Please see my reply in #277. I hope there will be a new PyMarkups release soon.

**Comment by Lin-Buo-Ren** [comment]
Great, thanks!
