### ISSUE TITLE
Feature request: Add support for CriticMarkup

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#284]
http://criticmarkup.com/

CriticMarkup makes it MUCH easier to collaborate on Markdown projects.

**Comment by mitya57** [comment]
Hi, please see my earlier response in https://github.com/retext-project/retext/issues/142#issuecomment-139895812. Basically I have neither time nor interest in this, but I would be open to a pull request if anything specific needs to be done in ReText about this.

**Comment by xgouchet** [comment]
Critic Markup can be used in ReText using [Markdown extensions](https://github.com/retext-project/retext/wiki/Markdown-extensions), with the extension `pymdownx.critic`

**Comment by mitya57** [comment]
Thanks @xgouchet for pointing the [`pymdownx.critic`](https://facelessuser.github.io/pymdown-extensions/extensions/critic/) extension out.

It appears to work fine, and there are multiple modes (show changes, accept, reject).
You can of course style it with custom CSS.

There is no editor integration of course, but as I said I have neither time nor interest to implement it.
![retext-critic](https://cloud.githubusercontent.com/assets/1381584/26524332/47f21e2a-4338-11e7-9697-81a069c8ac76.png)
