### ISSUE TITLE
[Bug] Clipboard Cut command and menu bar are disabled even though copy and paste are enabled

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#287]
ReText 7.0.0 on Windows 7

When I have text selected, Cut is disabled. This is minor because the shortcut key ctrl-x still works.

<img width="307" alt="retext-cut-disabled" src="https://cloud.githubusercontent.com/assets/492973/26651851/da705f38-4602-11e7-955d-17891cd9096f.png">

**Comment by mitya57** [comment]
Fixed in Git, thanks for noticing the bug!
