### ISSUE TITLE
Page break in markdown does not work

### ISSUE THREAD

**Issue by kannes** [retext-project/retext#290]
As per https://github.com/retext-project/retext/wiki/FAQ#can-i-use-page-breaks-in-markdown and https://github.com/retext-project/retext/wiki/Markdown-extensions I added

`<!-- Required extensions: attr_list -->`
as first line in my .md document but putting
`{: style="page-break-before: always" }`
anywhere does not do anything.

retext-git from Archlinux AUR, built the other day. "ReText 7.0.0 (using PyMarkups 2.0.0)".

**Comment by mitya57** [comment]
Hi,

The example from FAQ works correctly for me. However I should note that as ReText preview has no concept of “pages”, the change will only be in effect when you export to PDF, print or use the Print Preview.

Hope that makes it clear for you.

**Comment by kannes** [comment]
Thanks for testing it!

I should have said that I did PDF and ODT export without luck.

I made a file test.md with the following text inside:

```
<!-- Required extensions: attr_list -->
Some text here.

Another page starts here.
{: style="page-break-before: always" }
Some more text here.
```

When I export or print-preview, I get this:
https://anonimag.es/i/retext09bf4.png

**Comment by mitya57** [comment]
You need anpther line break after `}`, otherwise it is not parsed.

**Comment by kannes** [comment]
Argh, works like a charm now.

Could you add another line like that to the example? Then it would be complete and working.

**Comment by mitya57** [comment]
Example updated.
