### ISSUE TITLE
Text statistics placement conflicts with scroll position when searching

### ISSUE THREAD

**Issue by kannes** [retext-project/retext#291]
If document statistics are enabled they are displayed at the bottom of the text editor view. If one searches for text, retext will scroll the text editor view so that the matched text is in the last line. This is overlaid with the statistics, making work hard.

Maybe try to scroll on search so that the matched term is in the center of the text editor view? Or maybe make the statistics have some margin to the text editor view (I would prefer this so that it never overlays text).

**Comment by mitya57** [comment]
Should be fixed in the current master. @kannes @xgouchet please test.

**Comment by kannes** [comment]
It indeed now always keeps the cursor from search in the line above the statistics.

But I notice it overlays the very last line in a document so maybe I should add another issue? :D

I love this editor btw!

**Comment by mitya57** [comment]
Yes, please open a new issue. It may be more difficult to fix and I don’t have more time today.
