### ISSUE TITLE
tiny fonts in WebEngine on HiDPI

### ISSUE THREAD

**Issue by WellRedPandit** [retext-project/retext#293]
Hello. I am on Ubuntu 16.04 with a HiDPI monitor. When I switch to WebEngine(Chromium), the rendered fonts are tiny. Anything I can tweak to make them readable?
(warning: total newbie here, first day with retext, loving it! it's quite... _remarkable_ :-)

**Comment by pavel-ixxus** [comment]
Sorry, found it, _Change preview font_. Great editor! Thank you!

**Comment by mitya57** [comment]
Great that you solved it. Are both accounts (@WellRedPandit and @pavel-ixxus) yours?
