### ISSUE TITLE
7.0.1 crashes while 7.0.0 runs fine

### ISSUE THREAD

**Issue by jeremy886** [retext-project/retext#295]
(sphinx) ➜  ReText project retext
Using configuration file: /Users/apple/.config/ReText project/ReText.ini
2017-06-30 22:02:57.357 python[66920:12547378] *** Assertion failure in -[NSBitmapImageRep initWithCGImage:], /Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1504.83.101/AppKit.subproj/NSBitmapImageRep.m:1296
2017-06-30 22:02:57.359 python[66920:12547378] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cgImage != NULL'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffab3372cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc014248d objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffab33c042 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffacd84c80 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   AppKit                              0x00007fffa8ef55b6 -[NSBitmapImageRep initWithCGImage:] + 149
	5   QtGui                               0x0000000108a0eabd _Z21qt_mac_create_nsimageRK5QIconi + 525
	6   libqcocoa.dylib                     0x0000000111fcdfda qt_plugin_instance + 154170
	7   libqcocoa.dylib                     0x0000000111fcb197 qt_plugin_instance + 142327
	8   QtWidgets                           0x000000010bdb158d _ZN5QMenu11actionEventEP12QActionEvent + 1213
	9   QtWidgets                           0x000000010bc6def8 _ZN7QWidget5eventEP6QEvent + 1240
	10  QtWidgets                           0x000000010bdaf654 _ZN5QMenu5eventEP6QEvent + 1140
	11  QtWidgets                           0x000000010bc2d58d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
	12  QtWidgets                           0x000000010bc2fed2 _ZN12QApplication6notifyEP7QObjectP6QEvent + 5906
	13  QtWidgets.so                        0x000000010b7ff2b7 _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 231
	14  QtCore                              0x0000000108013544 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 164
	15  QtWidgets                           0x000000010bc61c61 _ZN7QWidget12insertActionEP7QActionS1_ + 353
	16  QtWidgets.so                        0x000000010b867d08 _ZL20meth_QMenu_addActionP7_objectS0_S0_ + 136
	17  python                              0x00000001073fe70d _PyCFunction_FastCallDict + 461
	18  python                              0x000000010748a0af call_function + 479
	19  python                              0x0000000107486ab2 _PyEval_EvalFrameDefault + 26098
	20  python                              0x000000010748af35 _PyEval_EvalCodeWithName + 3509
	21  python                              0x000000010748baeb _PyFunction_FastCallDict + 923
	22  python                              0x00000001073b4838 _PyObject_FastCallDict + 360
	23  python                              0x00000001073b4955 _PyObject_Call_Prepend + 149
	24  python                              0x00000001073b4585 PyObject_Call + 101
	25  python                              0x0000000107416c1e slot_tp_init + 158
	26  python                              0x0000000107412e59 type_call + 313
	27  python                              0x00000001073b4805 _PyObject_FastCallDict + 309
	28  python                              0x0000000107489fa9 call_function + 217
	29  python                              0x0000000107486ab2 _PyEval_EvalFrameDefault + 26098
	30  python                              0x000000010748af35 _PyEval_EvalCodeWithName + 3509
	31  python                              0x000000010748b736 fast_function + 742
	32  python                              0x000000010748a089 call_function + 441
	33  python                              0x0000000107486ab2 _PyEval_EvalFrameDefault + 26098
	34  python                              0x000000010748af35 _PyEval_EvalCodeWithName + 3509
	35  python                              0x0000000107480404 PyEval_EvalCode + 100
	36  python                              0x00000001074b5af1 PyRun_FileExFlags + 209
	37  python                              0x00000001074b51ec PyRun_SimpleFileExFlags + 668
	38  python                              0x00000001074ceab9 Py_Main + 3433
	39  python                              0x00000001073a913c main + 236
	40  libdyld.dylib                       0x00007fffc0a27235 start + 1
	41  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    66920 abort      retext

I'm using [pyenv](https://github.com/pyenv/pyenv). First, I got “error: option --single-version-externally-managed not recognized” when trying to install retext. 

I fixed it with "pip install wheel".

But then retext crashed. I tried the previous version 7.0.0 and it worked.

**Comment by mitya57** [comment]
Did you upgrade Qt at the same time as ReText?

You are most probably experiencing [QTBUG-58344](https://bugreports.qt.io/browse/QTBUG-58344) which happens only with Qt 5.8, and does not happen with 5.7 and 5.9.

**Comment by jeremy886** [comment]
Thanks. You are probably right.

>>> from PyQt5 import Qt, QtCore
>>> print("Qt version: " + str(QtCore.qVersion()))
Qt version: 5.8.0
>>> print("PyQt (Python module) version: " + str(Qt.PYQT_VERSION_STR))
PyQt (Python module) version: 5.8.2

It's weird that 7.0.0 works fine. Maybe it uses a different version of Qt?

**Comment by mitya57** [comment]
You can check which version it uses. Help &rarr; About Qt.

In any case `pip install "PyQt5<5.8"` should workaround the issue.

**Comment by jeremy886** [comment]
I checked About Qt. My retext 7.0.0 is using Qt 5.8.0 too (same virtualenv).

**Comment by mitya57** [comment]
Can you please install PyQt 5.9 and check if the crash still exists there?

**Comment by 2wayne** [comment]
Can't update ReText to 7.0.1. I get the same error as @jeremy886 "error: option --single-version-externally-managed not recognized" but `pip install wheel` didn't help.

**Comment by mitya57** [comment]
@2wayne I cannot reproduce this. Some searching shows that it is usually an issue with old libraries, so please try running `pip install -U pip setuptools` and then installing ReText again.

**Comment by 2wayne** [comment]
Already up to date.
chardet==3.0.4
docutils==0.14
Markdown==2.6.8
Markups==2.0.1
pyenchant==1.6.11
Pygments==2.2.0
PyQt5==5.9
ReText==7.0.0
sip==4.19.3

**Comment by mitya57** [comment]
These versions are irrelevant, I asked you about upgrading `pip` and `setuptools`…

**Comment by 2wayne** [comment]
I did and they are up to date ;)

**Comment by 2wayne** [comment]
@mitya57 

$ python -m pip install -U pip
Requirement already up-to-date: pip in d:\retext\lib\site-pac
kages

$ python -m pip install -U setuptools
Requirement already up-to-date: setuptools in d:\retext\lib\s
ite-packages

$ python -m pip install -U retext
Collecting retext
  Using cached ReText-7.0.1.tar.gz
Requirement already up-to-date: docutils in d:\retext\lib\sit
e-packages (from retext)
Collecting Markdown (from retext)
Requirement already up-to-date: Markups>=2.0 in d:\retext\lib
\site-packages (from retext)
Requirement already up-to-date: pyenchant in d:\retext\lib\si
te-packages (from retext)
Requirement already up-to-date: Pygments in d:\retext\lib\sit
e-packages (from retext)
Requirement already up-to-date: chardet>=2.3 in d:\retext\lib
\site-packages (from retext)
Requirement already up-to-date: PyQt5 in d:\retext\lib\site-p
ackages (from retext)
Requirement already up-to-date: sip<4.20,>=4.19.3 in d:\retex
t\lib\site-packages (from PyQt5->retext)
Building wheels for collected packages: retext
  Running setup.py bdist_wheel for retext ... error
  Complete output from command D:\ReText\python.exe -u -c "im
port setuptools, tokenize;__file__='C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-b
uild-5c3jqqr1\\retext\\setup.py';f=getattr(tokenize, 'open', open)(__file__);cod
e=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))
" bdist_wheel -d C:\Users\xxx\AppData\Local\Temp\tmpp6t5hl4vpip-wheel- --python
-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\ReText
  copying ReText\config.py -> build\lib\ReText
  copying ReText\converterprocess.py -> build\lib\ReText
  copying ReText\dialogs.py -> build\lib\ReText
  copying ReText\editor.py -> build\lib\ReText
  copying ReText\fakevimeditor.py -> build\lib\ReText
  copying ReText\highlighter.py -> build\lib\ReText
  copying ReText\icontheme.py -> build\lib\ReText
  copying ReText\mdx_posmap.py -> build\lib\ReText
  copying ReText\preview.py -> build\lib\ReText
  copying ReText\syncscroll.py -> build\lib\ReText
  copying ReText\tab.py -> build\lib\ReText
  copying ReText\tablemode.py -> build\lib\ReText
  copying ReText\webenginepreview.py -> build\lib\ReText
  copying ReText\webkitpreview.py -> build\lib\ReText
  copying ReText\window.py -> build\lib\ReText
  copying ReText\xsettings.py -> build\lib\ReText
  copying ReText\__init__.py -> build\lib\ReText
  running build_scripts
  creating build\scripts-3.5
  copying and adjusting retext.py -> build\scripts-3.5
  installing to build\bdist.win32\wheel
  running install
  running install_lib
  creating build\bdist.win32
  creating build\bdist.win32\wheel
  creating build\bdist.win32\wheel\ReText
  copying build\lib\ReText\config.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\converterprocess.py -> build\bdist.win32\wheel\.\ReTe
xt
  copying build\lib\ReText\dialogs.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\editor.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\fakevimeditor.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\highlighter.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\icontheme.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\mdx_posmap.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\preview.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\syncscroll.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\tab.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\tablemode.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\webenginepreview.py -> build\bdist.win32\wheel\.\ReTe
xt
  copying build\lib\ReText\webkitpreview.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\window.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\xsettings.py -> build\bdist.win32\wheel\.\ReText
  copying build\lib\ReText\__init__.py -> build\bdist.win32\wheel\.\ReText
  running install_scripts
  running egg_info
  creating ReText.egg-info
  writing dependency_links to ReText.egg-info\dependency_links.txt
  writing ReText.egg-info\PKG-INFO
  writing top-level names to ReText.egg-info\top_level.txt
  writing requirements to ReText.egg-info\requires.txt
  writing manifest file 'ReText.egg-info\SOURCES.txt'
  reading manifest file 'ReText.egg-info\SOURCES.txt'
  writing manifest file 'ReText.egg-info\SOURCES.txt'
  creating build\bdist.win32\wheel\ReText-7.0.1.data
  creating build\bdist.win32\wheel\ReText-7.0.1.data\scripts
  copying build\scripts-3.5\retext.py -> build\bdist.win32\wheel\ReText-7.0.1.da
ta\scripts
  running install_data
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\appdata
  copying data\me.mitya57.ReText.appdata.xml -> build\bdist.win32\wheel\ReText-7
.0.1.data\data\share\appdata
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\applications
  copying data\me.mitya57.ReText.desktop -> build\bdist.win32\wheel\ReText-7.0.1
.data\data\share\applications
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\icons
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\icons\hicolor
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\icons\hicolor\sc
alable
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\icons\hicolor\sc
alable\apps
  copying icons\retext.svg -> build\bdist.win32\wheel\ReText-7.0.1.data\data\sha
re\icons\hicolor\scalable\apps
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\retext
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\retext\icons
  creating build\bdist.win32\wheel\ReText-7.0.1.data\data\share\retext\locale
  running install_egg_info
  Copying ReText.egg-info to build\bdist.win32\wheel\.\ReText-7.0.1-py3.5.egg-in
fo
  renaming build\bdist.win32\wheel\ReText-7.0.1.data\scripts\retext.py -> build\
bdist.win32\wheel\ReText-7.0.1.data\scripts\retext
  error: [Errno 2] No such file or directory: 'ReText-7.0.1.data\\scripts\\retex
t.bat'

  ----------------------------------------
  Failed building wheel for retext
  Running setup.py clean for retext
Failed to build retext
Installing collected packages: Markdown, retext
  Found existing installation: Markdown 2.6.8
    Uninstalling Markdown-2.6.8:
      Successfully uninstalled Markdown-2.6.8
  Found existing installation: ReText 7.0.0
    Uninstalling ReText-7.0.0:
      Successfully uninstalled ReText-7.0.0
  Running setup.py install for retext ... error
    Complete output from command D:\ReText\python.exe -u -c "
import setuptools, tokenize;__file__='C:\\Users\\xxx\\AppData\\Local\\Temp\\pip
-build-5c3jqqr1\\retext\\setup.py';f=getattr(tokenize, 'open', open)(__file__);c
ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'
))" install --record C:\Users\xxx\AppData\Local\Temp\pip-gc0k3gll-record\instal
l-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
  Rolling back uninstall of ReText
Command "D:\ReText\python.exe -u -c "import setuptools, token
ize;__file__='C:\\Users\\xxx\\AppData\\Local\\Temp\\pip-build-5c3jqqr1\\retext\
\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r
\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\
Users\xxx\AppData\Local\Temp\pip-gc0k3gll-record\install-record.txt --single-ve
rsion-externally-managed --compile" failed with error code 1 in C:\Users\xxx\Ap
pData\Local\Temp\pip-build-5c3jqqr1\retext\

**Comment by mitya57** [comment]
Ok, I think I see what happens here. In commit b3e529a9 I added a new install command, and it does not work with pip’s hack to replace distutils with setuptools.

Will try to use setuptools now.
