### ISSUE TITLE
Code Highlighting

### ISSUE THREAD

**Issue by beli3ver** [retext-project/retext#296]
Hello,

I try to use code highlighting, so I installed pygments, but nothing happends.
All code will displayed without color.

**Comment by mitya57** [comment]
Hi @beli3ver,

If you are using Markdown, you should add [`codehilite`](http://pythonhosted.org/Markdown/extensions/code_hilite.html) to the list of Markdown extensions in the configuration dialog, after that the change will be in effect for new tabs.

**Comment by beli3ver** [comment]
Is there a way to change the style?

**Comment by mitya57** [comment]
You can use `pygmentsStyle` option in the [configuration file](https://github.com/retext-project/retext/blob/master/configuration.md). See the [Pygments documentation](http://pygments.org/docs/styles/#getting-a-list-of-available-styles) for details.

**Comment by beli3ver** [comment]
Thanks, that helped a lot.
