### ISSUE TITLE
mdx_linkify markdown extension: how to enable?

### ISSUE THREAD

**Issue by WellRedPandit** [retext-project/retext#300]
i've tried [Enabling extensions for a particular document](https://github.com/retext-project/retext/wiki/Markdown-extensions#enabling-extensions-for-a-particular-document). in steps:

1. installed [mdx_linkify](https://github.com/daGrevis/mdx_linkify) with pip
2. added `<!-- Required extensions: mdx_linkify.mdx_linkify -->` to the document (also tried `<!-- Required extensions: mdx_linkify.mdx_linkify.LinkifyExtension -->` and just `<!-- Required extensions: mdx_linkify -->`)
3. restarted retext, reopened the doc

links don't get converted (i'm using webengine)

maybe retext complains... is there a log file?

please help if you can. thank you!

**Comment by mitya57** [comment]
Did you install it for the same Python version as ReText uses? (I.e. on Debian/Ubuntu, you should use `pip3` instead of `pip`, the latter is for Python 2).

Try starting `retext` from the terminal — it should print some output there.

Also the correct extension name would be just `mdx_linkify`.

**Comment by WellRedPandit** [comment]
thank you for your help! works now when enabled either in the Markdown syntax extensions textbox or as a first comment line `<!-- Required extensions: mdx_linkify -->` in a file. closing this issue.
