### ISSUE TITLE
Include external document

### ISSUE THREAD

**Issue by xgouchet** [retext-project/retext#301]
One feature that would be nice would be the ability to include an external markup document. 

Much like we can include an image using 
```![Title](path/to/image.ext)```

We could have a 
```@[Title](path/to/document.md)```

The proposed syntax can be adapted, but this would splitting a document in multiple files and reorder sections easily.

**Comment by xgouchet** [comment]
The `[Title]` could be used if the referenced document is not found to insert the title as a `<a href="path/to/document.md">Title</a>`, maybe styling it in red to mark it as not found ?

**Comment by xgouchet** [comment]
I tried to play with the [`markdown_include.include`](https://github.com/cmacmackin/markdown-include) extension, which kind of works, but the path of the included file must be provided relative to the path of the working dir (in which retext is launched), and not the path of the parent document.

**Comment by mitya57** [comment]
With the latest version in master markdown_include should be working, please test.

**Comment by xgouchet** [comment]
Wow it works ! Amazing thanks a lot !

**Comment by xgouchet** [comment]
So to sum up, just include the following code and it works! 

```md
<!-- Required extensions: markdown_include.include -->

{!included_document.md!}
```
