### ISSUE TITLE
Header & Footer

### ISSUE THREAD

**Issue by beli3ver** [retext-project/retext#303]
Hello,

Is there a way to add a header & footer?

**Comment by beli3ver** [comment]
I mean something like in word

**Comment by mitya57** [comment]
Hi @beli3ver!

ReText documents are not split into pages, so the concept of pages exists only when printing. However, as we use the standard Qt dialogs for printing, there is no easy way to add such a setting. Pull requests are always welcome, but I do not have time or willingness to implement this myself.

Speaking about web pages (not printed pages), in reStructuredText you can use the [`.. header::` and `.. footer::` directives](http://docutils.sourceforge.net/docs/ref/rst/directives.html#document-header-footer). There is no such markup in Markdown though.
