### ISSUE TITLE
Add Table Wizard (See Tables Generator)

### ISSUE THREAD

**Issue by RoyiAvital** [retext-project/retext#308]
Hello,

Could you add ability to generate and edit tables using a wizard built like [Tables Generator](http://www.tablesgenerator.com)?

They have a clean and compact way to generate tables effectively.

Thank You.

**Comment by mitya57** [comment]
Sorry, I do not have any plans for implementing a special UI for tables.

Did you try the [table editing mode](https://github.com/retext-project/retext/wiki/Table-editing-mode)?

**Comment by RoyiAvital** [comment]
I see.
Maybe one day :-).

By the way why in apt-get we still have ReText 5.3?

**Comment by mitya57** [comment]
As I replied elsewhere:

New Ubuntu releases (such as 17.04) have newer ReText versions. See https://launchpad.net/ubuntu/+source/retext.

If you want to use the latest version on 16.04, you may try installing the package from 17.04 or installing ReText with `pip3 install --user ReText`.
