### ISSUE TITLE
Input problem for graph accents

### ISSUE THREAD

**Issue by cosmoscalibur** [retext-project/retext#309]
I have a problem with input accents in ReText. Example `á`.  
When copy/paste accents there is no problem, but accents using keyboard not work.  

Locale `es_CO.UTF-8` is enabled.

**Comment by mitya57** [comment]
Hi!

Do you mean that you have a Spanish keyboard layout, press the <kbd>á</kbd> button and nothing happens?

What is your distribution, desktop environment and Qt version (Help → About Qt)?

**Comment by mitya57** [comment]
(Edited the previous comment to make the question more correct.)

**Comment by cosmoscalibur** [comment]
My keyboard has latinoamerican spanish layaout and I try to input with combination of keys (accent + letter).  
My linux distribution is Lubuntu 16.04 (lxde desktop environment) and ReText is installed using pip.  
ReText version: 7.0.1  
PyMarkups version: 2.0.1  
Qt version: 5.9.1

**Comment by cosmoscalibur** [comment]
With Qt 5.9.3 there is no problem.
