### ISSUE TITLE
ReText Won't Render Something StackExchange Editor Renders Correctly

### ISSUE THREAD

**Issue by RoyiAvital** [retext-project/retext#310]
Hello,

Have a look at the following MarkDown code:

```
By definition as the dual norm $ \left\| a \right\|_{q} > \lambda \Rightarrow \exists u, \, \left\| u \right\|_{p} \leq 1 : {u}^{T} a > \lambda $.  
Choosing $ y = t u $ yields:

$$
\begin{align*}
-t {a}^{T} u + \lambda t \left\| u \right\|_{p} & = t \left( \lambda \left\| u \right\|_{p} - {a}^{T} u \right) & \text{} \\ 
& = t \left( \lambda - {a}^{T} u \right) \xrightarrow[]{t \to \infty} - \infty & \text{Since $ \left\| u \right\|_{p} \leq 1 $ and $ {a}^{T} u > \lambda $ }
\end{align*}
$$

### Summary
```

While StackExchange Editor renders it correctly (See https://math.stackexchange.com/a/2418078/33).  
The problem is in the line `& = t \left( \lambda - {a}^{T} u \right) \xrightarrow[]{t \to \infty} - \infty & \text{Since $ \left\| u \right\|_{p} \leq 1 $ and $ {a}^{T} u > \lambda $ }`. Specifically using `$ $` inside the `\text{}` command (Namely `\text{Since $ \left\| u \right\|_{p} \leq 1 $ and $ {a}^{T} u > \lambda $ }`).

I'm using ReText 5.3.1 (PyMarkups 1.0.1).

Thank You.

**Comment by RoyiAvital** [comment]
I verified this issue happens on ReText 7.0.0 (PyMarkups 2.0.1).

Thank You.

**Comment by mitya57** [comment]
Fixed, thank you for the report!

Note that you don’t need `$$` delimiters if you use `\begin{align*}` and `\end{align*}`. These are delimiters on their own.

**Comment by RoyiAvital** [comment]
This is perfect, Thank You!

By the way, any chance making the Portable version by @2wayne official?

**Comment by mitya57** [comment]
No, I do not want to support Windows officially because I don’t use it myself. I can add a link to the wiki though, but with the “unofficial” note.

**Comment by RoyiAvital** [comment]
I see your point.
A link in the Wiki will be great.

The more exposure the better.
More people need to know this great application.

**Comment by mitya57** [comment]
Added a link:
https://github.com/retext-project/retext/wiki/Installing-ReText#for-users-of-windows-and-macos
