### ISSUE TITLE
Retext 7.1.0 not parsing markdown if file starts with div tag

### ISSUE THREAD

**Issue by krunose** [retext-project/retext#314]
Hi,

ReText 7.1.0 is not parsing markdown if document starts with div tag (possible other block level tags). It parses HTML (embeds it into a file properly at export) but it wouldn't parse Markdown, so

<pre>
&lt;div id="test"&gt;

&num; This is example

This is example of ReText not parsing Markdown if file starts with div tag.

&lt;/div&gt;&lt;!-- /div#test --&gt;
</pre>

would result in 

<pre>
&num; This is example

This is example of ReText not parsing Markdown if file starts with div tag.

</pre>

**Comment by mitya57** [comment]
This is in accordance with the [Markdown syntax rules](https://daringfireball.net/projects/markdown/syntax#html), quoting:

> Note that Markdown formatting syntax is not processed within block-level HTML tags. E.g., you can’t use Markdown-style `*emphasis*` inside an HTML block.

And many other implementations are [doing the same](https://johnmacfarlane.net/babelmark2/?normalize=1&text=%3Cdiv+id%3D%22test%22%3E%0A%0A%23+This+is+example%0A%0AThis+is+example+of+ReText+not+parsing+Markdown+if+file+starts+with+div+tag.%0A%0A%3C%2Fdiv%3E%3C!--+%2Fdiv%23test+--%3E).
