### ISSUE TITLE
Mention required packages for building development snapshots

### ISSUE THREAD

**Issue by R1dO** [retext-project/retext#322]
First of all, thank you for this great piece of software. I find it really useful when writing restructuredtext documents.

When trying to create a development snapshot i stumbled upon the following build error:
```
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
Failed to build translations: Command '('lrelease', 'locale/retext_ca.ts')' returned non-zero exit status 1
``` 
It turned out i was missing some qt5 dev packages. [1]
In this case it was necessary to install the debian package ``qttools5-dev-tools``. 

It would be helpful if those dependencies are also mentioned in the readme file.
It might even be beneficial to mention the user home installation command ``./setup.py install --user``, so newby python programmers (like me) can use the package without putting it in a system area.

[1]  The command stated in the readme `lrelease locale/*.ts` does work, but that was probably because the debian package `qt4-linguist-tools` was present on this system.

**Comment by Lin-Buo-Ren** [comment]
Here's a pseudo package I use to install dependencies:

```debian-control
Source: retext
Homepage: https://github.com/retext-project/retext
Build-Depends: python3

Package: retext-runtime-dependencies
Version: sync-with-7.0.1+git-8d89e1e
Architecture: all
Depends: python3, 
	python3-pyqt5
# python3-markups needs newer version which is not provided by ubuntu, install version from PyPI instead
Recommends: python3-markdown, 
	python3-docutils, 
	python3-enchant
Description: Partially software required to run ReText

Package: retext-l10n-dependencies
Version: sync-with-7.0.1+git-8d89e1e
Architecture: all
Depends: qttools5-dev-tools, 
	pyqt5-dev-tools, 
Description: Software required to localize(translate) ReText
```

Save it to a file then build it with `equivs-build <filepath>`

**Comment by Lin-Buo-Ren** [comment]
I would suggest maintaining packaging information in upstream codebase, but it's not a popular idea.

**Comment by mitya57** [comment]
I have fixed the original bug now.

@Lin-Buo-Ren I don’t think it makes sense. First there is a proper Debian packaging, see http://sources.debian.net/src/retext/7.0.1-1/debian/.

Then, it is usually a bad idea to mix packages from distro and from PyPI, as that can lead to incompatibilities. My advice is: either use everything from the distro (including ReText), or set up a virtualenv and install all required Python modules from PyPI.
