### ISSUE TITLE
When a large font size is used, misspelled words aren't underlined

### ISSUE THREAD

**Issue by dechamps** [retext-project/retext#329]
I am using ReText 7.0.1 from the Debian package.

If I set the editor font size to 16, misspelled words are underlined:

![large](https://i.imgur.com/KPaHvHQ.png)

If I increase it to 18 or larger, they are not underlined anymore:

![small](https://i.imgur.com/vuzAY3n.png)

This is DejaVu Sans, but the issue seems to occur regardless of typeface.

**Comment by xgouchet** [comment]
This is a Qt bug : https://bugreports.qt.io/browse/QTBUG-50499
