### ISSUE TITLE
ReText refuses to run on Ubuntu 16.04

### ISSUE THREAD

**Issue by int3ll3ct** [retext-project/retext#332]
I tried to install using pip3 or apt, doesn't seem to make a difference.  When installed from apt, when I type `retext` at the command prompt, I get this:

```
Using configuration file: /home/rob/.config/ReText project/ReText.conf
Traceback (most recent call last):
  File "/usr/bin/retext", line 23, in <module>
    from ReText.window import ReTextWindow
  File "/usr/share/retext/ReText/window.py", line 22, in <module>
    from ReText.tab import ReTextTab, PreviewNormal, PreviewLive
  File "/usr/share/retext/ReText/tab.py", line 32, in <module>
    from PyQt5.QtWebKit import QWebSettings
ImportError: No module named 'PyQt5.QtWebKit'
```
It seems that QtWebkit is not supported by default as of Qt5.6 (see [https://riverbankcomputing.com/pipermail/pyqt/2017-March/038987.html](https://riverbankcomputing.com/pipermail/pyqt/2017-March/038987.html)), I am semeingly installing PyQt 5.9.1 as part of this install.

**Comment by mitya57** [comment]
It looks like you use a distro-packaged ReText with PyQt from PyPI. Please do not mix them, either upgrade ReText from PyPI, or use PyQt from the distro (Ubuntu does have `python3-pyqt5.qtwebkit`).
