### ISSUE TITLE
error in ReText setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

### ISSUE THREAD

**Issue by xhao79** [retext-project/retext#340]
Ubuntu 14.04 + Python 3.5
command: 
  python3 -m pip install ReText --user
or 
  sudo ./setup.py install
or
  sudo pip3 install retext

**Comment by mitya57** [comment]
ReText relies on [PEP 508](https://www.python.org/dev/peps/pep-0508/), which is implemented in setuptools 20.2 and newer. Ubuntu 14.04 has setuptools 3.3. Please upgrade your setuptools (e.g. `python3 -m pip install --upgrade setuptools --user`).

**Comment by xhao79** [comment]
Thanks mitya57!

Another error occurs with the command `sudo python3 -m pip install ReText --user` or `sudo pip3 install retext`:
error: option --single-version-externally-managed not recognized

**Comment by mitya57** [comment]
> `error: option --single-version-externally-managed not recognized`

That one is already fixed in master, will be in the next release.

**Comment by xhao79** [comment]
Ok, I will try the master version.

Thank you

**Comment by mitya57** [comment]
All the remaining problems should be fixed in ReText 7.0.3 release, so closing this.
