### ISSUE TITLE
Strike with double tilde is not rendered 

### ISSUE THREAD

**Issue by bagustris** [retext-project/retext#342]
I came with default retext in Ubuntu repository, it can't render double tilde to strikethrough text like ~~this one~~. This should appear as it is the default markdown feature. I already updated with the newest one from this repo.

**Comment by mitya57** [comment]
Strike is not a default Markdown feature. However there are extensions that implement it, for example [Tilde](https://facelessuser.github.io/pymdown-extensions/extensions/tilde/) by @facelessuser.

To use it, just run `pip3 install pymdown-extensions --user` and add `<!-- Required extensions: pymdownx.tilde -->` to the top of your document (or enable it globally using the configuration dialog). See [the wiki](https://github.com/retext-project/retext/wiki/Markdown-extensions) for details.

Note that this extension uses `<del>` tags which work only with the WebKit / WebEngine renderers. (If you want to use the default renderer (QTextBrowser), then the only option is using `<s></s>` tags manually).
