### ISSUE TITLE
Display regressions with QT 5.9.2

### ISSUE THREAD

**Issue by dhgutteridge** [retext-project/retext#345]
Fedora 26 and 27 recently moved to QT 5.9.2, after which ReText began exhibiting rendering issues  where particular lines in a file are not visible. I have reported this bug downstream at [https://bugzilla.redhat.com/show_bug.cgi?id=1514724](https://bugzilla.redhat.com/show_bug.cgi?id=1514724) which contains more details including screenshots.

A sample test case is to load the file found here:
[https://raw.githubusercontent.com/rpm-software-management/dnf/master/doc/command_ref.rst](https://raw.githubusercontent.com/rpm-software-management/dnf/master/doc/command_ref.rst)

Go to line 856 in the file, and then move the cursor downwards. Note that there are rows present in the file that are not displayed with QT 5.9.2, but there are no such issues with QT 5.7.1.

I imagine this may be a QT or pyqt5 issue rather than ReText, but I have no basis to provide any insight into this.

**Comment by mitya57** [comment]
Thanks for the bug report! I have not seen it myself, and so far I have no clue what could cause this.

Can you please enable line numbers in settings and attach a screenshot with them?

Also I notice that you are using Fusion style with Qt 5.7 and Adwaita-Qt with Qt 5.9. Does this bug happen if you use Fusion (you can try by passing `-style fusion` argument)?

**Comment by dhgutteridge** [comment]
If I enable line numbers, the problem goes away. It only manifests without that option. ("-style fusion" makes no difference. Without line numbers, the lines are missing, with line numbers, they're visible.)

**Comment by dhgutteridge** [comment]
Still an issue with QT 5.9.4. (BTW, if I load a file with line numbers enabled, then disable that option, there are no rendering issues after it's disabled. Closing and re-opening the same file with line numbering disabled of course still exhibits the rendering problem.)

**Comment by mitya57** [comment]
Does this still happen with Qt 5.10 or 5.11?

I cannot reproduce the bug yourself, and so far you are the only user who reported this…

**Comment by dhgutteridge** [comment]
I can reproduce this with Qt 5.10.1. The same sample file triggers the same missing lines.

**Comment by mitya57** [comment]
I noticed that in https://raw.githubusercontent.com/rpm-software-management/dnf/master/doc/command_ref.rst line 856 is this:

        Package specification like: name[-[epoch:]version[-release]][.arch]. See :ref:`Specifying Packages

while on your screenshots line 856 is different. What is marked line 856 on your screenshots is line 870 for me. Did you really attach the same file you were getting an issue with?

Also does the problem persist if you leave *only* the problematic lines in the file? Or it only happens in a large file?

Finally, can you please attach your configuration file (`~/.config/ReText project/ReText.conf`)? I want to know your font settings and other things that may help to localize the problem.

**Comment by mitya57** [comment]
Nevermind my first question. I just realized that this is a file in Git repository and the version from November 18th is https://raw.githubusercontent.com/rpm-software-management/dnf/b3cb12d289d096efbc82bcf1eb57c31ae41a40d6/doc/command_ref.rst.

**Comment by dhgutteridge** [comment]
I forgot to add, in doing this testing, I found the steps to reproduce are a little more specific than I realized before. In order to reproduce with the sample file, it _must_ be the first file opened in a new session. If any other files are opened before it, all lines are rendered correctly. Seems strange, but I confirmed this.

**Comment by dhgutteridge** [comment]
The sole content of my ReText.conf file is:

    [General]
    recentFileList=/home/disciple/Downloads/command_ref.rst, /home/disciple/test_frag.rst, /home/disciple/dnf-plugins-core/README.rst, /home/disciple/dnf-plugins-core/doc/versionlock.rst, /home/disciple/Brew/README.rst, /home/disciple/docbook2odf/README.md

**Comment by mitya57** [comment]
Oh, it looks like I am able to reproduce it!

**Comment by mitya57** [comment]
And there is a fix! Any chance you can test the latest version from Git master?

I want to fix one more bug (with syncscroll extension breaking code highlight), and after that there will be a new release.

**Comment by dhgutteridge** [comment]
I tested the latest version from Git master, and it fixes the problem for me, thanks!
