### ISSUE TITLE
Ctrl+F should focus the 'Search' field, not close the search bar

### ISSUE THREAD

**Issue by nodiscc** [retext-project/retext#346]
Hi, this is a small usability issue;

when the search bar is already opened (with `Ctrl+F` or `Edit > Search text`), and the focus is in the main editor area, pressing `Ctrl+F` again closes the search bar.

A workaround is to press `Ctrl+F` twice, but the usual behavior on `Ctrl+F` is to focus the search field if it's already opened. I often insert text by mistake with `Ctrl+Fsearchthisword` and have to delete it before pressing `Ctrl+F` again.

Thanks for this great editor

Retext 7.0.0 on Debian 9

**Comment by mitya57** [comment]
Fixed in master, please test.
