### ISSUE TITLE
Problem exporting links from source to pdf

### ISSUE THREAD

**Issue by Naufragus** [retext-project/retext#348]
When I type a link in the text source so: [bla bla](http://www.blblbla.org) appears as a clickable link in the preview tab. But, when I export the document to pdf thru the export function, the link in the final pdf I obtain is not clickable. It appears in blue but doesn't open in the browser I use. 

My platform is Ubuntu 14.04 and the retext version is ReText 5.2.1 (using PyMarkups 0.4).

However I have no problem if I export to pdf from this mkd filethru pandoc: pandoc textfile.mkd -o tetxfile.pdf

Any idea about?
Thanks in advance.

**Comment by Naufragus** [comment]
The kind of link I have in mind in the prior message is this, for example: \[bla, bla\](http://www.hdhdhdh.org) .

**Comment by mitya57** [comment]
Ubuntu 14.04 has an old Qt version, where [QTBUG-44563](https://bugreports.qt.io/browse/QTBUG-44563) was not fixed yet. It was fixed in Qt 5.6.

If you prefer to stick with old Qt version, try enabling / disabling WebKit renderer — one of this modes may work better if I recall correctly.

**Comment by Naufragus** [comment]
Why thru pandoc I have no issue, in the same system?

**Comment by mitya57** [comment]
That’s because pandoc does not use Qt for generating PDFs (I think it uses LaTeX).

You can create a custom [export extension](https://github.com/retext-project/retext/wiki/Export-Extensions) which will use pandoc for converting to PDF (or to any other format).

**Comment by Naufragus** [comment]
Thanks for the information and attention... but this option exceeds my knowledge. Perhaps I'll prefer yet postproces directly thru pandoc.
