### ISSUE TITLE
mac install python3 from brew  and using pip install Retext 

### ISSUE THREAD

**Issue by qinzheng** [retext-project/retext#349]
pip install ReText

Collecting ReText
  Using cached ReText-7.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Error: Python 3.x is required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/m9/48s6qy4n2cv67ccmpkd_xx_00000gn/T/pip-build-DYg5Gr/ReText/

**Comment by mitya57** [comment]
Use `pip3` or `python3 -m pip` instead of just `pip` then.

**Comment by qinzheng** [comment]
ok i will try it then   thank u

**Comment by qinzheng** [comment]
@mitya57  ok i will try it later thank u
