### ISSUE TITLE
Cannot input Chinese characters with iBus

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#35]
## ENV
- OS: Ubuntu 10.04 
- iBus: 1.3.8 + SunPinYin
- ReText: 3.0.3

Reported by: hutushen222

Original Ticket: [retext/tickets/35](https://sourceforge.net/p/retext/tickets/35)

**Comment by yjwfn** [comment]
I have encountered this problem, but I'am using the Fcitx.

**Comment by farseerfc** [comment]
@yjwfn fcitx should be working as long as your Qt5 have enabled fcitx support.
<img width="500" alt="screenshot_20160119_012627" src="https://cloud.githubusercontent.com/assets/861563/12396674/1d4ccd90-be4c-11e5-8cda-baedbe27c207.png">

Please provide your OS/Qt5/fcitx version, and `fcitx-diagnose` output to help diagnose the problem.

**Comment by yjwfn** [comment]
@farseerfc 
It can be working normally. Thank you for help.

**Comment by L-ios** [comment]
看看是不是安装的pyqt5的问题，比较一下/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforminputcontexts和/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts,我是使用的fctix

**Comment by mitya57** [comment]
@L-ios Please use English here.

> `/usr/local/lib/python3.5/dist-packages/PyQt5/Qt/plugins/platforminputcontexts`
This is from the Qt which is bundled with PyQt5 wheel. I do not recommend using it.

> `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts`
This is from the Qt distro packages as shipped by Debian/Ubuntu. They are generally more complete and thus better to use, compared to the bundled Qt.

> fctix
In Debian/Ubuntu, there is `fcitx-frontend-qt5` package, compiled against distro Qt. If you install it, then you should have the `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so` file.

If you use Qt, PyQt and fcitx from your Linux distribution repositories, then fcitx should work in ReText.
