### ISSUE TITLE
Reading-oriented layout and workflow

### ISSUE THREAD

**Issue by david-libremone** [retext-project/retext#351]
**User story:** I am a documentation writer reviewing multiple Markdown files. I am primarily interested in reading their content, and only occasionally making corrections.

**Suggested solution (two parts):**

1. Alternate layout for live preview. Option to put the preview pane on the left, and writing pane on the right.

2. Additional option. "Use preview by default." Opens files in preview mode (not writing mode) first. If the user hits Ctrl+E, switch to writing mode. If the user hits Ctrl+L, switch to live preview mode.

**Comment by mitya57** [comment]
Your second suggestion was implemented in #435. You can enable preview mode by default in Preferences dialog.
