### ISSUE TITLE
Add option to use only HTML as markup language

### ISSUE THREAD

**Issue by missic** [retext-project/retext#352]
I'm currently trying to use Retext as a HTML editor with live preview (with WebKit rendering) and to do this one doesn't need to convert any other markup language.
So it would be nice if Retext permitted to select "None" as markup language in use.

**Comment by dessalines** [comment]
If you're doing html, just use [jsfiddle](https://jsfiddle.net/) or, your browsers dev tools for live preview while editing. Retext is billed as a markdown editor.

**Comment by mitya57** [comment]
Yes, there is no plan to support plain HTML editing. It was part of early ReText versions, but was dropped in e8d1a3276d464ef05a49345b7b31b988b8da6484. If you really want HTML editing support, you may create a custom dummy HTML markup using instructions in [PyMarkups documentation](http://pythonhosted.org/Markups/custom_markups.html).
