### ISSUE TITLE
"Pip Install Retext" no longer correct

### ISSUE THREAD

**Issue by cefn** [retext-project/retext#353]
The frontpage at https://github.com/retext-project/retext claims...

> The latest stable version of ReText can be downloaded from PyPI. You can also use `pip install ReText` command to install it from there.

However, when I attempted to follow these instructions I received this output...

> Error: Python 3.x is required.

The front page should be updated to list the command as...

pip3 install ReText

**Comment by mitya57** [comment]
Fair enough, fixed.
