### ISSUE TITLE
How to launch Retext?

### ISSUE THREAD

**Issue by clabnet** [retext-project/retext#356]
I'm new to linux envs, I will try to install this program on Raspberry. 
After installation, how to start ?

**Comment by mitya57** [comment]
- If you install ReText via `pip3 install --user ReText`, it will be available as `~/.local/bin/retext`.
- If you install ReText via `sudo pip3 install ReText`, it will be available as `/usr/local/bin/retext`. However do **not** do this, as it may cause conflicts with system Python modules. Better clean your `/usr/local/bin/` directory if you have already done this.
- Finally, if you install it as `sudo apt-get install retext`, it will be available as `/usr/bin/retext`. Based on your distro, it may be a bit outdated though.

In all cases, an entry should be added to your desktop’s menu.

**Comment by epicTreeStick** [comment]
even if you install it with `pip3 install ReText` without using `sudo`, it will install to `~/.local/bin/retext`. I am not sure if the `--user` option makes a difference.

**Comment by mitya57** [comment]
That is the correct location. You can launch ReText from there, or you can use your desktop’s menu: ReText installs a `.desktop` file under `~/.local/share/applications` and your menu should pick it up.

If you really want to install system-wide to `/usr/local/`, you can use `sudo pip install --system ReText` (that is not recommended as it can break your system packages).
