### ISSUE TITLE
Unicode character breaks syntax highlighting

### ISSUE THREAD

**Issue by kannes** [retext-project/retext#357]
A headline is rendered in bold in the editor pane.

Adding 🌈 (unicode rainbow) at the start of the headline makes the last character non-bold (the unicode character is rendered as empty rectangle for me). Adding another 🌈 removes the boldness from the second to last, and so on.

Removing a character from the right of the headline makes the unicode character be rendered as two questionmark blocks. Removing another removes them. Removing another makes the next unicode character into the questionmarks, and so on.

Test with 🌈 and `#<inserthere>1234567890`

Tested with a git checkout from right now. ReText 7.1.0 (Git) (using PyMarkups 2.0.1) on Archlinux.

**Comment by mitya57** [comment]
Thanks for reporting this! Can you please test my today’s commit in master?

**Comment by kannes** [comment]
Fixed the bug and it even renders something rainbowy (black and white but yay!) for me now. Thanks for the swift fix!

**Comment by mitya57** [comment]
It looks like not only syntax highlighting was broken, but also right-click menus — I just filed #368 for that.
