### ISSUE TITLE
"document has been deleted" notification

### ISSUE THREAD

**Issue by jeyca** [retext-project/retext#358]
When you are working on a document, and the file has been deleted from externa, a popup will warn you about that you should save you work.

It would be better, not to have a popup here but something like red notification banner in top of the editing field.

**Comment by matkoniecz** [comment]
Why it would be better? I prefer popup, it is harder to miss.

**Comment by mitya57** [comment]
I think the current design is fine, and I don't have time to implement other options, so I am closing this bug. Pull requests will be welcome.
