### ISSUE TITLE
ReText on Windows stops responding when enabling 'Use WebEngine Chromium renderer'

### ISSUE THREAD

**Issue by taa1** [retext-project/retext#359]
Windows 10 Home, Version 1709, OS Build 16299.371

ReText 7.1

I know that ReText on Windows it not officially supported.

I've tried a regular ReText install using pip (Python v3.6.2 32bit) and also the [portable app](https://portableapps.com/node/56132) mentioned in the [wiki](https://github.com/retext-project/retext/wiki/Installing-ReText). 

Both exhibit the same issue: On launch with a file name I get a blank screen except for the upper left corner where it shows the ReText icon, open file name and the word ReText.

The local pip install was working fine about six months ago. I haven't had a reason to use ReText again until now.

Uninstall and re-install doesn't fix it.

How do I go about troubleshooting this?

**Comment by mitya57** [comment]
Does it happen only when launching with a file name? Can you please attach a screenshot?

Also maybe you can somehow check the console output? I think this can be done by running `python.exe` instead of `pythonw.exe`.

**Comment by mitya57** [comment]
Closing because I have not received a reply from you. Also the newer versions of Qt have many bugfixes related to Qt WebEngine. If it still happens with the latest version of Qt, please let me know and I will reopen the bug.
