### ISSUE TITLE
question: how to use Github markdown?

### ISSUE THREAD

**Issue by monperrus** [retext-project/retext#369]
Is there a way to activate Github-flavoured markdown in retext?

**Comment by mitya57** [comment]
You can install the `pymdown-extensions` module that provides some extensions which implement different parts of GitHub flavoured Markdown.

First, install it from PyPI:

    pip3 install --user pymdown-extensions

Then, add this line on top of your Markdown document:
```html
<!-- Required extensions: pymdownx.betterem, pymdownx.tilde, pymdownx.emoji, pymdownx.tasklist, pymdownx.superfences -->
```

See these links for detail:
- https://facelessuser.github.io/pymdown-extensions/faq/#github-ish-configurations
- https://github.com/retext-project/retext/wiki/Markdown-extensions

If you want to specify some options to the extensions, you can list them in brackets, e.g. `pymdownx.tilde(subscript=false)`.

**Comment by monperrus** [comment]
Thanks a lot, added them directly to `$HOME/.config/markdown-extensions.txt`

Is there an extension to recognize and not display Jekyll metadata in the live preview?

```
---
title: Spoon Patterns
---
```

**Comment by mitya57** [comment]
Yes, there is an [extension](https://python-markdown.github.io/extensions/meta_data/) for that too.

Just add `meta` to your extensions list.

**Comment by monperrus** [comment]
works perfectly, thanks!
