### ISSUE TITLE
Missing icons under Windows

### ISSUE THREAD

**Issue by holzkohlengrill** [retext-project/retext#371]
Since version 7.0.1 I cannot see any icons except I edit `ReText/__init__.py`. from `_iconPath = None` to `_iconPath = "./icons"`

Python 3.6.5
Qt Version 5.10.1

Seems to be changed in [this commit](https://github.com/retext-project/retext/commit/ffc8128da57af7ed574a1053a27d814f24450ea9#diff-93e4a0832908b2e14389ebaa6be3975c).

**Comment by mitya57** [comment]
This is strange. Can you please check what is the current value of `_iconPath` (after initialization), by adding `print(_iconPath)` before this line?

https://github.com/retext-project/retext/blob/882c4039e0d275732b9699d7b2747632fc4ffbb4/ReText/__init__.py#L63

**Comment by holzkohlengrill** [comment]
For `dir` I get the following values:

```text
dir: icons
dir: C:/Users/holzkohlengrill/AppData/Local\retext
dir: C:/ProgramData\retext
dir: C:/Program Files (x86)/Python36-32\retext
dir: C:/Program Files (x86)/Python36-32/data\retext
dir: C:\Program Files (x86)\Python36-32\share\retext
dir: C:\Program Files (x86)\share\retext
```

`print("_iconPath:", _iconPath)` before: `return join(_iconPath, iconName + '.png')` gives:

```text
Using configuration file: C:/Users/holzkohlengrill/AppData/Roaming/ReText project/ReText.ini
_iconPath: C:\Program Files (x86)\share\retext\icons
...
```

Obviously this directory does not exist.

```
if exists(_iconPath):
    break
```
Is never entered. As a result the last value of `dir`/`datadirs` is used

**Comment by mitya57** [comment]
So where your icons really are, and where is `retext.py` on your system? Are you using a Git checkout, or did you install ReText using `setup.py` or `pip`?

I cannot use just `./icons`, I need to use some absolute path because ReText can be run from any working directory.

- If this is a Git checkout, then a path relative to `__file__` should work.
- If ReText is installed then `setup.py` should install icons to a directory which should get into datadirs eventually.

**Comment by mitya57** [comment]
Closing because I have not received a reply from you. I will reopen it if you reply to my last questions.

**Comment by holzkohlengrill** [comment]
I downloaded it from github (no `setup.py`).

If you want to assure that this works from any working directory there should be always a possible relative path to your executable that works.

Output for `__file__` and `locals()` invoked in `def initializeDataDirs():`: 
`__file__`: `C:\Users\holzkohlengrill\AppData\Local\Programs\ReText\ReText\__init__.py`
`locals()`: `{}`

**Comment by holzkohlengrill** [comment]
any news?

**Comment by mitya57** [comment]
If you cloned ReText from Git, maybe you just don’t have the icons? Can you check the contents of `icons` directory in the Git root?

You can either download and unpack the [icons ZIP](https://github.com/retext-project/retext/archive/icons.zip) manually, or use `setup.py sdist` command which will do that for you.

**Comment by mitya57** [comment]
Can you try to unpack the icons to `C:\Users\holzkohlengrill\AppData\Local\Programs\ReText\*.png`?

**Comment by mitya57** [comment]
Upd: I meant `C:\Users\holzkohlengrill\AppData\Local\Programs\ReText\icons\*.png`.

**Comment by holzkohlengrill** [comment]
Sorry for the late answer. The icons are located on exactly this path.

```
$ tree -L 2
.
├── appveyor.yml
├── changelog.md
├── configuration.md
├── data
│   ├── me.mitya57.ReText.appdata.xml
│   ├── me.mitya57.ReText.desktop
│   └── retext-kde5.png
├── icons
│   ├── application-exit.png
│   ├── application-pdf.png
│   ├── COPYING
│   ├── document-new.png
│   ├── document-open.png
│   ├── document-open-recent.png
│   ├── document-preview.png
│   ├── document-print.png
│   ├── document-print-preview.png
│   ├── document-save.png
│   ├── document-save-as.png
│   ├── edit-copy.png
│   ├── edit-cut.png
│   ├── edit-find.png
│   ├── edit-paste.png
│   ├── edit-redo.png
│   ├── edit-undo.png
│   ├── go-next.png
│   ├── go-previous.png
│   ├── help-about.png
│   ├── internet-web-browser.png
│   ├── README.md
│   ├── retext.ico
│   ├── retext.png
│   ├── retext.svg
│   ├── system-file-manager.png
│   ├── text-html.png
│   ├── view-fullscreen.png
│   └── x-office-document.png
├── LICENSE_GPL
├── locale
│   ├── retext_ca.ts
│   ├── retext_cs.ts
│   ├── retext_cy.ts
│   ├── retext_da.ts
│   ├── retext_de.ts
│   ├── retext_es.ts
│   ├── retext_es_CO.ts
│   ├── retext_et.ts
│   ├── retext_eu.ts
│   ├── retext_fr.ts
│   ├── retext_hr.ts
│   ├── retext_hu.ts
│   ├── retext_it.ts
│   ├── retext_ja.ts
│   ├── retext_nl.ts
│   ├── retext_pl.ts
│   ├── retext_pt.ts
│   ├── retext_pt_BR.ts
│   ├── retext_ru.ts
│   ├── retext_sk.ts
│   ├── retext_sr.ts
│   ├── retext_sr@latin.ts
│   ├── retext_uk.ts
│   ├── retext_zh_CN.ts
│   └── retext_zh_TW.ts
├── MANIFEST.in
├── README.md
├── ReText
│   ├── __init__.py
│   ├── __pycache__
│   ├── config.py
│   ├── converterprocess.py
│   ├── dialogs.py
│   ├── editor.py
│   ├── fakevimeditor.py
│   ├── highlighter.py
│   ├── icontheme.py
│   ├── mdx_posmap.py
│   ├── preview.py
│   ├── syncscroll.py
│   ├── tab.py
│   ├── tablemode.py
│   ├── webenginepreview.py
│   ├── webkitpreview.py
│   ├── window.py
│   └── xsettings.py
├── ReText.bat
├── retext.py
├── setup.py
├── stderr.log
└── tests
    ├── __init__.py
    ├── test_editor.py
    ├── test_posmap.py
    ├── test_settings.py
    ├── test_tablemode.py
    ├── test_window.py
    └── testdata
```
Meanwhile I am on commit 4eb0194993e4d93015bfd5b430d91bc0814aba3a
