### ISSUE TITLE
Release ReText 7.2.0 ?

### ISSUE THREAD

**Issue by nodiscc** [retext-project/retext#373]
Hi,

I think it would be nice to tag and release a new version of retext.

There were many improvements since the last release, 

I think it would probably allow the maintainer of the debian package to prepare a new one (currently https://packages.debian.org/sid/retext 7.0.1-1)

I made release notes for you based on the previous ones and https://github.com/retext-project/retext/compare/7.0.0...master

----------------------

7.2.0 is the new version of ReText.

It contains new features and improvements, the most notable of which are:

 * ` Ctrl+Mouse wheel` can be used to increase / decrease the editor font size (#328)
 * Pressing `Return` while in an ordered list will auto-continue the list on next line
 * Pressing Alt+Arrow Up / Alt+Arrow Down will move the current line up/down.
 * The current tab can be closed with `Ctrl+W`
 * Ctrl+F now focuses the search field when search bar is already opened
 * Add an entry in the context menu on a mispelled word to add the word to the user dictionary.
 * Add statistics about the document in the lower left corner
 * Add an option to display relative line numbers (#265)
 * New tabbed preferences dialog
 * Images will never appear wider than the document
 * Translation updates and new languages
 * Several Windows and Linux bugfixes
 * Various optimizations and python package improvements

**Comment by mitya57** [comment]
I am going to do a bugfix only release soon (just need to fix one more important bug). The Debian maintainer is also me, so I will upload the release once it’s out.

The release with new features will be later, I hope it will be one of the summer months (in North hemisphere :)).

**Comment by mitya57** [comment]
I released 7.0.2 yesterday and a follow up release 7.0.3 today. Both are bugfix-only releases, but most commits in master were bug fixes anyway.
