### ISSUE TITLE
Support for Interpreted Text Roles

### ISSUE THREAD

**Issue by EricG-Personal** [retext-project/retext#374]
See http://docutils.sourceforge.net/docs/ref/rst/roles.html

For a reference implementation see http://rst.ninjs.org

An example would be:

    **strong**

should produce the same visual display as:

    :strong:`strong`

There are several more (and more useful) interpreted text roles defined for reStructuredText.

**Comment by mitya57** [comment]
Works fine for me. Did you set reStructuredText (and not Markdown) in “Edit → Default markup” menu?

![Screenshot](https://user-images.githubusercontent.com/1381584/41176304-8f94f62c-6b68-11e8-9c4f-57554c6cf8f4.png)
