### ISSUE TITLE
AttributeError: type object 'QKeySequence' has no attribute 'Cancel'

### ISSUE THREAD

**Issue by thedesignatedgeek** [retext-project/retext#376]
Can not run retext due to the following issue:
AttributeError: type object 'QKeySequence' has no attribute 'Cancel'
Verified that pyqt5 is install.

**Comment by mitya57** [comment]
What are your versions of Qt and PyQt? You need at least version 5.6 of both of them (see qt/qtbase@126c2cb8fbb50848).

**Comment by thedesignatedgeek** [comment]
Thanks. I will check.

On Jun 26, 2018 11:50 AM, "Dmitry Shachnev" <notifications@github.com>
wrote:

What are your versions of Qt and PyQt? You need at least version 5.6 of
both of them (see qt/qtbase@126c2cb
<https://github.com/qt/qtbase/commit/126c2cb8fbb50848>).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/retext-project/retext/issues/376#issuecomment-400386220>,
or mute the thread
