### ISSUE TITLE
Feature request: auto-open last file

### ISSUE THREAD

**Issue by EOSIT** [retext-project/retext#377]
A very handy tool (and perhaps not too hard to implement) is to add a check-box option in the preferences to "Automatically reopen the last file".  So if the app was closed, then reopened, it would restore the last file you were working on.  (I know you can do this from the recent files list, but this is just a bit faster!)

**Comment by mitya57** [comment]
There is already such an option since version 7.0.
Edit → Preferences → Automatically open last documents on startup.
