### ISSUE TITLE
Resizing window causes display to lose visibility of selected line/cursor position

### ISSUE THREAD

**Issue by dhgutteridge** [retext-project/retext#378]
When editing a document and then resizing its window, the display sometimes loses visibility of the selected line/cursor position. This is quickly remedied, and so hardly a serious bug, but it can be disorienting when first encountered, so I thought I'd mention it. (I just happen to encounter it a lot with my particular work habits.)

Steps to reproduce:
(1) Open a large document (e.g. [https://raw.githubusercontent.com/rpm-software-management/dnf/b3cb12d289d096efbc82bcf1eb57c31ae41a40d6/doc/command_ref.rst](https://raw.githubusercontent.com/rpm-software-management/dnf/b3cb12d289d096efbc82bcf1eb57c31ae41a40d6/doc/command_ref.rst)) with the ReText window un-maximized.
(2) Navigate to a specific line in the document, e.g. 800 in the sample file above. Choose a line towards the top of the displayed lines in the window, e.g. five lines from the top of the displayed region.
(3) Maximize ReText's window.
(4) Note the line the cursor was placed on is no longer visible in the window.
(5) Move the cursor with the keyboard. ReText adjusts the window view so the cursor can now be seen again on the appropriate line.

(I can duplicate this with different screen resolutions, and in more than one desktop environment. This could be a QT issue, rather than being ReText-specific, I'm not sure. I don't use any other pure QT applications to compare against.)

**Comment by mitya57** [comment]
This one was easy to fix, thanks for reporting :)
