### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [retext-project/retext#379]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by mitya57** [comment]
Hi, thanks for your kind offer!

Indeed the current logo was designed very quickly and is not a piece of art.
If you can draw something and release it under a free license, then please do that and I will consider it.

**Comment by Batarian711** [comment]
Sorry. I'm a little late. I designed an icon suitable for  name. What do you think? Is there anything you want to add?

![retext](https://user-images.githubusercontent.com/41051393/42739288-5f189f4c-889d-11e8-811e-2cd0a89d7b1b.jpg)

**Comment by mitya57** [comment]
To be honest, I think your new logo is too generic (can be visually associated with any text editor). The word “ReText” is too generic itself, so the logo should be something that clearly distinguishes us from the other projects.

That said, I am not ready to make the change you proposed.

**Comment by Batarian711** [comment]
She'il be ready for a few days.
