### ISSUE TITLE
Search does not work in Preview mode (both WebKit and non-WebKit renderers)

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#381]
Steps to reproduce:
1. Open Markdown document in ReText
2. Switch it to the Preview mode
3. Press <Ctrl+F> to search for something, enter search term
4. Press <Enter> or *Previous* / *Next*

Expected results:
* ReText allows to search text in Preview mode

Actual results:
* ReText does not allow to search text in Preview mode (in both WebKit and non-WebKit renderers)

Affected Ubuntu versions:
14.04 LTS, 16.04 LTS, 18.04 LTS.

Downstream bug-report:
https://bugs.launchpad.net/bugs/1786611

**Comment by mitya57** [comment]
I will try to implement this when I have time.

**Comment by mitya57** [comment]
Finally I have found time to implement this, and it's now done in master branch.

If you are still interested in this, maybe you can test it?

**Comment by N0rbert** [comment]
Great! It works as expected! Thank you!
