### ISSUE TITLE
Autosave disables save button, why?

### ISSUE THREAD

**Issue by MonteCarlos** [retext-project/retext#384]
When autosave is enabled, save button is disabled. Assuming autosave saves file on a regular time period, forcing save in between that period is not possible with autosave. As a workaround, autosave can be disabled. Forcing instantaneous saving matters after some important change has been made to the document, though.

**Comment by mitya57** [comment]
Can you please be more verbose what your use case is?

Auto-save automatically updates the file on disk every minute. Also it updates the file when you close it.

Preview, export and other functions do not require the file to be saved, they will work just fine between the saves.

Maybe you need to open the file in another program after you made the change? That would be a valid use case, but I still want to know details.

If you worry about losing your data in a crash, then even if ReText crashes (that should not happen :)), the worst thing that can happen is losing the results of a minute of work. This is not that much to worry about, I think.

**Comment by matkoniecz** [comment]
> Auto-save automatically updates the file on disk every minute.

I sometimes want to save immediately after changes. Maybe I just copied in something important and noticed that laptop battery is running out and may switch off at any second.

Or maybe I am just anxious and I want to save exactly at this moment :)

**Comment by elguitar** [comment]
First, for me this is mostly about user experience. Right now there is no indicator on whether the file is saved or not when autosave is on. If the save button would work normally, it would work as the indicator.

**Comment by adessein** [comment]
I have just created a new issue that is related to this one, but I do not think it is a duplicate.
In #461 I report that this statement from mitya57 is actually wrong :

> If you worry about losing your data in a crash, then even if ReText crashes (that should not happen :)), the worst thing that can happen is losing the results of a minute of work. This is not that much to worry about, I think.

I have just lost hours of work + work done some weeks ago. Look at my issue, but what I have experienced is that the autosave feature has saved an empty file over a non-empty file....

**Comment by mitya57** [comment]
This is now fixed in master branch. Now you will see whether the latest changes are saved or not, by looking at the window/tab titles and at the Save button, just like when auto-save is disabled.

Any feedback is welcome and sorry for the delay.
