### ISSUE TITLE
ReText ignores LaTeX equations declared by inline $...$ blocks

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#387]
Steps to reproduce:

* prepare text Markdown document with some LaTeX equations inside the inline `$ ... $` block:

```
# Doing Math

Simple inline math is rendered as is $a^2 + b^2 = 
c^2$.

But LaTeX equation is rendered correctly:

\begin{equation}
J(\theta) = \frac 1 2 \sum_{i=1}^m (h_\theta(x^{(i)})-y^{(i)})^2
\end{equation}
```

Expected result:
* ReText renders math inside inline `$ ... $` blocks. This behavior is expected to get compatibility with RMarkdown and other Markdown dialects. For example VNote renders this correctly, but [fails with   `\begin{equation} ... \end{equation}` math](https://github.com/tamlok/vnote/issues/401).

    > ![vnote-eq](https://user-images.githubusercontent.com/309456/45601146-f0faa000-ba10-11e8-9575-98e9d312c7b5.png)

Actual result:
* ReText does not render math inside inline `$...$` block and shows it as is.

    > ![retext-eq2](https://user-images.githubusercontent.com/309456/45601272-fd7ff800-ba12-11e8-8daf-3891f2e35e64.png)

Note: I'm running ReText 7.0.3 (installed with `sudo pip3 install ReText`) on Ubuntu 16.04 LTS amd64.

**Comment by mitya57** [comment]
Hi!

You need to add `mathjax` to your extensions list as documented in the [wiki](https://github.com/retext-project/retext/wiki/Math).

**Comment by fanxinping** [comment]
Hi!  
You need to add `$$` like this
![image](https://user-images.githubusercontent.com/23021820/45604818-a86fd080-ba6a-11e8-9e67-ac9f0b4e6ae9.png)

**Comment by N0rbert** [comment]
Added `mathjax` to extensions. ReText part is fixed. Thank you,  mitya57!
Now I can use it as Rmd and bookdown editor.
