### ISSUE TITLE
Right-click deselects selected text

### ISSUE THREAD

**Issue by holzkohlengrill** [retext-project/retext#390]
How to reproduce:

1. Select text in document
2. Right click to get into context menu
3. As a result the selected text gets unselected

==============

ReText: 7.1.0 (Git)
PyMarkups: 3.0.0
Qt: 5.10.1
Python: 3.7.0b5

**Comment by mitya57** [comment]
Thanks for reporting this bug, it is now fixed in master. Please test if you can.

It was a regression from #337, so it is not present in a stable release.

**Comment by holzkohlengrill** [comment]
Testing was successful from my side.
