### ISSUE TITLE
Help needed: GFM and apt packaged ReText

### ISSUE THREAD

**Issue by fprawits** [retext-project/retext#391]
Probably not a real issue and just my own inability of getting this set up properly:
The wiki page of ReText advises to install pymdown-extensions in order to get GitHub-flavoured markdown working.

When running `pip3 install --user pymdown-extensions` said extensions are installed together with the latest `Markdown` (3.0 in this case) into my `~/.local/lib/...`. Somehow the user-site installation of `Markdown` breaks the live-previewer and I am left with an error message asking whether this module is installed. Uninstalling via `pip3 uninstall Markdown` makes the previewer work again, however the (now) lonely `pymdown-extensions` sitting in my `~/.local/lib` doesn't do me any good and I am still not getting GFM when including
`<!-- Required extensions: pymdownx.betterem, pymdownx.tilde, pymdownx.emoji, pymdownx.tasklist, pymdownx.superfences -->`
in my document, so I might as well uninstall it.

It is worth noting that I originally installed ReText, together with the needed `python3-docutils` and `python3-markdown` through `apt install ...` (I am on a fresh install of **Ubuntu 18.04** here), so I suspect some *path* issues. Is the only way to get GFM by installing ReText through pip as well, or is there some option to use it with the version from the Ubuntu-repositories (I would like to profit from distribution managed updates down the line)? To my knowledge there is no packaged pymdown-extensions in the repositories (correct me if I am wrong), which is why I tried the one from PyPI in the first place.

I hope I stated my issue well enough to be understandable, I am happy to provide any further information if needed and would be grateful for directions. Oh, and thanks for creating this wonderful piece of software!

**Comment by mitya57** [comment]
> Somehow the user-site installation of `Markdown` breaks the live-previewer and I am left with an error message asking whether this module is installed.

Most likely this is because the versions of PyMarkups and ReText (in Ubuntu 18.04 repositories) do not support Python-Markdown 3.0 which was released recently on PyPI. This can be fixed by pinning Markdown to the previous version: `pip3 install Markdown==2.6.11`.

> Uninstalling via `pip3 uninstall Markdown` makes the previewer work again, however the (now) lonely `pymdown-extensions` sitting in my `~/.local/lib` doesn't do me any good

This should work (I just tested such a configuration and it works for me).

Can you please tell me two things:
- Run `python3` shell and check if `import pymdownx` there works (does not print any errors).
- What exact syntax of GFM you are trying to use? Maybe it's just unsupported by pymdownx.

**Comment by fprawits** [comment]
First of all thanks for the quick reply and the hint concerning the version conflict with PyMarkups vs Python-Markdown.

Here comes the embarrassing part: It seems like I confused the lack of *GitHub-style rendered* Markdown in the previewer with _support_ for GFM. After further investigating, I noticed that truly GFM additions like ~~strikethrough~~ or
this | is 
---|---
a | table

are actually working, when removing the pip version of Python-Markdown (v3.0) while keeping `pymdown-extras`. I realized that what I am actually looking for is probably some kind of custom *.css as I would like to have GitHub's alternating-shade tables as well as the nicely formatted quoted blocks.

**Comment by mitya57** [comment]
The tables are actually supported out of the box, as they are part of the [Python-Markdown Extra](https://python-markdown.github.io/extensions/extra/) extension.

What features the `pymdownx` extensions add can be deduced from their names or from the [documentation](https://facelessuser.github.io/pymdown-extensions/).

If you want some GitHub-ish CSS, you can download some CSS file and specify it in the Preferences dialog. There are some CSS files mentioned in https://github.com/retext-project/retext/issues/366#issuecomment-391086538 and in https://github.com/retext-project/retext/issues/366#issuecomment-391370848, maybe they will work for you.

**Comment by fprawits** [comment]
thank you for your help!
