### ISSUE TITLE
[FR] Hide tab header if only one tab is open like Falkon/Dolphin etc.

### ISSUE THREAD

**Issue by artemanufrij** [retext-project/retext#393]
I would love it.

**Comment by mitya57** [comment]
There is already an option in the configuration file for this, called `tabBarAutoHide`.

See https://github.com/retext-project/retext/blob/master/configuration.md.

**Comment by artemanufrij** [comment]
@mitya57 could you post the location of this config file, please? I can't find it in my home folder.

I use ArchLinux.

**Comment by mitya57** [comment]
On Linux it is `~/.config/ReText project/ReText.conf`. If that file does not exist, you can create it.

In that file, you can put something like:
```ini
[General]
tabBarAutoHide=true
```
