### ISSUE TITLE
Images are not cached

### ISSUE THREAD

**Issue by dopeboy** [retext-project/retext#396]
I want to start with the comment that this is a fantastic tool. Thank you @mitya57 and others for all your effort on this.

I was using retext on a low data cap connection. I had an image in my markdown file and noticed it gets reloaded in full when I make an update (of any kind) to my markdown file. Is there a way to cache images? If not, would you be open to a PR for it?

**Comment by mitya57** [comment]
Currently the only way to cache image is to save it locally, which is what I recommend to do :)

I will be open to a pull request if the implementation is not too complex.

**Comment by dopeboy** [comment]
Thanks for the quick reply, mitya57. I think my use case might be worth still solving if the final content is going to remotely hosted e.g. on github.

I'll perform a quick analysis and draft up an approach. If it sounds reasonable to you, I'll proceed with a PR.

**Comment by dopeboy** [comment]
Here's a proposed approach. All of it refers to `tab.py`. Feedback is welcome.

* In `startPendingConversion()`, take `self.editBox.toPlainText()` and scan for images (both in markdown and HTML) that have a remote URL. For each such image, download the image and save it into `/tmp`. In this text that is being send to be rendered, replace the remote URLs with local paths.

* When the live preview is closed (can be closed manually or through closing the file), delete these files in `/tmp`. 

* In `triggerPreviewUpdate()`, take an optional parameter. Pass this optional parameter to `startPendingConversion()`. This optional parameter will be non-null when `triggerPreviewUpdate()` is invoked by a text change. This is useful because if the user updated their remotely hosted image, we want a way for them to force a deep refresh of the live preview so that their new image shows. Text changes shouldn't initiate that but, say, opening and closing the live preview area should.

**Comment by dopeboy** [comment]
Bump @mitya57

**Comment by mitya57** [comment]
This was fixed in 5c7b38916f0d2e60495175a9f77a1ff5df2a0e9b and confirmed in https://github.com/retext-project/retext/pull/409#issuecomment-458758594, so I am closing this issue.
