### ISSUE TITLE
Editing from Google Drive - freezing

### ISSUE THREAD

**Issue by porjo** [retext-project/retext#397]
I use Gnome desktop and a Google Drive mount point in the file manager. When I edit a file that is located on Drive, retext freezes regularly as I edit text to the point of being unusable. Editing the same document with Gnome's default text editor has no such problem. Also, editing files on local disk with retext has no such problem.

**Comment by mitya57** [comment]
Hi!

What method are you using for mounting Google Drive?

**Comment by porjo** [comment]
I'm using Gnome's built in 'Online Accounts' facility which integrates with the default file manager 'Gnome Files'. I'm not sure what that uses behind the scenes..

**Comment by porjo** [comment]
> What do the file paths look like for you?

`/run/user/1000/gvfs/google-drive:host=example.com,user=ian/...`

> Do you have auto-save enabled?

No

> Can you try to comment out these lines and see if it helps?

Yes, that seems to fix the issue :+1:

**Comment by mitya57** [comment]
This should be now fixed in master branch.
