### ISSUE TITLE
Soft wrap enable/disable

### ISSUE THREAD

**Issue by holzkohlengrill** [retext-project/retext#398]
Currently soft wrap is disabled in the settings (greyed out) as I undertand because it is still experimental.

When clicking on the text (instead of the greyed out tick box) I am still able to enable it.

Also wrapping does looks not as intended (though it might be that it is still not finished):

![image](https://user-images.githubusercontent.com/12732886/46861995-39d92500-ce14-11e8-95a7-b48408920d5a.png)

**Comment by mitya57** [comment]
You are supposed to set “Draw vertical line at column” to non-zero value first, then you will be able to use soft wrap.

I will fix it.

**Comment by holzkohlengrill** [comment]
Possibly I get the idea wrong but shouldn't the soft wrap feature adapt on the window dimensions (width)?

**Comment by mitya57** [comment]
ReText soft wraps at window borders by default. This feature is needed if you want to wrap earlier.

**Comment by holzkohlengrill** [comment]
I think this is more a usability issue:

![image](https://user-images.githubusercontent.com/12732886/47712556-55c42f80-dc38-11e8-961a-e6c8feef0aaa.png)

* When I enable soft wrap I expect that soft wrap is enabled and it will break at the window boarders.
* However when it is disabled I expect that it will not wrap at all (currently it always wraps no matter if ticked or not)
* `Draw vertical line at column`: after enabling and disabling the value remains (in my case it was the default value = 80).
    * You might want to add another tick box to enable or disable the vertical line
    * You can of course set it to `0` but that seems more like a hack (even if you would do virtually the same in the code)
