### ISSUE TITLE
WebEngine (Chromium) renderer should allow user to set zoom level

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#400]
I need to use _WebEngine (Chromium) renderer_ to get inline math shown.
But this previewer currently does not support zooming.
Please add zoom functionality to the _WebEngine (Chromium) renderer_ preview. 
Currently it is difficult to read text on FullHD display.

Possible workaround is to specify font size using _Edit→Change preview font_ as 16 or bigger. But this does not replace zooming.

Note: I'm using ReText 7.0.4 (installed from pip3) on Ubuntu 16.04 LTS MATE.

**Comment by mitya57** [comment]
Why do you say that changing font does not replace zooming? What should be the difference?

In editor you can use Ctrl + mouse wheel to zoom in/out. But that works based on font size. I can implement the same in WebEngine preview if that helps you.

**Comment by N0rbert** [comment]
Sometimes real-time zooming  by mouse-wheel is very useful. For example to focus attention on some part of the text.

![zoomin][1]

So it would be faster than change font-size every-time. 

If it is possible, please implement zoom for WebEngine when you'll have time.

[1]: https://i.stack.imgur.com/2hpDc.gif

**Comment by mitya57** [comment]
Fixed in master, please test if you can.

**Comment by N0rbert** [comment]
It works, thank you!
