### ISSUE TITLE
Configuration file (ReText.ini) link is not clickable

### ISSUE THREAD

**Issue by holzkohlengrill** [retext-project/retext#402]
Link in preferences seems to be clickable but does not work (pointer changes to a hand). However right click + Copy Link Location works.

I am not sure what is the intended behaviour.

![image](https://user-images.githubusercontent.com/12732886/47006404-1d9bf780-d136-11e8-8b79-93f1d2bcefc7.png)

**Comment by mitya57** [comment]
Can you please check if the linked commit (in wip/issue402 branch) fixes it for you?

**Comment by holzkohlengrill** [comment]
Jap, that fixed it.
