### ISSUE TITLE
ReText incorrectly renders document with fenced code blocks

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#405]
I'm using ReText 7.0.4 as pre-production environment for editing RMarkdown files with bookdown extenstions.
The simplest minimal working example is below:
 
<pre>
---
book_filename: "markdown_test"
site: bookdown::bookdown_site

output:
  bookdown::html_document2: default
---

Below is code listing \@ref(exm:listing1-name). All text below it is wrongly rendered by ReText in `monospace`.

```{example, listing1-name}
label for code listing 1
```
```
some
code
here

```

Some text with formatting: `monospaced` (***bold italic*** = `m`).

Listing \@ref(exm:listing2-name) follows.

```{example, listing2-name}
label for code listing 2
```
```
some
code
here

```

All text above is wrongly rendered `monospace` in ReText.

---

</pre>

It renders normally on Ghostwriter 1.7.3, VNote 2.1 and in RStudio:

* Ghostwriter: 
   ![ghostwriter](https://user-images.githubusercontent.com/309456/47613824-c8050a80-daa6-11e8-9ebc-332f9747a3d6.png)

But in ReText it results in error formatting:

* default renderer
   ![retext-default](https://user-images.githubusercontent.com/309456/47613799-63e24680-daa6-11e8-823f-3dcd49880d5d.png)

* WebEngine
   ![retext-webengine](https://user-images.githubusercontent.com/309456/47613808-79f00700-daa6-11e8-9884-b3ea77403a37.png)

Note: I have enabled `fenced_code` markdown extension - 

```
$ cat $HOME/.config/markdown-extensions.txt
mathjax
fenced_code
```

but it does not help.

**Comment by mitya57** [comment]
Labels for code listings are not a standard Markdown feature, I hear for the first time about it. [Babelmark 2](https://johnmacfarlane.net/babelmark2/), the tool for comparing Markdown implementations, also knows nothing about it.

What fenced blocks are supported is described in the [documentation](https://python-markdown.github.io/extensions/fenced_code_blocks/).

If you want to add support for your own syntax, you can try to write your own extension for that. How to do that is also described in the [documentation](https://python-markdown.github.io/extensions/api/).

With regards to the meta-data on top of your file: ReText will recognize (and hide) it if you enable the [`meta` extension](https://python-markdown.github.io/extensions/meta_data/). But you will need to remove the empty line between `site` and `output`.

**Comment by N0rbert** [comment]
Thanks for the `meta` hint :)

I do not need to write an extension, I mean that 

<pre>
```{example, listing1-name}
label for code listing 1
```
```
some
code
here
```
</pre>

should be rendered without errors in any place of the document. 
From ReText I need simple adequate preview. 
Could you please fix this? Or please point me to the correct upstream direction.

**Comment by mitya57** [comment]
I mean that this line:

    ```{example, listing1-name}

is not a correct Markdown syntax. So it won‘t be recognized as code block start.

**Comment by N0rbert** [comment]
I understood, thank you for all your work and time :)
