### ISSUE TITLE
Feature request: backslash for hard line break

### ISSUE THREAD

**Issue by j77h** [retext-project/retext#410]
The CommonMark Spec says that a hard line break can be set by a backslash instead of 2 spaces.
https://spec.commonmark.org/0.28/#hard-line-break
But ReText 7.0.4 does not convert it to \<br>.

Trailing spaces are problematic because I set my text editor (SciTE) to remove them on save.
I rely on that option; if I turn it off I waste time tidying line ends, and SciTE's auto-indenter leaves many 'empty' lines of spaces or tabs.
The editor in ReText lacks some features that SciTE has (and I've been using SciTE daily for 10+ years), so I tend to write a doc in ReText, massage it in SciTE, then use ReText to export it to html.

Many thanks for ReText, it's great! Before I found it I was writing html entirely in SciTE, because there's no clean open-source wysiwyg html writer (they all add too much redundant code).

**Comment by mitya57** [comment]
First of all, CommonMark is a different language from Markdown. It is better standardized but also has many features that the original Markdown does not have. ReText is primarily a Markdown editor.

However, ReText supports [Python-Markdown extensions](https://github.com/retext-project/retext/wiki/Markdown-extensions). And it appears that there is already an [extension](https://facelessuser.github.io/pymdown-extensions/extensions/escapeall/) that supports this feature.

So getting the behavior you want is as easy as:

- Running `pip3 install --user pymdown-extensions` or a similar command to install pymdown-extensions;
- Adding `pymdownx.escapeall(hardbreak=true)` to the “Markdown syntax extensions” field in Preferences dialog.

**Comment by j77h** [comment]
Neat, thanks!
Don't know how I missed Python-Markdown extensions before.
Might end up using nl2br instead, and will definitely use Smarty.
