### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by scx** [retext-project/retext#412]
I created the flatpak package for ReText.
https://github.com/scx/retext-flatpak#retext-flatpak

I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/376

It would be nice if the author decided to participate in the further development of the flatpak package.
https://github.com/flathub/flathub/pull/376#issuecomment-443096430

**Comment by mitya57** [comment]
Hi! I appreciate your efforts and I am now subscribed to flathub/flathub#376, but I have very limited time even for upstream maintenance so I can't promise that I will be able to maintain also flathub package.

**Comment by scx** [comment]
Thanks for the quick reply.
I will try to take care of the flatpak package as much as I can.
All comments are welcome. I want to make sure that everything works as it should.

**Comment by mitya57** [comment]
Thanks! Feel free to ask me if there are any problems with packaging it.

**Comment by mitya57** [comment]
There is nothing to do on ReText side, so I am closing this.
