### ISSUE TITLE
 Is it necessary to install the python-markdown package?

### ISSUE THREAD

**Issue by kiminseob** [retext-project/retext#418]
(I do not speak English very well. I hope you understand..)

Environment : ubuntu 18.04.1 LTS

I think the **python-markdown** package you recommended in the readme is required..?

- Before installing the python-markdown package
![Before installing the python-markdown package](https://user-images.githubusercontent.com/14813208/49781421-f9375280-fd55-11e8-8032-cc85bffb16ee.png)

- After installing the python-markdown package
![After installing the python-markdown package](https://user-images.githubusercontent.com/14813208/49781478-3a2f6700-fd56-11e8-9ada-764ebae30085.png)

**Comment by mitya57** [comment]
In Ubuntu the required package is `python3-markdown`.

If you install ReText using `pip3` or `apt`, you should get this dependency automatically.
