### ISSUE TITLE
Why not use Hotkeys to Formating?

### ISSUE THREAD

**Issue by KdungKdung** [retext-project/retext#419]
It would be nice 
if it added shortcuts key (like this, header(F1 key), bold(F2 key),underline(F3 key)...... etc.) 
for the selected texts.

Is it possible to make a small modification to this code?
window.py 

Can I add a shortcut key here to trigger it?

**Comment by mitya57** [comment]
For Bold and Underline there are already <kbd>Ctrl</kbd>+<kbd>B</kbd> and <kbd>Ctrl</kbd>+<kbd>U</kbd> shortcuts.

Using F-keys is unconventional, for example F1 is used for help in most applications.
