### ISSUE TITLE
add hotkey

### ISSUE THREAD

**Issue by KdungKdung** [retext-project/retext#421]
Thank you for quick response.

The header function is a frequently used function.

`		self.actionUnderline = self.act(self.tr('Underline'), shct=QKeySequence.Underline,
			trig=lambda: self.insertFormatting('underline'))
`
The code above is the shortcuts key part of window.py
 Like the previous Bold key(Ctrl +B ),

`		self.actionHeader = self.act(self.tr('Header'), shct= Qt.CTRL + Qt.Key_H,
			trig=lambda: self.insertFormatting('header'))
`
How about adding it this way?
(CTRL+H is the Standard shortcuts key in QKeySequence....(Replace Key in Windows)
So it would be better to unify.)

Is this a possible way?

**Comment by mitya57** [comment]
Adding a header is just a matter of typing `#` for the first level header, or `##` for the second level one.

How is that harder than typing Ctrl+H?

**Comment by KdungKdung** [comment]
Thankyou for your feedback

but, For people who do not know why they typing # and the Markdown language, it may be necessary to explain the trivial addition of #.

What I mean is to apply shortcuts to other formats as well as header. It's not just the header.

**Comment by mitya57** [comment]
> For people who do not know why they typing # and the Markdown language

Why will such people use ReText at all? It is an editor for Markdown, and headers are a very basic concept of Markdown.

Also ReText has a Formatting box which may act like a tip, and it has a documentation link in the About dialog.

That said, feel free to submit a pull request for this, but I am not interested in implementing it myself.

**Comment by JoelMon** [comment]
> but, For people who do not know why they typing # and the Markdown language, it may be necessary to explain the trivial addition of #.

It's not trivial, it's part, and a very basic part may I add, of the markdown syntax.

**Comment by mitya57** [comment]
I agree with @JoelMon. ReText users are expected to have at least basic knowledge of Markdown (or the other markup language they are using).

So I am closing this bug.
