### ISSUE TITLE
Installs the empty directory share/retext/locale

### ISSUE THREAD

**Issue by yurivict** [retext-project/retext#422]
Please either install files into this directory, or do not install it at all.
Found in the FreeBSD port.

**Comment by mitya57** [comment]
If you are using the tarballs from PyPI, then this directory should be not empty and should contain `.qm` files (translations in Qt format).

If you are using a Git checkout and building ReText from it, please make sure you have `lrelease` tool from Qt 5 installed. It is used in the build process.

**Comment by yurivict** [comment]
I use GitHub.
I have ```lrelease``` installed (/usr/local/lib/qt5/bin/lrelease) but it doesn't use it.

**Comment by mitya57** [comment]
Is that on your `$PATH`?

**Comment by yurivict** [comment]
It is in the path, and 
```
        import os
        os.system("lrelease -x")
```
runs it.
But this line fails:
> check_call(('lrelease', ts_file), env={'QT_SELECT': '5'})
```
Failed to build translations: [Errno 2] No such file or directory: 'lrelease': 'lrelease'
```

**Comment by mitya57** [comment]
That is strange. The (old and unsafe) [`os.system`](https://docs.python.org/3/library/os.html#os.system) function uses [system(3)](https://www.freebsd.org/cgi/man.cgi?system(3)), which in turn uses executes `/bin/sh -c {command}`.

Can it be that `$PATH` is different for `/bin/sh` and for the Python interpreter?

Also do you use qtchooser? It may provide `lrelease` on a different path, and there may be problems with that path.

**Comment by yurivict** [comment]
> Can it be that $PATH is different for /bin/sh and for the Python interpreter?

No, I don't see how can this be.

> Also do you use qtchooser?

No, the path is direct.

**Comment by mitya57** [comment]
Can you try this patch?
```diff
--- a/setup.py
+++ b/setup.py
@@ -14,6 +14,7 @@ For more details, please go to the `home page`_ or to the `wiki`_.
 .. _`home page`: https://github.com/retext-project/retext
 .. _`wiki`: https://github.com/retext-project/retext/wiki'''
 
+import os
 import sys
 from os.path import join, isfile, basename
 from distutils import log
@@ -55,9 +56,10 @@ class retext_build_translations(Command):
 		pass
 
 	def run(self):
+		environment = dict(os.environ, QT_SELECT='5')
 		for ts_file in glob(join('locale', '*.ts')):
 			try:
-				check_call(('lrelease', ts_file), env={'QT_SELECT': '5'})
+				check_call(('lrelease', ts_file), env=environment)
 			except Exception as e:
 				log.warn('Failed to build translations: %s', e)
 				break
```
