### ISSUE TITLE
Table Wizard

### ISSUE THREAD

**Issue by khe0613** [retext-project/retext#424]
Thank you for your kind feedback.
Can I add the Table Wizard function?

I know that there is a table edit mode. 
However, I think it would be more convenient to automatically create a table by specifying rows and columns. The Table wizard allows you to select the row and column of the table to be created and the alignment of the table elements.

**Comment by mitya57** [comment]
Please be more verbose. Do you mean an action that will insert an HTML `<table>` into the document, a Markdown table, or what?

It looks like you are not the first one who is requesting this. Issue #308 was a similar suggesion. So I am open to a pull request implementing this if it does not add much code complexity.

**Comment by khe0613** [comment]
I mean Markdown Table!!


![khe0613](https://user-images.githubusercontent.com/34531914/50258279-44caba00-0442-11e9-9a84-51c6a7df3b34.JPG)

**Comment by mitya57** [comment]
Fixed by #431.
