### ISSUE TITLE
"--record {plist}" records bin/retext.py, but it installs bin/retext

### ISSUE THREAD

**Issue by yurivict** [retext-project/retext#425]
There's a mismatch between what is recorded with ```--record {plist}``` and what is installed:
```
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: bin/retext
===> Checking for items in pkg-plist which are not in STAGEDIR
Error: Missing: bin/retext.py
```

**Comment by mitya57** [comment]
I think I will fix this by switching from custom code to setuptools entry points.

Until I fix that, pass `--no-rename` to setup.py install, that should work around your problem.

**Comment by mitya57** [comment]
Please try the current master version. setup.py is now using setuptools entry points, so there is less custom magic now.

**Comment by yurivict** [comment]
Ok, thank you for fixing this!
