### ISSUE TITLE
[Documentation Request] List of tags/parmeters for Editor style.qss

### ISSUE THREAD

**Issue by nh3oh** [retext-project/retext#432]
Hi,

Apparently, in **retext.conf** the _**"appStyleSheet"**_ parmeter allows user to give a custom **style.qss** path.

That's great !

But where to find info in order to edit such a file ?

I've yet found : https://github.com/retext-project/retext/issues/18

that gives :
```
QTextEdit { 
     background-color: #1d1d1d; 
     color: #dfc47d 
}

```
Would be kind to add in the wiki an example showing all param=value in a similar way made for retext.conf

Thanks & best regards.

**Comment by mitya57** [comment]
See these pages:

- https://doc.qt.io/qt-5/stylesheet.html
- https://doc.qt.io/qt-5/stylesheet-reference.html

I will add a link to `configuration.md` now.

**Comment by nh3oh** [comment]
Thanks, for answer.

Sorry, my question wasn't enough precise.

I would have to ask for **qss selectors list** that can be used to customize the **editor display**

in order to set **properties for each format items** (header, codeblock, blockquote, ...).

I suppose those selectors names are defined in the application code, aren't they.

**Comment by mitya57** [comment]
At the moment you cannot customize the syntax highlighter styles. They are hard-coded in [highlighter.py](https://github.com/retext-project/retext/blob/master/ReText/highlighter.py#L110), you can only customize the colors (as described in configuration.md).

**Comment by nh3oh** [comment]
Ok, I understand, thanks
