### ISSUE TITLE
Highlight dead links

### ISSUE THREAD

**Issue by red-kite** [retext-project/retext#438]
It would be imho a useful feature to highlight links to nonexistent files on the local machine. Just like popular wiki-software does.

Don't really know if i'm digging to deep in markup-languages (should work for .md and .rst, generally said for all html output) or in territory of renderer.

I'm thinking of these links being marked with a distinct css-class.

**Comment by mitya57** [comment]
If highlighting in preview (not in editor) is an option for you, you can implement this as a [Markdown extension](https://python-markdown.github.io/extensions/api/) and then enable it as described in the [wiki](https://github.com/retext-project/retext/wiki/Markdown-extensions).

Implementing in editor/highlighter would be much more complicated, as there are many different ways to create links in Markdown and reStructuredText. So I am closing this.
