### ISSUE TITLE
Displaying Japanese characters

### ISSUE THREAD

**Issue by ijklsd** [retext-project/retext#443]
I have a document that contains Japanese characters. Both in the document panel and in the preview panel, the Japanese characters are displayed incorrectly - essentially, I get a string of ASCII characters, printable and otherwise, that have nothing to do with Japanese:

![leftpanel](https://user-images.githubusercontent.com/47425074/52423783-08b4ec80-2ab6-11e9-95fb-3bed16999a4c.png)

![rightpanel](https://user-images.githubusercontent.com/47425074/52423871-2e41f600-2ab6-11e9-8cc6-5149e9cf6556.png)

In my underlying shell, the Japanese characters are displayed correctly:

![shell](https://user-images.githubusercontent.com/47425074/52424018-5fbac180-2ab6-11e9-9938-ed49a34f3fc8.png)

Can ReText be configured so that such characters are displayed as they should, like in my shell?

**Comment by ijklsd** [comment]
For what it's worth. this can be achieved by clicking on File -> Set encoding, and selecting UTF-8.

**Comment by mitya57** [comment]
Can you check if setting `detectEncoding` to false in the [configuration file](https://github.com/retext-project/retext/blob/master/configuration.md) (and removing `defaultCodec` setting) also fixes the issue?

If that is the case, I will disable `detectEncoding` by default.
