### ISSUE TITLE
Enabling MathJax in ReText for Windows 10

### ISSUE THREAD

**Issue by justineuro** [retext-project/retext#444]
According to the [documentation](https://github.com/retext-project/retext/wiki/Math), for Linux OSs MathJax should be installed in `/usr/share/javascrpt/mathjax` folder.  What would be the equivalent location for Windows 10?  Thank you in advance.

**Comment by justineuro** [comment]
I may have figure it out.  Installing MathJax under `C\:` using `git clone https://github.com/mathjax/MathJax.git`, so that `C:\MathJax` is my main MathJax directory, seems to work for me.  Doing so gets ReText to render the math formulas:
- inline with `\( ... \)`
- math environment mode with `$$ ... $$` or `\[ ... \]`

**Comment by mitya57** [comment]
Offline MathJax is currently not supported on Windows. But if you have internet connection then MathJax will be loaded from `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js`.
