### ISSUE TITLE
Rendering errors

### ISSUE THREAD

**Issue by ijklsd** [retext-project/retext#446]
I am using the latest ReText release, and I have come across a few problems with literal text - i.e. text between triple backquotes:

1. When the literal text is inserted within a numbered items list, blank lines in the text are incorrectly processed. The only way I have been able to get it to behave (almost) the way I want is by splitting the literal text into chunks that do not contain any blank lines.

2. Certain characters between the backquotes are interpreted as special characters, despite the fact that they are between the backquotes. For example, a triple hyphen at the beginning of a line is rendered as a horizontal line, edge to edge, and a sharp character (#) at the beginning of a line is interpreted as the start of a new section. I observed this, again, within a numbered items list.

**Comment by mitya57** [comment]
Can you please mention the version of Python-Markdown that you have installed, and paste (or attach) Markdown snippets that render incorrectly?

**Comment by mitya57** [comment]
I am closing this as you have not provided the requested information.
