### ISSUE TITLE
Highlight with pymdownx.highlight

### ISSUE THREAD

**Issue by shvchk** [retext-project/retext#451]
Can't get [PyMdown Highlight](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/) extension to work, while default `codehilite` works fine. Well, `pymdownx.highlight` does seem to load, as I get line numbers (if I set `linenums=True`), but code does not get highlighted. Am I supposed to provide CSS for it myself?

My `~/.config/markdown-extensions.txt`:

```
remove_extra
pymdownx.extra
pymdownx.highlight(guess_lang=True)
```

**Comment by mitya57** [comment]
Thanks for your report! Please try the latest master version of pymarkups, I have added support for `pymdownx.highlight` there.

**Comment by shvchk** [comment]
Thanks! It mostly works, the only issue is that sometimes blank lines in code got replaced with `__posmapmarker__X` (`X` is a number). It probably has something to do with `<<` in code.

Example:
```bash
tee ~/test << EOF
A

B

C
EOF
```
translates to:

```
tee ~/.profile << EOF
A

__posmapmarker__3

B

__posmapmarker__5

C
EOF
```

Probably similar to #299

**Comment by mitya57** [comment]
This was an unfortunate side-effect of our synchronized scroll implementation.

It requires a special work-around for highlight extensions. I have added one for pymdownx.highlight now, this time you need ReText from master.

**Comment by shvchk** [comment]
Perfect, thanks!
