### ISSUE TITLE
ReText has wrong Exec and Icon lines in /usr/local/share/applications/me.mitya57.ReText.desktop file when installed with pip3

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#452]
Steps to reproduce:
1. Have Ubuntu 16.04.6 LTS or Ubuntu 18.04.2 LTS installed with all updates
1. Install `pip3` with `sudo apt install python3-pip`
1. Install ReText from pypi with `sudo -H pip3 install retext`

Expected results:
* pip3 installed ReText with correct paths in desktop-file - user can launch application from Dash and can identify ReText by its icon

Actual results:
* pip3 installed ReText with broken paths in `/usr/local/share/applications/me.mitya57.ReText.desktop` file:

  ```
  $ cat /usr/local/share/applications/me.mitya57.ReText.desktop | grep -E "Exec|Icon"
  Exec=ReText-7.0.4.data/scripts/retext %F
  Icon=ReText-7.0.4.data/data/share/retext/icons/retext.svg
  ```

  Screenshot from `mozo` *Main Menu* editor
  ![retext](https://user-images.githubusercontent.com/309456/54869566-92412500-4dab-11e9-990d-573c2103e3c3.png)

* ReText starts normally only from terminal as

  ```
  $ which retext 
  /usr/local/bin/retext
  ```

  is correct.

Temporary workaround:
* Change paths in `/usr/local/share/applications/me.mitya57.ReText.desktop` manually to

  ```
  Exec=/usr/local/bin/retext
  Icon=/usr/local/share/retext/icons/retext.svg
  ```

**Comment by mitya57** [comment]
Thanks for reporting this! I will fix it ASAP. In the meantime, passing `--no-use-wheel` to pip should work around the issue.

**Comment by mitya57** [comment]
So it looks like by default pip first builds a wheel and then installs it. When installing into a wheel, our setup.py thinks that the wheel directory is the final destination and writes that path to the .desktop file. There is no way to know what the actual destination will be.

I have just pushed a commit that disables any path substitution at all when building wheels, so the desktop file will have generic `Exec=retext %F` and `Icon=retext` lines. This is not ideal, but better than the current situation.

I recommend either using the distro packages, or running pip with `--no-cache-dir` like my previous comment says.
