### ISSUE TITLE
Do not support web image

### ISSUE THREAD

**Issue by sonichy** [retext-project/retext#453]
Do not support web image.
And table has no background.

**Comment by mitya57** [comment]
ReText supports web images, but only if you enable WebKit or WebEngine preview from the menu.

I don’t understand what you mean by “no background”, but there are many options for styling: per-document CSS styles (`your-doc-basename.css`), global CSS styles (see `styleSheet` [configuration file][1] option) and inline CSS via `<style>` tags.

[1]: https://github.com/retext-project/retext/blob/master/configuration.md#possible-configuration-options

**Comment by sonichy** [comment]
Table has no border no background like normal text, it should like this:
![](https://www.simipic.com/images/2019/04/16/__201904160942123aeb3832841584a0.png)
