### ISSUE TITLE
Do not support delete line

### ISSUE THREAD

**Issue by sonichy** [retext-project/retext#455]
`~~Delete~~`
~~Delete~~

**Comment by mitya57** [comment]
This syntax is not a standard feature of Markdown, so it is not supported by default. However, there is a third-party extension which supports it:

https://facelessuser.github.io/pymdown-extensions/extensions/tilde/

You can install and enable it as documented in the [wiki] and in https://github.com/retext-project/retext/issues/369#issuecomment-390983311.

[wiki]: https://github.com/retext-project/retext/wiki/Markdown-extensions
