### ISSUE TITLE
Latest releases not on GitHub releases

### ISSUE THREAD

**Issue by rsyring** [retext-project/retext#457]
I initially reviewed the [releases page](https://github.com/retext-project/retext/releases) and saw 7.0.0 being released over two years ago. I almost bailed on installing this project and trying it b/c I thought it had been abandoned.   I then checked PyPi and noticed a few more releases since then. 

Just wanted to point out the discrepancy.  :)

**Comment by mitya57** [comment]
Fixed — release for 7.0.4 is here: https://github.com/retext-project/retext/releases/tag/7.0.4
