### ISSUE TITLE
Code execution via path traversal

### ISSUE THREAD

**Issue by RootUp** [retext-project/retext#460]
## Summary
A local file path traversal issue exists in latest version of retext for ubuntu which allows an attacker to execute arbitrary programs.

## Technical observation
We are abusing the URI schemes here so, a crafted URI can be used in a note to perform this attack using file:/// as an argument or by traversing to any directory like (../../../../something.sh) 
```sh
Example: [google.com](file:///etc/passwd)
```

Also it was observed the application allows users to execute JS, such as.
```JS
<scripT>alert(/Its not an XSS test/)</scripT>
```
See the above output in preview mode this will pop and alert, this issue is not about XSS its just to demonstrate that the application allows JS to get executed. I can use malicious JS to perform any further attack.

**Comment by mitya57** [comment]
Yes, the WebKit and WebEngine preview backends allow users to execute JS. This is helpful, e.g. JS is needed to render math formulas with MathJax.

Note that WebKit and WebEngine are not default, so the user needs to explicitly enable them.

**Comment by RootUp** [comment]
Thank you @mitya57 for quick response, could to take a look on the path traversal issue, reading local files via abusing the URI schemes.

**Comment by mitya57** [comment]
Do you mean that specially formed files can send user’s file contents to a remote server?

It is strange because we explicitly disallow this in both WebKit previewer:

https://github.com/retext-project/retext/blob/afb326bf8b683d632e292dae1650ea310b7d88c1/ReText/webkitpreview.py#L47

and WebEngine previewer:

https://github.com/retext-project/retext/blob/afb326bf8b683d632e292dae1650ea310b7d88c1/ReText/webenginepreview.py#L88-L89

Can you check which backend has the bug? (What checkbox is active in the edit menu?)

**Comment by RootUp** [comment]
Oh, let me re-frame this for you the URI schemes opens `file:///etc/passwd` in primary text editor of your OS rather than the webview.

**Comment by mitya57** [comment]
So this is not “arbitrary programs”, but “programs associated with file types”, and they are executed only when user clicks a link?

**Comment by RootUp** [comment]
`file:///etc/passwd` is just an example, programs can be anything.

> and they are executed only when user clicks a link?

Yes

**Comment by mitya57** [comment]
If the attacker cannot steal any data, and if opening a program requires an explicit click, I do not consider this a vunlerability.

If you want an option to not call any programs for local files, then pull requests are welcome.
