### ISSUE TITLE
Update template for HTML5?

### ISSUE THREAD

**Issue by LeeUnd** [retext-project/retext#462]
I see that this was addressed [back in 2015/16](https://github.com/retext-project/retext/issues/163). I was wondering if anything has been done since then. I would be great to either have an HTML5 template or the ability to make our own template.

**Comment by mitya57** [comment]
ReText export generates HTML 5 files by default, using this template:

https://github.com/retext-project/pymarkups/blob/ee9056b8fa8d00b39972f80f5db881b576179c82/markups/abstract.py#L7-L16

If you want a custom template, I highly recommend you to use one of the tools I mentioned in https://github.com/retext-project/retext/issues/163#issuecomment-154513103.

Or do you want something else?

**Comment by mitya57** [comment]
I am closing this bug. Being a static site generator is out of scope for ReText, and there are many third-party tools that do it.
