### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by Aquarian-Age** [retext-project/retext#463]
第一次安装可以用　之后就出现下面现象无法用了
/usr/bin/python3: Relink `/usr/lib64/libsystemd.so.0' with `/lib64/librt.so.1' for IFUNC symbol `clock_gettime'
段错误 (核心已转储)

**Comment by farseerfc** [comment]
請報告您正在使用的發行版版本、python3 版本、systemd 版本、 glibc 版本。以及請嘗試把所有軟件包升級到發行版提供的最新版本然後再次嘗試。
Please report your distribution version, python3 version, systemd version, and glibc version. And please also try to upgrade all the packages to the latest version and retry.

For other English speakers:
This issue is titled "Segfault (core dumped)".
The contents says:
    I was able to use after installation, but after that I cannot use due to the following phenomenon:
    /usr/bin/python3: Relink /usr/lib64/libsystemd.so.0' with /lib64/librt.so.1' for IFUNC symbol `clock_gettime'
    segfault (core dumped)

**Comment by Aquarian-Age** [comment]
> 请报告您正在使用的发行版本本，python3版本，systemd版本，glibc版本。以及请尝试把所有软件包升级到发行版提供的最新版本然后再次尝试。
> 请报告您的发行版本，python3版本，systemd版本，和glibc版本。并且还请尝试将所有软件包升级到最新版本并重试。
> 
> 其他英语使用者的翻译：
> 此问题的标题是“Segfault（core dumped）”。
> 内容说：
> 我可以在安装后使用，但之后由于以下现象我无法使用：
> / usr / bin / python3：使用/lib64/librt.so重新链接/usr/lib64/libsystemd.so.0' .1'表示IFUNC符号`clock_gettime'segfault 
> （核心转储）

liangzi@xuan 34 09:43 >python3 --version
Python 3.6.5
~/.local/bin
liangzi@xuan 35 10:27 >systemd --version
systemd 234
+PAM -AUDIT +SELINUX -IMA +APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN default-hierarchy=hybrid
~/.local/bin

~/.local/bin
liangzi@xuan 37 10:27 >ldd --version
ldd (GNU libc) 2.26
Copyright (C) 2017 自由软件基金会。
这是一个自由软件；请见源代码的授权条款。本软件不含任何没有担保；甚至不保证适销性
或者适合某些特殊目的。
由 Roland McGrath 和 Ulrich Drepper 编写。

感谢回复
第一个通过python3 -m pip install ReText --user　安装后可以用
之后安装了python-Markups　python-markdown　发现默认python版本都是2的然后卸载了　然后就不能用了　重新安装也不行

**Comment by Aquarian-Age** [comment]
经过几次的反复安装　测试　发现问题在这里
```
stat("/usr/bin", {st_mode=S_IFDIR|0755, st_size=135168, ...}) = 0
stat("/usr/lib64/python3.6", {st_mode=S_IFDIR|0755, st_size=12288, ...}) = 0
stat("/usr/lib64/python3.6/lib-dynload", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/xuan/.local/lib/python3.6/site-packages", {st_mode=S_IFDIR|0700, st_size=277, ...}) = 0
stat("/usr/lib64/python3.6/site-packages", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/lib64/python3.6/_import_failed", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/lib/python3.6/site-packages", {st_mode=S_IFDIR|0755, st_size=16384, ...}) = 0
stat("/usr/lib64/python3.6/site-packages/PyQt5", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/usr/lib64/python3.6/site-packages/PyQt5/QtPrintSupport.so", {st_mode=S_IFREG|0755, st_size=316184, ...}) = 0
````
之后我手动删除了python*/site-packages/的PyQt5　markups　markupsafe
然后变更python默认版本为3.6
```
ln -sf python3.6 $(pwd)/python
ln -sf python3-config $(pwd)/python-config
ln -sf python3.6m-config $(pwd)/python3.6-config
```
进入源码目录重新安装
```
python3.6 setup.py build
python3.6 setup.py install --user

pip install markups==3.0.0 
```
问题解决了
