### ISSUE TITLE
RuntimeWarning: Dictionary for language 'zh_CN' could not be found

### ISSUE THREAD

**Issue by Aquarian-Age** [retext-project/retext#464]
### Unable to input Chinese
Use the openSUSE distribution
Tried all methods are invalid

retext
```
Using configuration file: /home/xuan/.config/ReText project/ReText.conf
/home/xuan/.local/lib/python3.6/site-packages/ReText/window.py:389: RuntimeWarning: Dictionary for language 'zh_CN' could not be found
  warnings.warn(str(e), RuntimeWarning)
```
l .local/share/retext/locale/retext_zh_CN.qm
-rw-r--r-- 1 xuan users 8434 6月   6 10:46 .local/share/retext/locale/retext_zh_CN.qm

locale
```
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```

python -c "from PyQt５.QtCore import QLocale; print(QLocale.system().name())"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt５'
```

python --version
Python 3.6.5

ln -s /usr/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so /home/xuan/.local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforminputcontexts/

ls -ltr /home/xuan/.local/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforminputcontexts/
```
总用量 220
-rwxr-xr-x 1 xuan users 156288 6月   6 06:46 libibusplatforminputcontextplugin.so
-rwxr-xr-x 1 xuan users  64968 6月   6 06:46 libcomposeplatforminputcontextplugin.so
lrwxrwxrwx 1 xuan users     82 6月   6 10:36 libfcitxplatforminputcontextplugin.so -> /usr/lib64/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so
```

pip list
```
docutils                 0.14 
Markdown                 3.1.1 
Markups                  3.0.0      
MarkupSafe               1.0  
PyQRCode                 1.2.1      
PyQt5                    5.12.2     
PyQt5-sip                4.19.17
ReText                   7.1.0 
```

Exec=env LC_NUMERIC=zh_CN.UTF-8 /home/xuan/.local/bin/retext %F
```
Using configuration file: /home/xuan/.config/ReText project/ReText.conf
/home/xuan/.local/lib/python3.6/site-packages/ReText/window.py:389: RuntimeWarning: Dictionary for language 'zh_CN' could not be found
  warnings.warn(str(e), RuntimeWarning)

```

cat -n .config/ReText\ project/ReText.conf
```
     1	[General]
     4	"uiLanguage=zh_CN.UTF-8"
```

**Comment by mitya57** [comment]
Which exactly input methods did you try? Do you use ibus, fcitx or something else? Does Chinese input work in other Qt applications such as Qt Assistant?

The warning printed is related to spell checker. I am not sure spell checker applies to Chinese at all, but if it does, you need to install a spelling dictionary for one of supported spell checkers (myspell, aspell, ispell or hunspell).

**Comment by Aquarian-Age** [comment]
> 您尝试了哪种输入法？你使用ibus，fcitx还是别的什么？中文输入是否适用于其他Qt应用程序，如Qt Assistant？
> 
> 打印的警告与拼写检查有关。我不确定拼写检查器是否适用于中文，但如果确实如此，则需要为其中一个支持的拼写检查器（myspell，aspell，ispell或hunspell）安装拼写字典。

感谢回复　我使用fcitx　中文输入适用其他Ｑt程序　最初安装之后是可以输入中文的　后来用'python不同版本(3.X)覆盖安装之后无法启动　各种尝试之后可以启动了　然而中文输入没有了　现在就当做一个预览ＭＤ的工具了　毕竟我英语都是谷歌翻译....
