### ISSUE TITLE
Feature Request: Provide current filename as suggested name on "Save As" and Exports

### ISSUE THREAD

**Issue by kannes** [retext-project/retext#469]
It would be very helpful if the current file's filename was automatically used as filename in the "Save file" dialogs of the "Save As" option and the various "Export" options.

For export it should be minus the extension of course.

Thank you!

**Comment by mitya57** [comment]
Fixed in master branch now, please test if you can.

**Comment by kannes** [comment]
This is awesome, works like a charm. Thank you!

**Comment by mitya57** [comment]
Thanks should go to @xgouchet :)

**Comment by kannes** [comment]
It does! :)
