### ISSUE TITLE
Directory tree side pane

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#47]
A directory/document tree side pane like Zim's would be a fine convenience if it's not a big trouble.

Reported by: gooddead

Original Ticket: [retext/tickets/47](https://sourceforge.net/p/retext/tickets/47)

**Comment by oguzhanogreden** [comment]
I started a little on a document navigation tree solution. I opted for a sidebar solution. You can see the relevant branch [here](https://github.com/oguzhanogreden/retext/tree/treenav-oo). I'm facing a decision which is likely relevant for future of this patch. Hence I'm bringing it up here.

The decision is mainly regarding the following question: _How will this scale to large documents? (= Is there a preferred large performance test file?)_

Briefly, this implementation:
A1. parses the conversion output,
A2. creates a `ReTextTreeModel` object (which inherits `QAbstractItemModel`),

When the conversion output is renewed (as signalled by `converterProcess.conversionDone`), it updates the tree by:
B1. Starts a new round of A1 & A2,
B2. Compares the new model (outcome of B1) to the present one (outcome of A2),
B3. If any difference is present (i.e. if the two lists are not identical),
B4. Starts using the new model.

Specifically, is it a reasonable idea to create trees from scratch using the converted document?

(I know that RStudio has a similar feature which gives a dropdown list of defined functions and specifically tagged comment headers. I'll check that in the meanwhile.)

Best,
Oğuzhan

**Comment by oguzhanogreden** [comment]
Checking other implementations including RStudio, perhaps it's an overkill to use the QTreeView here. I can simply list the headers and give the hierarchy effect with indentations (and or by appending the header to \# or \## etc.).

This removes expand/collapse use of the hierarchy. Then again, for extremely large documents, a better Markdown approach would be switching files at one of the higher levels of hierarchy.

What do you think?

**Comment by mitya57** [comment]
@oguzhanogreden I agree that a tree is overkill, just a simple list structure sounds fine to me.

I do not like the idea of converting HTML back to an ElementTree, because an ElementTree already exists during conversion (i.e. for Markdown it exists [here](https://github.com/Python-Markdown/markdown/blob/master/markdown/__init__.py#L379)).

I think it is better to write an extension that will be run after all tree processors and will save the headers structure to some attribute of Markdown instance. Then you can make PyMarkups set this structure as an attribute of [ConvertedMarkup](http://pythonhosted.org/Markups/interface.html#markups.abstract.ConvertedMarkup) object.

You can enable such extension similarly how we enable [mdx_posmap](https://github.com/retext-project/retext/blob/master/ReText/mdx_posmap.py). Or you can just append the tree processor to mdx_posmap code, as it requires posmap information anyway.

**Comment by oguzhanogreden** [comment]
Agreed with reusing the existent trees. I needed the direction towards extensions and now I have it without regenerating tree.

Thinking further along the line, though, I think two small features of such a navigation tree are:
1. Mark the header under which the cursor is located,
2. Move editor and preview to the clicked header (moving the cursor should be enough here, I think)

I'm guessing you mentioned `posmap`s as a direction for these. I've been looking into the posmap thinking. So far, I can not think of a direct way to link the line number of the cursor (in editor) and the posmap. I may be missing something though.
