### ISSUE TITLE
increment bullet list with 2 spaces

### ISSUE THREAD

**Issue by monperrus** [retext-project/retext#470]
Hello!

On Github, one can increment the bullet list level with two spaces. On ReText, 4 more spaces are needed.

How to configure retext such that the bullet list level is set with two more spaces, as on Github?

Thanks!

**Comment by mitya57** [comment]
Actually GitHub goes against the rules here, as the [syntax rules](https://daringfireball.net/projects/markdown/syntax#list) clearly state:

> Each subsequent paragraph in a list item must be indented by either 4 spaces or one tab

However, there is a third-party extension called [mdx_truly_sane_lists](https://github.com/radude/mdx_truly_sane_lists) that changes the indent level to 2. I have just tried it and it works:

- Install it using `pip3 install --user mdx_truly_sane_lists`.
- Enable it by adding `<!-- Required extensions: mdx_truly_sane_lists -->` or adding that extension to your `~/.config/markdown-extensions.txt`. See our [wiki](https://github.com/retext-project/retext/wiki/Markdown-extensions) for details.

**Comment by monperrus** [comment]
Thanks, I confirm that it works with mdx_truly_sane_lists.
