### ISSUE TITLE
How do you add a word to the spellchecker?

### ISSUE THREAD

**Issue by Lokathor** [retext-project/retext#472]
I turned on spellcheck, and it shows corrections when you right click on a word, but the pop-up menu doesn't appear to have an option for adding a word to a dictionary so that it can be counted as correct.

**Comment by mitya57** [comment]
This was implemented in #320, but unfortunately not released yet. Can you try master branch?

**Comment by Lokathor** [comment]
Will do.

Looks like this is a pure python program? just clone it and run?

**Comment by mitya57** [comment]
Yes, just clone and run, provided that you have the dependencies installed.

**Comment by Lokathor** [comment]
seems to work!
