### ISSUE TITLE
question: what is correct method of full-feature ReText installation on Microsoft Windows?

### ISSUE THREAD

**Issue by N0rbert** [retext-project/retext#477]
I want to use ReText on Microsoft Windows in full-feature mode.  
I strictly need full LaTeX math support which is provided by Chromium/WebEngine/WebKit engine and Markdown `math` extension.
I tried several ways without luck.

What I have tried already:

* Python for windows: 

     1. downloaded [Python 3.8 for windows](https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64.exe) and then installed it
    1. launched `cmd.exe`
    1. issued `pip install retext pyqtwebengine`
    1. launched ReText as `retext` from `cmd.exe`

* Anaconda for windows:

    1. downloaded [Anaconda 2019.10 with Python 3.7.4](https://repo.anaconda.com/archive/Anaconda3-2019.10-Windows-x86_64.exe) and then installed it
    1. opened windows start menu and navigated to *Anaconda3 (64-bit)* → *Anaconda Prompt (Anaconda3)*
    1. issued `pip install retext pyqtwebengine` 
    1. launch ReText as `retext` from this prompt

Then ReText opens, and I click on *Edit* →  *User WebEngine (Chromium) renderer*, enable live preview with <Ctrl>+<L> but it is empty:

![wkr](https://user-images.githubusercontent.com/309456/67144144-44769780-f27c-11e9-8a88-117833052039.png)

and shows strange message about *data* filetype/datatype:

> ![data](https://user-images.githubusercontent.com/309456/67144550-3165c680-f280-11e9-9525-8f7c06b47b12.png)

Did I missed something? Where am I doing wrong?
Could you please recommend tested method of full-feature ReText installation on Microsoft Windows?

**Comment by mitya57** [comment]
This is a regression caused by new Qt WebEngine. Please apply the fix from commit 60651631695c760a00d5f3a269e7454e948da77b.

I should make a new release but do not have time for it so far…

**Comment by N0rbert** [comment]
Thanks, after applying the patch it is now better!

But it does not want to render equations in single dollars `$ x = y^2 + z^2 $`:
![after](https://user-images.githubusercontent.com/309456/67145348-a689c980-f289-11e9-9d8c-7de4314cef80.png)

I'm not sure why this happens.
The Qt versions on the system are 5.13.1 for both PyQt5 and PyQtWebEngine if this matters.
Also note, that the test example from this comment works normally with Qt versions 5.9.3.

**Comment by mitya57** [comment]
As the [wiki](https://github.com/retext-project/retext/wiki/Math#math-syntax) says, `$...$` delimiter is disabled by default.

Please enable the (virtual) `mathjax` Markdown extension (in file header or in `markdown-extensions.txt`) to use them.

**Comment by N0rbert** [comment]
I'm very sorry for the disturbance, it seems that I am a bit forgetful this time.
Thank you for the hints and the great editor!

The indicated problem is solvable by installing previous version of PyQt5 5.9.2 ontop of Python 3.7.5 for which there is no separate PyQtWebEngine (it became separate in [5.12](https://pypi.org/project/PyQtWebEngine/#history)) :

```
pip install retext pyqt5==5.9.2
```

I have tested this method on 64-bit Windows 7, 8.1 and 10.

Notes: 
1. other usable versions of PyQt5 are 5.10 and 5.10.1.
2. bugs started to appear from PyQt5 5.11.2.
