### ISSUE TITLE
Support for mathjax v3.0

### ISSUE THREAD

**Issue by GFdevelop** [retext-project/retext#478]
```OS: Arch Linux x86_64```
On arch we have 2 mathjax packages: mathjax and mathjax2
```shell
/usr/share/mathjax # mathjax v3.0
/usr/share/mathjax2 # mathjax v2.7
```
To use mathjax offline I have created a folder `/usr/share/javascript` and then a symlink
```shell
sudo ln -s /usr/share/mathjax2 /usr/share/javascript/mathjax
```
this work for mathjax2 but not work for mathjax
```shell
sudo ln -s /usr/share/mathjax /usr/share/javascript/mathjax
```

(Why I have to create a symlink?!? Not all the users are root, we need an option in the user settings to set the mathjax path)

**Comment by mitya57** [comment]
A setting makes sense, definitely. I will look at it later.

**Comment by GFdevelop** [comment]
But for mathjax v3.0? Is there any plan?

**Comment by mitya57** [comment]
I will look at it too, that was already on my TODO list but no time so far.

**Comment by mitya57** [comment]
I have just added MathJax v3 support to the pymarkups master branch. It will be present in the next release, which will hopefully happen this month.

There is still no configuration option, but that's a different bug (feel free to file it if you want).
