### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by MestreLion** [retext-project/retext#482]
I'm aware this is a harmless warning from QT WebKit, but why not fix it? Most likely the cause is the app's icon, `retext.png`. If so, the fix should be simple, possibly a simple `pngcrush`: https://stackoverflow.com/questions/22745076

**Comment by mitya57** [comment]
I think I fixed this in qtwebkit/qtwebkit#798. What version of Qt WebKit are you using?

**Comment by MestreLion** [comment]
@mitya57 the one on Ubuntu 18.04 repository, not sure what package it is. But since that commit was created this year it will hit an Ubuntu LTS possibly only on 20.04. Anyway, I'm glad it's fixed upstream, so it will eventually arrive when I upgrade OS.

Meanwhile, regardless of this fix on WebKit, the images and assets used in ReText could be made not vulnerable to such bugs by stripping off any sRGB profiles in it (`pngcrush` does that, among other solutions)

**Comment by mitya57** [comment]
Ubuntu 18.04 has alpha2 so yes, it will be fixed when you upgrade to 20.04.

> Meanwhile, regardless of this fix on WebKit, the images and assets used in ReText could be made not vulnerable to such bugs by stripping off any sRGB profiles in it.

If you mean the logo, then it is never passed to WebKit. WebKit deals only with content coming from users. And there are no other assets in ReText.

As this warning can be ignored, I am closing the bug.
