### ISSUE TITLE
requirements.txt missing?

### ISSUE THREAD

**Issue by calcium** [retext-project/retext#483]
I git cloned the project.
And after a $ python3 setup.py install

I still needed to install the following
 pip3 install docutils
 pip3 install Markups
 pip3 install Markdown
 pip3 install PyQt5

before a "retext" would run

**Comment by mitya57** [comment]
The dependencies are specified in setup.py:
https://github.com/retext-project/retext/blob/bc87fd87004d5d0dc7581fe2bc6cc3685cc078a0/setup.py#L139-L148

However, setuptools does not install them when you run `setup.py install`. And `requirements.txt` won’t help here. You may want to use `pip3 install --user .` or even `pip3 install --user ReText`.
