### ISSUE TITLE
Numbered list not displayed correctly

### ISSUE THREAD

**Issue by patrickdung** [retext-project/retext#485]
Sample rst (also attached as test.rst in this ticket)

```
=============
List of items
=============

1. Point one

- eggs
- milk
- apples

2. Point two

   Test.

   *Test*

3. Point Three

   Test.
```

The numbered list is not in order (1. 2. 3.). It is displayed as (1. 1. 2.)

Gitit (that should use pandoc) and http://rst.ninjs.org could display the numbered list correctly.

Retext and Formiko (https://github.com/ondratu/formiko) could not display the numbered list in order.
[test.rst.txt](https://github.com/retext-project/retext/files/3908170/test.rst.txt)

**Comment by patrickdung** [comment]
David Goodger (Docutil's author) replies that bullet list should be indented to indicate that it is part of item 1. See
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#indentation

So it's not a bug of Retext.

**Comment by mitya57** [comment]
I see his response on https://sourceforge.net/p/docutils/bugs/382/, so closing this bug.

Note that docutils is the reference implementation of reStructuredText :)
