### ISSUE TITLE
Automatic file saving continuously saves even when there are no changes

### ISSUE THREAD

**Issue by colans** [retext-project/retext#486]
I left a Retext window open for several days without editing the open file.  Today, I happened to see my backup logs, and noticed that Retext is saving the file every minute even though there are no changes.  This has been going on for days so I'm seeming many file versions.

While my backup service does deduplication, it would be nice if Retext only auto-saved every minute if the file was actually edited, to prevent these types of services from being triggered.

So every minute:
  * *If the file was changed*
    * Save it.

Is this something that would be possible without too much effort?  Just wrapping an `if` around the auto-saving?

**Comment by mitya57** [comment]
This should be fixed in commit 40420a4f6fafc5ee, which was included in 7.1.0 (released in April 2020) and newer releases. Sorry for not replying earlier.

**Comment by colans** [comment]
Okay, thanks.  So this is related to #461.
