### ISSUE TITLE
Preview dont work when use webengine(chromium) renderer

### ISSUE THREAD

**Issue by UesugiErii** [retext-project/retext#488]
[log.txt](https://github.com/retext-project/retext/files/4035996/log.txt)

**Comment by mitya57** [comment]
This is fixed in the latest `master` and `retext-7.0` branches, please update or apply 60651631695c760a00d5f3a269e7454e948da77b manually.

**Comment by UesugiErii** [comment]
> This is fixed in the latest `master` and `retext-7.0` branches, please update or apply [6065163](https://github.com/retext-project/retext/commit/60651631695c760a00d5f3a269e7454e948da77b) manually.

Thank you for your reply.
No problems with manual installation(7.0.4).
Although the version on PyPI is also 7.0.4, it does not work.

**Comment by mitya57** [comment]
Yes, unfortunately the current stable release is broken. It will be fixed in the next one.

Note that the Qt WebEngine renderer is still experimental and there are other things that don't work (e.g. printing). The Qt WebKit renderer is more stable.
