### ISSUE TITLE
markdown extensions have no effect

### ISSUE THREAD

**Issue by dhebbeker** [retext-project/retext#490]
I am trying to work with checklists and read on the [wiki page](https://github.com/retext-project/retext/wiki/Markdown-extensions) that this can be added with an extension. I followed the instructions from https://github.com/retext-project/retext/issues/361#issuecomment-385069997 and https://github.com/retext-project/retext/issues/243#issuecomment-249485790 but with no success. 

Environment
==========

* ReText 7.0.4 (using PyMarkups 3.0.0)
* pip 18.1
* `python` 2.7.16
* `python3` 3.7.3
* extensions are installed in `~/.local/lib/python3.7/site-packages/`:
  * pymdown-extensions 6.2.1
  * markdown-checklist 0.4.1
* `~/.config/markdown-extensions.txt`:   
    ```
    markdown_checklist.extension
    pymdownx.tasklist
    ```
* `~/.config/ReText project/ReText.conf`:   
    ```
    [General]
    font=DejaVu Sans
    fontSize=12
    livePreviewByDefault=true
    spellCheck=true
    spellCheckLocale=en_US
    tabWidth=2
    ```

Steps to reproduce
===============

1. Write in editor and save as `*.md` file:
    ```
    <!-- Required extensions: markdown_checklist.extension -->
    
    - [ ] foo
    - [x] bar
    ```
2. Enable live preview and check.

Expected result
============

![should be like this](https://user-images.githubusercontent.com/1381584/39381046-63456608-4a69-11e8-9ca1-8508e395ccce.png)

Actual result
==========

![actual result](https://user-images.githubusercontent.com/1594340/73431150-04758500-4340-11ea-9cca-3a73907f16ce.png)

when started from command line interface I get the following message:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Using configuration file: ~/.config/ReText project/ReText.conf
```

----

Is there anything I can do to analyse or fix my setup?

**Comment by mitya57** [comment]
Hi!

Please enable the WebKit (or WebEngine) renderer from the Edit menu. The default renderer doesn't support `<input type="checkbox">` unfortunately.

**Comment by dhebbeker** [comment]
Thanks! That solved my problem.

What are the drawbacks of the WebEngine renderer?

**Comment by mitya57** [comment]
It is very unstable, may crash depending on platform and version. Also it does not properly support printing, only PDF export works.

**Comment by dhebbeker** [comment]
Thank you for the clarification!
