### ISSUE TITLE
menu can not be browsed with keys

### ISSUE THREAD

**Issue by dhebbeker** [retext-project/retext#491]
I am used to be able to use <kbd>ALT</kbd> to browse the application menu. This does not seem to work.

Shortcuts like <kbd>CTRL</kbd> + <kbd>S</kbd> do work as expected. Being able to browse the menu with the <kbd>ALT</kbd> is quite useful, for example to browse through the recently opened files.

Environment
==========

* ReText 7.0.4 (using PyMarkups 3.0.0)
* pip 18.1
* `python` 2.7.16
* `python3` 3.7.3
* extensions are installed in `~/.local/lib/python3.7/site-packages/`:
  * pymdown-extensions 6.2.1
  * markdown-checklist 0.4.1
* `~/.config/markdown-extensions.txt`:   
    ```
    markdown_checklist.extension
    pymdownx.tasklist
    ```
* `~/.config/ReText project/ReText.conf`:   
    ```
    [General]
    font=DejaVu Sans
    fontSize=12
    livePreviewByDefault=true
    spellCheck=true
    spellCheckLocale=en_US
    tabWidth=2
    ```

Steps to reproduce
===============

- press <kbd>ALT</kbd>
- press <kbd>ALT</kbd> + <kbd>F</kbd>

Expected result
============

- "File" menu item is expanded

Actual result
==========

- no visible reaction

when started from command line interface I get the following message:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Using configuration file: ~/.config/ReText project/ReText.conf
```
----

Is there anything I can do to analyse or fix my setup?

**Comment by JimH44** [comment]
I also like to be able to use keyboard shortcuts, as they are much quicker than dragging the mouse pointer around, and there is less risk of clicking on the adjacent thing by mistake, so I endorse this request.
I have also started a spreadsheet that compares markdown editors for Linux, at
[Markdown Editor Shortcomings](https://docs.google.com/spreadsheets/d/1Qe6IYOv_wEyc407FilYZFLx4qtI4XPdnuyliqDgU9SU/edit?usp=sharing)
Anyone with that link can view and comment, so I invite comments. There may be things that I like in the program, but I couldn't find them.

**Comment by tbird1965** [comment]
In version 7.1.0 (at least on Windows), the <kbd>Alt</kbd> key highlights the File tab, but does not expand it.  If you hit the <kbd>Spacebar</kbd> or <kbd>↓</kbd>, it will expand.

**Comment by dhebbeker** [comment]
Thanks, I gave it a shot using the environment of the original post. Although the File tab is not highlighted, it is possible to expand the menu using the keys you advertised.

**Comment by dhebbeker** [comment]
I suspect this may have to do something how Qt works with my environment (using Debian Buster). I checked VLC media player. The behaviour there is similar. But they have highlighted the keys one may press to expand the menu items. This would be for example to underline the "F" of the File tab. Maybe [this hint](https://www.qtcentre.org/threads/59228-Select-first-QMenu-from-QMenuBar-using-ALT-key?s=c1371dd9f31f31eb8371a18a04cf6f44&p=263144#post263144) can be helpful to make using the keys for the menu more user friendly?
