### ISSUE TITLE
wrong link in starter

### ISSUE THREAD

**Issue by freddii** [retext-project/retext#499]
i was installing it in xubuntu with:
pip3 install ReText
But the starter in my menu is not working:
it runs: 
ReText-7.0.4.data/scripts/retext %F

for me this one in starter worked:
python3 /home/freddii/.local/bin/retext %F

**Comment by mitya57** [comment]
This is a duplicate of #452 and #497. It is fixed in git (27a2745e3ae65bf8) and the fix will be available in the next release. Please use pip's `--no-cache-dir` option as a temporary workaround.
