### ISSUE TITLE
I miss a find & replace action

### ISSUE THREAD

**Issue by andrewufrank** [retext-project/retext#505]
I like Retext a lot, especially to write blog entries. I need occasionally to replace a bunch of characters and can easily find what I have to replace - but how to replace it and then go to the next. Most editors have such a featuere (often ^F and ^H). 
Is there an efficient way to replace text and I have not yet seen it? I use 6.0.2 on Linux Debian. If not, could this be added? 

Thank you!
andrew

**Comment by mitya57** [comment]
There is such feature, but it has been added in ReText 7.0 (released in February 2017). ReText 6.0 is a very old version, the latest Debian stable release (Buster) has ReText 7.0.4.

**Comment by andrewufrank** [comment]
thank you - I have not moved up with debian before finishing a coding project; sorry for not checking on a newer installation.
