### ISSUE TITLE
Special character render weird

### ISSUE THREAD

**Issue by Qik000** [retext-project/retext#506]
I am Polish, and we use ł ń ą ś ć ó ę and theese characters render weird, they stand out. Especially in an h1

**Comment by mitya57** [comment]
Cześć!

Most probably it is a font problem. For me it works fine, see the screenshot (I added letters without diacritics for comparison):

![Screenshot](https://user-images.githubusercontent.com/1381584/82673914-34c49480-9c4b-11ea-8681-0b28a66d0b02.png)

Please try opening Edit → Change preview font, and select a different font (for me it is DejaVu Sans Book, but many others should work fine).

**Comment by Qik000** [comment]
> Cześć!
> 
> Most probably it is a font problem. For me it works fine, see the screenshot (I added letters without diacritics for comparison):
> 
> ![Screenshot](https://user-images.githubusercontent.com/1381584/82673914-34c49480-9c4b-11ea-8681-0b28a66d0b02.png)
> 
> Please try opening Edit → Change preview font, and select a different font (for me it is DejaVu Sans Book, but many others should work fine).

Thanks !, that was it. The dont was funky. The default on selected after install should be a one thats compatible with special characters as i imagine it causes the same problems in other languages
