### ISSUE TITLE
Stuff written `like this` is very small in WebKit render mode

### ISSUE THREAD

**Issue by Qik000** [retext-project/retext#508]
When you write stuff inside `` its very small in WebKit mode. IS there a way to fix it ?

**Comment by mitya57** [comment]
Hi!

You can change this with a small piece of CSS:
```css
code { font-size: 120%; }
```

There are several ways to get that CSS applied:

- Either add the following directly to your Markdown file:
  ```html
  <style>
  code { font-size: 120%; }
  </style>
  ```

- For a file named `foo.md`, create a file named `foo.css` and add that text there.

- Create a global stylesheet file somewhere, open the Preferences dialog, in Interface → Stylesheet file specify a path to it.
