### ISSUE TITLE
Search/Replace bar takes up focus, escape key should dismiss it

### ISSUE THREAD

**Issue by NucleaPeon** [retext-project/retext#509]
I use Ctrl+F to bring up the find / replace bar to search for terms in my document.
Normally in other text editors I use, pressing the escape key will dismiss the find modal/bar but here it doesn't do anything. I just found out that pressing Ctrl+F again would dismiss the find prompt, but it seems unintuitive to me and I think Escape should dismiss it as well.

Thanks.

**Comment by mitya57** [comment]
This was already fixed in f3fe2330430eaa99! Please test the latest release (7.1.0).

**Comment by NucleaPeon** [comment]
Thanks for the reply. Retext 7.1.0 is not yet available on gentoo, even with a sync done right this moment. I get that you are likely not the maintainer for it. I will start using source if it is not updated soon.

Thank you.
