### ISSUE TITLE
Simple word count

### ISSUE THREAD

**Issue by internationils** [retext-project/retext#514]
When writing blog posts or web text, a word count is important to know how long the article is. A simple word count would be great to have (even if piped through 'wc' and shown in a dialog, or something similarly simple. Preferred would be an option to have it in a toolbar.

**Comment by mitya57** [comment]
This feature is already available. See Preferences → Editor → Show document stats.

It will display a line in form “X w[ords], Y a[lphanumeric characters], Z c[haracters]”.
