### ISSUE TITLE
Crashing after choosing WebEngine(Chromium) in edit menu on Ubuntu 16.04

### ISSUE THREAD

**Issue by edyatl** [retext-project/retext#515]
I'm trying to use WebEngine in retext and getting crash with output bellow:
```
LaunchProcess: failed to execvp:
/home/edyatl/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec/QtWebEngineProcess
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/edyatl/.local/lib/python3.6/site-packages/ReText/converterprocess.py", line 63, in _converter_process_func
    job = receiveObject(conn_child)
  File "/home/edyatl/.local/lib/python3.6/site-packages/ReText/converterprocess.py", line 32, in receiveObject
    sizeBuf = recvall(sock, 4)
  File "/home/edyatl/.local/lib/python3.6/site-packages/ReText/converterprocess.py", line 25, in recvall
    raise EOFError('Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?')
EOFError: Received 0 bytes from socket while more bytes were expected. Did the sender process exit unexpectedly?
Ловушка трассировки/останова (сделан дамп памяти)
```
OS: Ubuntu 16.04 xenial
Kernel: x86_64 Linux 4.15.0-101-generic
Shell: bash 4.3.48
DE: Unity 7.4.5
WM: Compiz
WM Theme: Ambiance
GPU: Mesa DRI Intel(R) Sandybridge Mobile

Python installed:
python2.7  
python3.5  - system default
python3.6 - from ppa

>python3.6 -m pip show retext
Name: ReText
Version: 7.1.0
Location: /home/edyatl/.local/lib/python3.6/site-packages

>python3.6 -m pip list
Package                       Version
aiohttp                       3.5.4
aiohttp-socks                 0.2.2
aiorpcX                       0.18.4
apturl                        0.5.2
async-timeout                 3.0.1
attrs                         18.2.0
beautifulsoup4                4.4.1
blinker                       1.3
Brlapi                        0.6.4
certifi                       2018.11.29
chardet                       3.0.4
checkbox-support              0.22
classicmenu-indicator         0.10.1
command-not-found             0.3
cryptography                  1.2.3
cycler                        0.9.0
decorator                     4.0.6
defer                         1.0.6
dnspython                     1.16.0
docutils                      0.16
ecdsa                         0.13.2
Electrum                      3.3.8
feedparser                    5.1.3
guacamole                     0.9.2
html5lib                      0.999
httplib2                      0.9.1
idna                          2.8
idna-ssl                      1.1.0
importlib-metadata            1.6.1
jdcal                         1.0
Jinja2                        2.8
jsonrpclib-pelix              0.4.0
language-selector             0.1
louis                         2.6.4
lxml                          3.5.0
Mako                          1.0.3
Markdown                      3.2.2
markdown-checklist            0.4.3
Markups                       3.0.0
MarkupSafe                    0.23
matplotlib                    1.5.1
multidict                     4.5.2
numexpr                       2.4.3
numpy                         1.11.0
oauthlib                      1.0.3
onboard                       1.2.0
openpyxl                      2.3.0
padme                         1.1.1
pandas                        0.17.1
pexpect                       4.0.1
Pillow                        3.1.2
pip                           20.1.1
plainbox                      0.25
prompt-toolkit                0.57
protobuf                      3.8.0
ptyprocess                    0.5
py                            1.4.31
pyaes                         1.6.1
pyasn1                        0.1.9
pycryptodomex                 3.7.3
pycups                        1.9.73
pycurl                        7.43.0
pyenchant                     1.6.6
Pygments                      2.6.1
pygobject                     3.20.0
pyinotify                     0.9.6
PyJWT                         1.3.0
pymdown-extensions            7.1
pyparsing                     2.0.3
PyQt5                         5.15.0
PyQt5-sip                     12.8.0
PyQtWebEngine                 5.15.0
pytest                        2.8.7
python-apt                    1.1.0b1+ubuntu0.16.4.9
python-dateutil               2.4.2
python-debian                 0.1.27
python-markdown-math          0.6
python-systemd                231
pytz                          2014.10
pyxdg                         0.25
QDarkStyle                    2.5.4
qrcode                        6.1
reportlab                     3.3.0
requests                      2.9.1
ReText                        7.1.0
scipy                         0.17.0
sessioninstaller              0.0.0
setuptools                    41.0.1
six                           1.12.0
system-service                0.3
tables                        3.2.2
typing-extensions             3.7.2
ubuntu-drivers-common         0.0.0
ufw                           0.35
unattended-upgrades           0.1
unity-scope-calculator        0.1
unity-scope-chromiumbookmarks 0.1
unity-scope-colourlovers      0.1
unity-scope-devhelp           0.1
unity-scope-firefoxbookmarks  0.1
unity-scope-gdrive            0.7
unity-scope-manpages          0.1
unity-scope-openclipart       0.1
unity-scope-texdoc            0.1
unity-scope-tomboy            0.1
unity-scope-virtualbox        0.1
unity-scope-yelp              0.1
unity-scope-zotero            0.1
unity-tweak-tool              0.0.7
urllib3                       1.13.1
usb-creator                   0.3.0
wcwidth                       0.1.6
webkit                        1.1.0
wheel                         0.29.0
xdiagnose                     3.8.4.1
xkit                          0.0.0
xlrd                          0.9.4
XlsxWriter                    0.7.3
yarl                          1.3.0
zipp                          3.1.0

**Comment by mitya57** [comment]
> LaunchProcess: failed to execvp:
> /home/edyatl/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec/QtWebEngineProcess

Can you try to launch that process manually and see what happens?

My guess is that some libraries on Ubuntu 16.04 are too old and Qt WebEngine will not work with them. Or maybe some packages are missing.

**Comment by edyatl** [comment]
It was a matter of execution rigths of file QtWebEngineProcess
`sudo chmod 755 ~/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec/QtWebEngineProcess`
solved the problem
