### ISSUE TITLE
Some minor issues esp. for rtl texts

### ISSUE THREAD

**Issue by hadi-f90** [retext-project/retext#526]
As you told in last issue post that you intend to extend the support for _right-to-left languages_, and *bidirectional* as well as _mixed directional_ texts, here is a series of new issues I came across regarding right-to-left and mixed English-Persian texts:

- [ ] For right-to-left languages like Persian current line highlighter, highlights texts form left side like this:

![image](https://user-images.githubusercontent.com/62212402/91384092-0acecf80-e843-11ea-8f5a-05f4be08e4e4.png)

- [ ] The "Formatting" and "Symbols" buttons are totally disabled:

![image](https://user-images.githubusercontent.com/62212402/91384218-436ea900-e843-11ea-8e67-4b7510e913a4.png)

- [ ] WebEngine does not show the in-text images properly. Although it provides a far more better CSS formatting than the other text rendering engine, it is still faulty. For example, the "Hint" section should be an expandable section not expanded one.
![image](https://user-images.githubusercontent.com/62212402/91385991-479cc580-e847-11ea-9e7f-bcd627340961.png)

- [ ] While the other HTML engine loads images properly, it almost does not support CSS formatting at all.
![image](https://user-images.githubusercontent.com/62212402/91385930-2936ca00-e847-11ea-830d-ad4f07b861a0.png)

- [ ] Synchronized scrolling for markdown does not work.

PS: The last two photos are taken from the same part of the same document.

**Comment by mitya57** [comment]
I will look at these issues later when I have more time. Now I just want to say thanks for your translation on Transifex :+1:

**Comment by mitya57** [comment]
I am terribly sorry for the delay with replying. This week I have finally found some time to look at ReText issues.

> The "Formatting" and "Symbols" buttons are totally disabled.

They are only enabled for Markdown documents, not for reStructuredText. The “Symbols” box inserts HTML symbols (`&hellip;`, `&times;` and similar). reStructuredText does not support them. In fact, I prefer to use the [Compose key](https://en.wikipedia.org/wiki/Compose_key) to do the same thing, it works with any markup (and I think there is something equivalent for Windows). The “Formatting” box is also only implemented for Markdown.

> WebEngine does not show the in-text images properly.

This looks like #533 which I fixed a few days ago. Can you please test the version from master branch?

> While the other HTML engine loads images properly, it almost does not support CSS formatting at all.

Right, the other HTML engine is based on QTextEdit, you can see what it supports [here](https://doc.qt.io/qt-5/richtext-html-subset.html). If you need rich CSS then WebEngine is the way to go.

> Synchronized scrolling for markdown does not work.

Please make sure that:

- You have “Enable synchronized scrolling for Markdown” checked in settings.
- You are using the WebEngine renderer.
- Your document is actually Markdown, not reStructuredText.

If it still does not work, please let me know.

Now I will look at the remaining issue you reported (the first one, regarding selection).

**Comment by mitya57** [comment]
Regarding the selection, since #523 (available in master) you can set highlight mode to “Wrapped line” in settings. Unlike the “Cursor line”, it seems to work fine with right-to-left texts. Can you try that while I have not fixed the “Cursor line”?

**Comment by mitya57** [comment]
“Cursor line” should be a bit less buggy now, but I have not found a way to make it highlight the whole line for RTL texts. “Wrapped line” still behaves better.

If there are any remaining issues please let me know.
