### ISSUE TITLE
How execute the APP?

### ISSUE THREAD

**Issue by damianlluch** [retext-project/retext#534]
Hi guys, I found this repository by comments. I installed with PIP, but I don't know how run the app.

I use, Ubuntu 20

thanks!

**Comment by mitya57** [comment]
Hi!

Installation via `pip` should have added ReText to the list of applications in GNOME. If that didn't happen, try running `retext` command (in Terminal or in <kbd>Alt</kbd>+<kbd>F2</kbd> menu).

Also you can just install `retext` package from Ubuntu repository (`apt install retext`), that would provide a more native experience.
