### ISSUE TITLE
Can ReText support the mermaid?

### ISSUE THREAD

**Issue by tianjun9** [retext-project/retext#535]
Can ReText support the mermaid?

**Comment by mitya57** [comment]
Yes, it can!

I found an extension for it — https://pypi.org/project/md-mermaid/ by @oruelle.

So you need to:

- Install it using `python3 -m pip install md-mermaid`.
- Enable WebKit or WebEngine renderer from ReText's Edit menu.
- Enable the extension via `markdown-extensions.txt` file or via `Required extensions` comment. See the [wiki] for details.
- Include the script manually in your document.

Result is:
![Screenshot](https://user-images.githubusercontent.com/1381584/102811352-45520e80-43d6-11eb-9314-6e09d5565247.png)

[wiki]: https://github.com/retext-project/retext/wiki/Markdown-extensions
