### ISSUE TITLE
Load any file in reST mode

### ISSUE THREAD

**Issue by mattrust** [retext-project/retext#537]
The AROS project uses reST file for its documentation (https://github.com/aros-development-team/documentation).
File endings are localized (*.en, *.de, *.ru etc.)
Problem is that retext 7.1.0 opens those files in markdown mode. Currently I'm temporary renaming those files to *.rst.
I'm suggesting to add a button which treats any text file as reST file.

**Comment by mitya57** [comment]
Hi!
Did you try Edit → Default markup → reStructuredText?

**Comment by mattrust** [comment]
Oh great. I've overlooked that.
