### ISSUE TITLE
Gitlab-flavoured markdown

### ISSUE THREAD

**Issue by lindnemi** [retext-project/retext#538]
I just wanted to start using Retext with gitlab-flavoured markdown. After trying for almost an hour to get `markdown_katex` to work without getting anywhere I found this issue #510. So there seems to be a solution but I didn't get it to work either. Could you clarify again what steps are necessary to get gitlab-flavoured markdown working? Inserting `
` at the top of the document didn't work for me. That would be great, thanks.

**Comment by lindnemi** [comment]
After
```python3 -m pip install --upgrade --user https://github.com/mitya57/python-markdown-math/archive/master.zip```
and getting version 0.8, all blocks within ```math fences and `$ delimiters disappeared in the rendered output

**Comment by mitya57** [comment]
Hi!

Can you please make sure that you have one of “Edit → Use WebKit renderer” or “Edit → Use WebEngine (Chromium) renderer” options enabled?

**Comment by lindnemi** [comment]
Thanks a lot, that did the trick :) Math code displays correctly now.
