### ISSUE TITLE
Asking for help: why Retext does not render math equations?

### ISSUE THREAD

**Issue by liwenbo92** [retext-project/retext#541]
Sorry I am new to ReText and want to ask a simple question. I installed ReText on my Ubuntu 20.04 but I cannot make the math equations work. Here I attach the screen shot I got
![Screenshot from 2021-01-25 13-15-38](https://user-images.githubusercontent.com/15386956/105747985-7d85c900-5f0f-11eb-975e-0f77762ae83d.png)

MathJax has been installed at /usr/share/javascript/mathjax. I checked the [wiki page](https://github.com/retext-project/retext/wiki/Markdown-extensions), but still have no clue why the math equations are not displayed correctly. I also tried to export the md file into pdf or html files. I see the math equations in the exported html file correctly, but not in the pdf file.

Could anyone help me on this? Thank you very much.

**Comment by mitya57** [comment]
Hi!

You needed to check [another wiki page](https://github.com/retext-project/retext/wiki/Math).

I guess you have “Edit→ Use WebKit renderer” unchecked. Enabling it should help.

**Comment by liwenbo92** [comment]
You are right. Once I enabled that option, everything works perfectly. 

Thank you very much. I have no idea why I overlooked that part of the wiki page.
