### ISSUE TITLE
Disable table autocomplete inside equations

### ISSUE THREAD

**Issue by michaelerule** [retext-project/retext#542]
I'm writing up some math, and the editor mistakes the vertical bar for table markdown, and  fills in columns/row separators when one presses return. To reproduce, try typing `$$\Pr(a | b)=$$`, and then press enter to create a new line after the `=` character. 

I suppose the way to fix this would be to detect when the editor is inside an equation environment, or to narrow down the patterns that trigger the markdown-table autocomplete?

**Comment by mitya57** [comment]
You can uncheck “Edit → Table editing mode”. In fact it's disabled by default.

**Comment by michaelerule** [comment]
noted; thanks! apologies for the spam( :
