### ISSUE TITLE
Retain scroll position when updating

### ISSUE THREAD

**Issue by gkatev** [retext-project/retext#544]
Hi,
I use retext as a markdown renderer (preview mode), and use an external editor for the source. Every time I save the document(on the external editor), retext updates the preview. However, it also scrolls the view away from where it was (sometimes to the top, others to bottom, or to the middle; not sure).

Is it trying and failing to detect where the change was made? Or is the position lost when updating the view?
An option to keep the position exactly the same sounds like it would be a simple and good enough solution.
Is this currently possible?

**Comment by mitya57** [comment]
Hi!

Synchronized scrolling is already implemented. Please make sure that:

- In Preferences, you have “Enable synchronized scrolling for Markdown” checked.
- In Edit menu, either "Enable WebKit renderer” or “Enable WebEngine (Chromium) renderer” is checked.

**Comment by gkatev** [comment]
As far as I understand synchronized scrolling only works with the integrated editor (?).
Instead I'm trying to use a separate/external editor.

I tried synchronized scrolling and while it worked with the internal editor, the problem persisted with the external one.

I also have a suspicion the SVGs in my MD come into play somehow, but haven't investigated fully yet.

**Comment by mitya57** [comment]
> Instead I'm trying to use a separate/external editor.

So you are using ReText as a previewer only? It is a very interesting use case that I never thought of!

But ReText's synchronized scrolling implementation uses a [quite complicated algorithm][1] that tries to make sure the line currently being edited is visible. When you modify a document externally, the (internal) editor cursor gets reset to the first line, so the previewer should also scroll to top accordingly.

And of course ReText does not know anything about the current position in external editor. So while your use case is valid, it's quite exotic and it will be very difficult to support it properly.

[1]: https://github.com/retext-project/retext/blob/master/ReText/syncscroll.py

**Comment by gkatev** [comment]
I'm surprised this seems as a rare use-case!

Not necessarily speaking in the context of synchronized scrolling; I actually don't use it. Without synchronized scrolling I can indeed witness the editor scrolling to the top, but the preview remains in the same spot.

And I'm not looking to use synchronized scrolling with an external editor (if one wanted to track changes made by an external editor, comparing the cached file with the new version could be an approach(?)), but rather have the scroll not jump around when the document is detected to have changed.

Now as I'm testing again I notice that with a simple test file and without synchronized scrolling the behavior is the one that I'm seeking here(scroll remains in the same position when the file is modified&saved externally). But I have another MD which scrolls to some arbitrary point when the file is changed externally (not to the top).

I will produce two minimal MDs to illustrate the effect I'm seeing.

**Comment by mitya57** [comment]
> I'm surprised this seems as a rare use-case!

I have quite a lot feedback here (e.g. this issue is 544th), and I have never heard of this use case :)

> Now as I'm testing again I notice that with a simple test file and without synchronized scrolling the behavior is the one that I'm seeking here(scroll remains in the same position when the file is modified&saved externally).

That sounds like the desired behavior, indeed.

> I will produce two minimal MDs to illustrate the effect I'm seeing.

Ok, waiting then and let's see if I can reproduce that issue.

**Comment by gkatev** [comment]
So, producing a minimal MD wasn't simple after all. Things like removing a sentence, a graph, or a character would cause the problem to disappear. Instead, here is the full document (sorry that it's redacted :) it's some work stuff..).  I've generally noticed it starts appearing as my document gets longer.

[MD.zip](https://github.com/retext-project/retext/files/5900502/MD.zip)

Open the MD (with the SVG in the same directory), with Live Preview, scroll the Preview somewhere to the middle, and change something in the editor (internal or external) (tested without synchronized scrolling). The preview jumps around towards the end.

Thanks, let me know if the problem exists itself in your environment as well.

**Comment by mitya57** [comment]
I am sorry for the delayed response.

I was able to reproduce your issue, and for me it happens even with ReText's own `changelog.md` file (which does not contain any images).

Commit b473f6b5e2b810590ab90f908a5f302f584370d7 should improve it. With this fix the preview box will jump to bottom first, but after 50ms it will return to the correct position. Can you please test it?

Also if you use WebKit or WebEngine renderer (which you can enable from the Edit menu), there should be no such bug and there will be no jumps.

**Comment by gkatev** [comment]
Thanks for looking into this,
Indeed, on the *scroll-problem.md* I uploaded, I can see the scrollbar jump around but eventually return to the same position.

However, on another MD I have, it does not work. (not sure if it jumps at all, hard to see)
Might the 50ms delay not be enough? Is the delay dependent on the render time or something of the sort?
When the problem occurs, I think I've always observed the view moving upwards, if that hints towards something.

**Comment by mitya57** [comment]
> Might the 50ms delay not be enough? Is the delay dependent on the render time or something of the sort?

Yes, the scrollbar configuration is changing three or more times during rendering. Can you try changing 50 ms to 100 or another value in this block?

https://github.com/retext-project/retext/blob/b473f6b5e2b810590ab90f908a5f302f584370d7/ReText/tab.py#L264-L267

I thought about using signals to track when the configration changes, but the jump is still visible for me, and I still need to set some timeout after which the position should not be changed, because the user may have resized the window or otherwise manually changed the scroll position.

> When the problem occurs, I think I've always observed the view moving upwards

I have not observed this behavior yet. Maybe you can try to create a new (obfuscated) test file?

**Comment by gkatev** [comment]
Yes indeed, changing the timer to 100ms fixes the problem for the second MD as well. I'm not sure how this would be fixed portably. As far as I understand, the longer the markdown takes to render the higher the chance the timer will not be enough.

One approach that springs to mind: Blank out the view (is this possible?) while it's rendering, and re-enable it at the correct position once it's done (detectable via some signal or similar?). (with appropriate (~500ms?) timeout in case something goes wrong).
This could be made to only be activated when an extended rendering time for a specific document is detected. But then again, for markdowns that render very quickly, blanking out the view for couple milliseconds shouldn't be a problem(?).

**Comment by mitya57** [comment]
Thanks for the feedback! Can you please try the latest commit? Actually I tried to use the signal like I wrote in my last comment, and it seems to work better than the old approach.

**Comment by gkatev** [comment]
As far as I can tell it works beautifully!
Sometimes the view doesn't even jump around, and when it does it returns to the original position, in a humanly-insignificant time frame.

**Comment by mitya57** [comment]
Hooray! Are there any remaining things to fix, or we can close this issue?

**Comment by gkatev** [comment]
All good on my end!
