### ISSUE TITLE
If a file is already open, focus on the window

### ISSUE THREAD

**Issue by arteteco** [retext-project/retext#550]
Hello everyone,
right now if a file is already open in ReText and I open it again, another window is opened. This can lead to conflict and data loss, while a more standard way to go would be bring forward the window where that file is currently being edited.

Hope I made myself clear enough, all the best!

**Comment by mitya57** [comment]
Opening files in existing window is already the default behavior since ReText 7.1.0 (see #476). What version and what OS do you use?

**Comment by arteteco** [comment]
@mitya57 You are right, I'm on 7.0.4, Debian 10, sorry for the useless issue, closing!
