### ISSUE TITLE
Synchronized scholling not working

### ISSUE THREAD

**Issue by tridral** [retext-project/retext#553]
I've installed *ReText v7.1* on *Ubuntu 20.04.2 LTS.*

I used 

```
  sudo apt install retext
```

To carry out the installation

Live preview works but synchronized scrolling doesn't.
Is there something else I need to do so that synchronized scrolling works.

Many thanks for any help

**Comment by mitya57** [comment]
Hi!

Please make sure that:

- You have “Edit → Use WebKit renderer” enabled.
- You have “Edit → Preferences → Enable synchronized scrolling for Markdown” enabled.
- Your document is Markdown (not reStructuredText). Support for reStructuredText was added in a newer version.

**Comment by tridral** [comment]
Dear Dmitry,

Thank you very much indeed for your swift reply.

I've made the changes as you advise and reText now has synchronized
scrolling

best regards,

'ö-Dzin




འོད་འཛིན་དྲི་བྲལ
'ö-Dzin Tridral
[image: https://]about.me/tridral
<https://about.me/tridral?promo=email_sig&utm_source=email_sig&utm_medium=email_sig&utm_campaign=external_links>
☸
*Drala Jong Appeal - creating a Buddhist retreat centre in Wales:
https://www.drala-jong.org/ <https://www.drala-jong.org/> *☸

☸ Achos pan ddaw y Pedwar Marchog i ofyn a roist ti o dy gyfan - fydd gen
ti ddim esgus - Meinir Gwilym ☸
