### ISSUE TITLE
ReText 7.2.1 on Windows: Edit->Change editor font->not saving font style "Bold" for next ReText launch

### ISSUE THREAD

**Issue by POTSandSTOP** [retext-project/retext#555]
Changing from font style "Regular" to "Bold" works while editing, but when I exit ReText and start it up again, it goes back to "Regular".

The "Bold" font style adds that little extra bit of readability to these aging eyes. :D

I realize Windows is not officially supported but I thought I would try asking anyway.

**Comment by mitya57** [comment]
Thanks for your report! I will try to fix it when I have time.

**Comment by mitya57** [comment]
This is now fixed in master branch. Any feedback is welcome, if you can test it.
