### ISSUE TITLE
Segfault when WebKit is installed

### ISSUE THREAD

**Issue by tzovas** [retext-project/retext#557]
Probably not an issue of retext but of pyqt; I thought of posting it here for others that might get the same issue.

After installing the latest version (7.2.1) I got a segmentation fault. After digging around I located that it happens inside the `ReText/__main__.py` file in line 64, when calling `app = QApplication(sys.argv)`. I figure out that this probably is not a problem of retext but of my system (I run Ubuntu 18.04 btw). After removing some packages it worked! 

Among the packages removed is `python3-pyqt5.qtwebkit`which appears to be the problematic one. If I re-install the package the segmentation fault reappears. So I removed it permanently. The downside is that I cannot use the synchronized scroll of retext...

**Comment by mitya57** [comment]
I guess this can be caused by incompatibility between PyQt5 from PyPI and PyQt5.QtWebKit from Ubuntu 18.04 repositories.

You can try running `pip3 install --user PyQtWebEngine` — this is like WebKit, so you will also have synchronized scroll and other features like MathJax support.

**Comment by tzovas** [comment]
This indeed worked nice! Thanks.
