### ISSUE TITLE
Не масштабируется картинка по директиве :scale:

### ISSUE THREAD

**Issue by vicjan89** [retext-project/retext#559]
При любых значениях :scale: размер картинки не меняется

**Comment by mitya57** [comment]
Включена ли у вас опция «Использовать движок WebKit/WebEngine» (в меню «Правка»)?

У меня при включённом WebKit всё работает:
![Скриншот](https://user-images.githubusercontent.com/1381584/118699892-b88f6d80-b81a-11eb-9bf6-f6fecf62b361.png)

Стандартный движок Qt поддерживает только подмножество CSS, которое описано [здесь](https://doc.qt.io/qt-5/richtext-html-subset.html), и CSS-свойств `width` и `height` там нет.

**Comment by vicjan89** [comment]
Была отключена. Включил - всё масштабируется! Спасибо!
