### ISSUE TITLE
Неиспользование WebEngine при печати

### ISSUE THREAD

**Issue by vicjan89** [retext-project/retext#564]
Изображение предварительного просмотра при печати выглядит так как при просмотре с отключенным WebEngine.
![изображение](https://user-images.githubusercontent.com/64374842/119719034-f91d6580-be70-11eb-93c5-d0ff498c1aa1.png)
Возможно у меня что-то не установлено? 
Как получить при печати качество аналогичное просмотру с использованием WebEngine?
Заранее спасибо.

**Comment by mitya57** [comment]
Вот есть баг про поддержку просмотра печати в Qt WebEngine. Несколько раз обещали реализовать в разных версиях, но пока не сделали: https://bugreports.qt.io/browse/QTBUG-57982.

**Comment by vicjan89** [comment]
Понял. Спасибо.
