### ISSUE TITLE
show embedded video

### ISSUE THREAD

**Issue by matkoniecz** [retext-project/retext#566]
In many places (for example github) embedding both video and images is possible.

Is it either expected to work in retext or feasible to add?

Or is it "massive amount of work needed in upstream project, feel free to make pull requests"

Either way thanks for this program!

I tried https://github.com/retext-project/retext/search?q=video&type=issues https://github.com/retext-project/retext/search?q=mp4&type=issues https://github.com/retext-project/retext/search?q=media&type=issues

**Comment by mitya57** [comment]
Hi! It works for me. You just need to:

1. Enable WebKit or WebEngine renderer from the Edit menu (both renderers show video for me).
2. Use `<video>` tag for Markdown or `.. image::` directive for reStructuredText (works with docutils ≥ 0.17).
If something does not work, please give more detail.

![Screenshot](https://user-images.githubusercontent.com/1381584/126214401-4c67ff88-efe7-44ad-9a94-c2adab048305.png)

**Comment by matkoniecz** [comment]
oh, I was trying the same syntax as with the image

I will close and reopen if it will not work
