### ISSUE TITLE
Mermaid extension not working for versions >8.13.0

### ISSUE THREAD

**Issue by dpdoughe** [retext-project/retext#570]
Following the instruction in issue https://github.com/retext-project/retext/issues/535, I was able to get Mermaid diagrams to render nicely in retext ver 7.1.0-1. 

The diagram creation works when including the script with e.g.
```
<script src="https://unpkg.com/mermaid@8.13.0/dist/mermaid.min.js"></script>
```
but stops working for any versions after 8.13.0. For example, the diagram is no longer rendered if I use
```
<script src="https://unpkg.com/mermaid@8.13.1/dist/mermaid.min.js"></script>
```

Is there a way to know if this is a problem in retext or a problem with the Python extension md-mermaid ?  

Thank you!

**Comment by mitya57** [comment]
The latest version in master removed support for Qt WebKit, leaving only Qt WebEngine, so I'm closing this bug.
