### ISSUE TITLE
Mathjax not working in openSUSE

### ISSUE THREAD

**Issue by Oisangui** [retext-project/retext#579]
I installed retext and mathjax, added mathjax to the extensions list in the preferences dialog but this happens:
![image](https://user-images.githubusercontent.com/48262842/159129820-9163d393-4cd1-4a54-b537-ac6ca5738944.png)

The math is somewhat ignored. What could it be?

Is it possible to see any logs of retext trying to load the mathjax extension?

Also the chromium web renderer is not working. When I enable it the preview is totally blank. I did a fresh reboot and the problems persist.

**Comment by Oisangui** [comment]
Is it possible to see any logs of retext trying to load the mathjax extension?

**Comment by mitya57** [comment]
Hi! Do you have “Edit → Use WebEngine (Chromium) renderer”? Is it enabled?

If it's not, please try installing [PyQtWebEngine](https://pypi.org/project/PyQtWebEngine/) and then enabling that option.

**Comment by Oisangui** [comment]
@mitya57 I did and when it is enabled the preview is absolutely blank. Trying removing the pip3 package and installing with distro package manager instead...

**Comment by Oisangui** [comment]
Still not working. Same behaviour.

**Comment by mitya57** [comment]
Can you clarify, when you install it with openSUSE package manager, is it absolutely blank, or there is only math missing?
Is the “Use WebEngine (Chromium) renderer” option shown in menu and enabled?

If the preview is blank, can you please launch ReText from terminal and check what is printed there?

**Comment by Oisangui** [comment]
When ```Use WebEngine (Chromium) renderer``` is enabled, the preview is completely blank, not even any text showing, just pure white. When it is disabled, only math is not rendered, but text is.

**Comment by mitya57** [comment]
It's very strange. Can you please make sure that PyQt5 and PyQtWebEngine come from the same source? If one is from package manager and the other one is from PyPI, there may be a conflict.

Also maybe it can't find PyQtWebEngineProcess? Can you try to list installed files of PyQtWebEngine, locate PyQtWebEngineProcess file and export full path to it in `QTWEBENGINEPROCESS_PATH` environment variable?

**Comment by Oisangui** [comment]
Alright uninstalling both from pip3 and... it works! It seems I should only had installed it from the openSUSE package manager from the beginning.  Thanks.

**Comment by callegar** [comment]
Same issue here. If you install retext in a virtual environment via `pip`, it pulls in PyQt5 and its dependencies. If you then use pip to install `PyQtWebEngine` it installs and you find the `Use WebEngine (Chromium) renderer` option to enable in `retext`. However, selecting it the preview is blank with no error given.

Observed on Ubuntu, so it is not OpenSuse specific.

Please reopen.
