### ISSUE TITLE
Format selected text to inline code for AZERTY keyboard

### ISSUE THREAD

**Issue by websealevel** [retext-project/retext#581]
When selecting some text and using back-ticks to format to `inline code` the text is replaced by the back-tick. Whereas this functionality works as expected for link, bold or italic.

- Is this an issue or a feature which is not implemented yet ?
- Is there any way to configure our-self a shortcut to format to inline-code?

Thank you very much for this amazing editor

**Comment by websealevel** [comment]
I use ReText 7.2.1 (utilisant PyMarkups 3.1.1), installed from Debian repo.

But I saw the last version is currently 7.2.3

So i've installed ReText using pip3 to test. Still have the same issue. 

My guess is that I'm using AZERTY Keyboard (french) so in order to do the back-tick I need to press **twice** ALTGR+7, the second input is replacing the selected text. On QUERTY keyboards you juste need to press one key if I checked that correctly. That would explain why any other surrounding options work fine, but not this one.

Yes, to select and press ` is absolutely fine for me : )

**Comment by mitya57** [comment]
> My guess is that I'm using _AZERTY_ Keyboard (french) so in order to do the back-tick I need to press **twice** `ALTGR+7`, the second input is replacing the selected text.

So did you use apply formatting from “Formatting” dropdown, or you selected text and tried to press backtick key?

If the former, then I don't see how keyboard layout would affect this.

The latter is implemented in master branch now. If you could test, that would be nice. You can simply clone the repository and run `./retext.py` from there. Or pass the repository URL to `pip install`.

**Comment by websealevel** [comment]
Using Formatting dropdown it works with no problems, it is when I select and try backtick key.
I ve tried by cloning the repo as you suggested but still not working when selecting then backtick. Still replacing the selected text because I have to press keyboard combination twice to make a backtick

**Comment by mitya57** [comment]
I tried with AZERTY myself, but I get a backtick by pressing <kbd>Alt Gr</kbd>+<kbd>7</kbd> only once. What option do I need to enable to have to press it twice?

**Comment by websealevel** [comment]
Ok thank you for your patience and for your answer. I've tried to change the version of my french keyboard and with the new push on main it's working like a charm ! So happy, will save me a lot of time and efforts : )

**Comment by hydrargyrum** [comment]
When reading the discussion, I'm not sure: the issue is not fixed in 7.2.3 but will be fixed in the next release, is it correct?

**Comment by mitya57** [comment]
Correct, it will be fixed in the next release (8.0).
