### ISSUE TITLE
Opening *.md files with retext.exe not working

### ISSUE THREAD

**Issue by protoporos** [retext-project/retext#582]
Hi, I installed retext on my machine to try it out. It's working like I wished but I can't use retext as the standard program to open markdown files with. It won't open when I want to open a markdown file with retext.exe.

I'm really thankful in advance, if this works on my PC it would be awesome :)

**Comment by mitya57** [comment]
Hi!
Can you try to run `retext.exe /path/to/file.md` in Terminal and see what happens?
If it does not work, can you also try `python.exe -m ReText /path/to/file.md`?

I am using Linux so I am not familiar with the specific of Windows, but these two commands may give a clue what happens.

**Comment by protoporos** [comment]
Thanks pretty much, 
I had retext installed for python 3.8 and 3.9. I don't know why exactly, but the retext.exe script in pyhton38 doesn't work. The error it was throwing pointed towards sip and PyQt5 not working together, because API versions.
Anyway, 3.9 does work fine, just couldn't get md-files open with it. But when looking into it with your tips, I discovered that windows was probably using retext with python 3.8 for opening markdown files. Because I may have selected it at the beginning as standard option for opening md-files. But when using opening with retext.exe in python 3.9 it still didn't work, because Windows may have assumed retext.exe in py 3.9 is the same as retext.exe in 3.8 and proceeded to do failed launches. So had to make retext.exe from the directory Scripts in python39 the standard first and than it worked. :)

I'm really thankful you helped me. This was a dump mistake on my side. But now I can work with retext as I have wished. Thanks!
