### ISSUE TITLE
Flathub

### ISSUE THREAD

**Issue by Mailaender** [retext-project/retext#583]
Hi, I want to notify you about a Flatpak package at https://github.com/flathub/flathub/pull/3085.

**Comment by mitya57** [comment]
Thank you! Your packaging looks good to me.

There was an earlier attempt (flathub/flathub#376) but it was not merged for some reason.

**Comment by Mailaender** [comment]
He made his own repository instead https://github.com/scx/retext-flatpak which seems outdated. I also like the community approach more than being a loner.
