### ISSUE TITLE
ReText toolbar icons get transparent

### ISSUE THREAD

**Issue by aryayounesi** [retext-project/retext#590]
greetings.
I faced a problem with the app which is toolbar icons are **transparent** but when the cruiser is on them keyword appeared, meaning one could know it is *open* , or *new file*, etc. I could not solve it by myself and actually I like the app. it is more than great if there would be a solution. 
OS: **fedora 36**
p.s: I reinstall it once, did not work. two screenshots are attached.

**soloution:** I remove the app and reinstalled it through **pip**; problem solved.
![Screenshot_2022-08-01_17-34-25](https://user-images.githubusercontent.com/107572856/182156253-3a413778-75b4-49cd-b43b-8a3a5bb03e5e.png)
![Screenshot_2022-08-01_17-33-36](https://user-images.githubusercontent.com/107572856/182156271-1dff5f5b-d432-4790-840e-d07337d1d683.png)

**Comment by aryayounesi** [comment]
> Try going to Edit → Preferences → Interface and setting "Icon theme name" to your icon theme (e.g. Adwaita).
> 
> There is automatic detection but it works only if you have [pygobject](https://pygobject.readthedocs.io/en/latest/) installed.

dear @mitya57 
thanks for your quick reply; unfortunately I could not make it right; the package is installed, also I install a handful other packages. no gain. note it may be good that I'm using xfce4. if it's possible for you guide me a little more. I have read the docs, and tried every installed icon theme.

**Comment by mitya57** [comment]
Can you show the contents of your /usr/share/icons?

You can try putting names of directories from there to "Icon theme name" field, clicking "Apply" and seeing what happens.

Also how did you install ReText? From Fedora's repository or with `pip`? What is ReText version?

**Comment by aryayounesi** [comment]
@mitya57 thanks for help. yes sure. here is my icon folder. I tried a few icon themes, actually it was funny. the only icon I can see is *preview* and in fact it changes with changing in the field. screen shots attached.
I installed it from fedora repository; do you suggest to remove and install with pip?
![Screenshot_2022-08-01_23-55-19](https://user-images.githubusercontent.com/107572856/182230659-cb4244e5-3096-4920-8f1b-3980dd48b980.png)
![Screenshot_2022-08-01_23-55-41](https://user-images.githubusercontent.com/107572856/182230670-62cdbf5b-5ee9-4294-bf57-6849e806093e.png)
![Screenshot_2022-08-01_23-57-49](https://user-images.githubusercontent.com/107572856/182230703-3dd43aba-c0cf-468e-8d94-8b48a03f0289.png)
![Screenshot_2022-08-01_23-58-20](https://user-images.githubusercontent.com/107572856/182230724-51493fc2-5301-4826-9b1b-ba35f0388c61.png)
![Screenshot_2022-08-01_23-58-49](https://user-images.githubusercontent.com/107572856/182230726-9e5fdd5c-4c3b-4bee-a5a4-78f0c7488505.png)
