### ISSUE TITLE
Issue displaying checkboxes in html with markdown-checklist extension

### ISSUE THREAD

**Issue by wtbutler** [retext-project/retext#591]
I have installed the markdown-checklist extension pip3, and I have added it to my markdown file. If I check the HTML generated by ReText, it clearly includes checkboxes. I copied and pasted this into its own file and viewed it in my browser and it did include checkboxes.
```markdown
<!-- Required extensions: markdown_checklist.extension -->

# TODO
 - [X] Testing  
 - [ ] This  
```
```html
<!doctype html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="generator" content="ReText 8.0.0">
<title>README</title>
</head>
<body>
<!-- Required extensions: markdown_checklist.extension -->

<h1>TODO</h1>
<ul class="checklist">
<li><input type="checkbox" disabled checked> Testing  </li>
<li><input type="checkbox" disabled> This  </li>
</ul>

</body>
</html>
```
However, the retext preview shows no checkboxes, and when exported to a PDF, the PDF also includes no checkboxes. 
![image](https://user-images.githubusercontent.com/22160103/183263607-318e5f67-04f8-4075-ac0f-4724a139414e.png)

I'm using debian 11 and retext 8.0.0.

Thanks for any help!

**Comment by mitya57** [comment]
Please try enabling the WebEngine renderer from the Edit menu. The default renderer supports only a basic subset of HTML.

**Comment by wtbutler** [comment]
Thanks for the reply! I probably did something wrong, because the option is grayed out. I tried installing chromium and restarting ReText and it's still grayed out.

**Comment by mitya57** [comment]
Then try this:

    sudo apt install python3-pyqt6.qtwebengine libqt6webenginecore6-bin

These packages are recommended by retext.

**Comment by wtbutler** [comment]
Just so I don't bork things, I'm not seeing those packages. I'm seeing pyqt5, but not pyqt6. Is there a significant enough difference that I should figure out how to get to pyqt6?

**Comment by mitya57** [comment]
Sorry, I did not read your post carefully enough and I thought you installed ReText from Debian testing packages.

But you are using Debian 11 which indeed does not have PyQt6.

Then I assume you installed ReText using pip. In that case, you need this:

    pip install PyQt6-WebEngine

Sorry again for confusion.

**Comment by wtbutler** [comment]
All good! Thanks again. That did display checkboxes. There's a separate issue now, but that seems to be with checkbox-extension and nested lists, not ReText, so this seems to be resolved!

**Comment by mitya57** [comment]
Good! Closing then.
