### ISSUE TITLE
Exception during window resize

### ISSUE THREAD

**Issue by wladimir-boyarskiy** [retext-project/retext#595]
Hello, there is exception during retext running at Fedora Linux: https://bugzilla.redhat.com/show_bug.cgi?id=2089762

Could someone please fix it?

**Comment by mitya57** [comment]
It's a duplicate of #573, which was fixed in ReText 7.2.3 (commit 5cedbb05c9c906cd).

Fedora seems to still use 7.2.2. Please ask Fedora maintainers to update to a newer version (the latest one is 8.0.0).
