### ISSUE TITLE
Math missed

### ISSUE THREAD

**Issue by penghao123456** [retext-project/retext#596]
I had used your ReText. I had set the configurations from [the wiki](https://github.com/retext-project/retext/wiki/Math) because I think I habit use `$...$`:
```
mdx_math(enable_dollar_delimiter=1)
```
Just this line. But when I input this:
```
$1+1=2$
```
I want it shows math but it don't shows any things.
Is it a bug? Or I did something wrong? How can I let it shows math?

**Comment by penghao123456** [comment]
P.S. I had installed it using `pip install retext`.

**Comment by penghao123456** [comment]
P.S. I had tried it again using `\(1+1=2\)` and `$$1+1=2$$` but it doesn't shows any things again.
The html code it makes is:
```html
<!doctype html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="generator" content="ReText 7.2.3">
<title>新建文档</title>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "input/AsciiMath", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"],
  TeX: {
    extensions: ["AMSmath.js", "AMSsymbols.js"],
    equationNumbers: {autoNumber: "AMS"}
  }
});
</script>
<script type="text/javascript" src="file:///usr/share/javascript/mathjax/MathJax.js"></script></head>
<body>
<p>
<script type="math/tex">1+1=2</script>
</p>

</body>
</html>
```
(I had using Chinese.)
And the markdown of it is:
```
$1+1=2$
```
And it shows:[![image.png](https://i.postimg.cc/tJ34DZ8q/image.png)](https://postimg.cc/YLS7C9pZ)

**Comment by penghao123456** [comment]
Oh, I finished it!
1. Install the `libjs-mathjax`:
```
sudo apt install libjs-mathjax
```
2. Set the extensions;
3. Set use WebKit.
Finish!

**Comment by mitya57** [comment]
Yeah, you did everything correct!
