### ISSUE TITLE
Cannot load Youtube iframe

### ISSUE THREAD

**Issue by fredele** [retext-project/retext#604]
When navigating on Youtube, you can copy an integration code which resembles to this :

<iframe width="837" height="614" src="https://www.youtube.com/embed/XXXXXXXXX" title="title" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

At the current state, the frame is displayed but not the video.
This behavior is due to the function "acceptNavigationRequest" in the file "webenginepreview.py"

If you add to this function this statement :        

```
if url.scheme() == "https":
            return True
```

the iframe is properly loaded and the video displayed ...

( ...and yes, I know, I should do a proper pull request ...)

**Comment by mitya57** [comment]
Actually, I think we should fix this issue by allowing all requests when `isMainFrame` argument is False.
