### ISSUE TITLE
How can I install Retext 8.0.0 using apt?

### ISSUE THREAD

**Issue by penghao123456** [retext-project/retext#605]
I had using Ubuntu 22.04.1 64bit.
I want upgrade ReText from 7.2.3 to 8.0.0.
But I can't install it using `apt reinstall`.
It can only install 7.2.3.
How can I install ReText 8.0.0 using  `apt reinstall`?

**Comment by mitya57** [comment]
Unfortunately, Ubuntu 22.04 does not have PyQt6 in the repositories, so making a package is complicated.

Can you install the package with `pip`?
- `sudo apt install python3-pip`
- `pip install --upgrade --user ReText`

**Comment by penghao123456** [comment]
Thank you. I had installed ReText 8.0.0 with PyQt6.4.2.
