### ISSUE TITLE
webenginepreview: font size should be in pixels

### ISSUE THREAD

**Issue by char101** [retext-project/retext#609]
Hi,

`setFontSize` in this line uses pixels not points so this line should be

https://github.com/retext-project/retext/blob/961a3922f073407d2cd1f41e2e05360d7868c06c/ReText/webenginepreview.py#L122-L123

```python
settings.setFontSize(QWebEngineSettings.FontSize.DefaultFontSize,
                     int(font.pointSize() * QGuiApplication.primaryScreen().physicalDotsPerInch() / 72))
```

**Comment by mitya57** [comment]
Thank you very much for your report!

I fixed this in a bit different way. Your suggestion makes the font too large on my display, while with `QFontInfo::pixelSize()` the size in QTextEdit and WebEngine previews is the same.
