### ISSUE TITLE
HTML parser doesn't respect list item value attribute

### ISSUE THREAD

**Issue by mxamber** [retext-project/retext#610]
In HTML, `li` list item elements in `ol` ordered lists can use the `value` attribute to skip numbers. Since Markdown has no equivalent, but writing raw HTML into `.md` files is commonly accepted (and supported by ReText), using `<li value=n>` is the only way to achieve numbered list with skipped numbers.

However, although such HTML is exported correctly using the HTML export, it is neither displayed correctly nor exported correctly using the built-in print dialog.

Here is an example code snippet:

```
## My subsection

Here goes the list. It looks like this:

<ol>
  <li>One</li>
  <li>Two</li>
  <li value=5>Five</li>
</ol>
```

The above code should produce a 1-2-5 list, which it does in the HTML export, but does not in the live preview, static preview, or print export.

**Comment by mitya57** [comment]
Thank you for your report.

QTextEdit is not a full-fledged HTML engine, it only supports a subset of HTML which is documented on [this page](https://doc.qt.io/qt-6/richtext-html-subset.html). Unfortunately, `value` attribute of `li` elements is not supported.

I suggest you to use the WebEngine (Chromium) renderer which can be enabled from the Edit menu.
