### ISSUE TITLE
Feature request: rendering <details><summary> blocks

### ISSUE THREAD

**Issue by vi** [retext-project/retext#613]
Github and some other markdown support

<details><summary>foldable sections</summary>, which expand on click</details>.

Retext does not seem to render them properly in preview. There is seems to be no button to insert them easily, at least in ReText 8.0.0.

**Comment by mitya57** [comment]
The default previewer is based on QTextEdit, which supports only a subset of HTML.

If you want to use advanced HTML features, you can use ‘Edit → Use WebEngine (Chromium) renderer’ (first install [PyQt6-WebEngine]). With that renderer, the `details` tag works fine:

![Screenshot](https://user-images.githubusercontent.com/1381584/220274948-93d81723-cc5b-4e6d-be7e-e6e6a16167dd.png)

[PyQt6-WebEngine]: https://pypi.org/project/PyQt6-WebEngine/

**Comment by mitya57** [comment]
As for support in Markdown, there is a third-party extension for this: https://facelessuser.github.io/pymdown-extensions/extensions/details/.

But as it is not part of standard Markdown syntax, there is no button for it.
