### ISSUE TITLE
[feature] Provide an installer for precompiled binaries on Windows.

### ISSUE THREAD

**Issue by hwhsu1231** [retext-project/retext#614]
### Feature Request

Provide an installer for precompiled binaries on Windows.

Maybe it can use [PyInstaller](https://pyinstaller.org/en/stable/) to do so.

One of the possible benefits is being able to installed by [winget-cli](https://github.com/microsoft/winget-cli).

**Comment by Griffon26** [comment]
There was already https://github.com/retext-project/ReTextPortable/ with instructions on how to compile such a package, but I recently updated them for ReText 8.0.1 and just created a release. The installer executable is available as an attachment on the release page: https://github.com/retext-project/ReTextPortable/releases/tag/v8.0.1-31d2ff2.

I hope this satisfies your requirements.
