### ISSUE TITLE
retext does not apply QT style override 

### ISSUE THREAD

**Issue by rohshall** [retext-project/retext#615]
I have environment with:
`QT_STYLE_OVERRIDE=kvantum`

`
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: kvantum-dark, kvantum, Windows, Fusion
Using configuration file: /home/salilw/.config/ReText project/ReText.conf
`

`
$ retext -v
QApplication: invalid style override 'kvantum' passed, ignoring it.
	Available styles: kvantum-dark, kvantum, Windows, Fusion
ReText 8.0.0
`

`
$ uname -a
Linux salil-xps139360 6.2.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 13 Mar 2023 17:02:08 +0000 x86_64 GNU/Linux
`
It's Arch Linux.

**Comment by mitya57** [comment]
I cannot reproduce this. Although, I am using Debian, not Arch Linux. Debian does not have Kvantum packaged for Qt 6, so I complied it myself:

![Screenshot](https://user-images.githubusercontent.com/1381584/226033578-4aa40482-4ac8-4ba3-83bb-d4e8aa8fb845.png)

It looks like Qt fails loading the plugin for some reason. Maybe it needs some shared libraries which are not installed? Can you try checking it with `ldd`? Also, does it work with other Qt 6 applications (e.g. Designer or Assistant)?

**Comment by rohshall** [comment]
Thank you @mitya57 - it's not a bug. I had `qt5ct` installed, not `qt6ct`. After installing `qt6ct`, my style got applied. Thanks a lot, again!
