### ISSUE TITLE
[feature request] Markdown headers in color

### ISSUE THREAD

**Issue by flexid2000** [retext-project/retext#617]
Highlighting markdown headers with color would render text readable more easily, e.g. as some editors like featherpad are doing it. Any chance of coding that to highlighter.py?

**Comment by johanneskropf** [comment]
I second this, it wold be great if this could be exposed as a customizable variable for the color scheme.

**Comment by mitya57** [comment]
This is now implemented in git. You can now use this in the configuration file:
```ini
[ColorScheme]
markdownHeaders=red
```

See [configuration.md](https://github.com/retext-project/retext/blob/master/configuration.md) for details.
