### ISSUE TITLE
[bug] No pdf export if useWebEngine checked

### ISSUE THREAD

**Issue by flexid2000** [retext-project/retext#618]
Distros: Arch Linux, Debian 12
Desktop Environment: LXQt (in Arch with Qt6-plugins)
ReText v. 8.0.0

Actual behavior: When I check `Customize >  Use WebEngine (Chromium)` and then run `Export > PDF` a blank page is produced.

Expected behavior: The program should compile a pdf document even if the option `Use WebEngine` is checked.

Workaround: Set `useWebEngine` to `false`.

**Comment by mitya57** [comment]
For WebEngine PDF export to work, you need to refresh the preview panel first. For example, enable preview mode and disable again if you want.

Can you please check if it works for you?

**Comment by flexid2000** [comment]
Unexplicably, I cannot reproduce the alleged bug any more. It's working now. So let's close the issue.
