### ISSUE TITLE
New paperSize?

### ISSUE THREAD

**Issue by texjunky** [retext-project/retext#619]
I see only A4 and Letter paperSizes. Could you add a Beamer(128 x 96mm) size. This if popular for slides.

**Comment by mitya57** [comment]
Can you please elaborate where you see only two options? Also, what are your versions of ReText and Qt?

For me, there are many options in the page setup dialog. If you need slides with 3:4 ratio, you can try the 4×6 inch option.

![image](https://user-images.githubusercontent.com/1381584/227735753-27387a5f-ca57-42c1-b1dd-a36026a0eb46.png)

**Comment by texjunky** [comment]
Thanks for your response. My version is from the Ubuntu repositories. It is version 7.1.0 and does not have the page layout option. I saw the A4 and Letter options in a conf file somewhere.
I will try installing it from github --- thanks again.

**Comment by mitya57** [comment]
ReText 7.1 had the same dialog.

File → Print (or Print preview) → Properties button.

**Comment by texjunky** [comment]
I have not been clear. My main interest is in the exported pdf file. I would like to control the (I think) media box of the resulting pdf file.

**Comment by mitya57** [comment]
You can export to PDF from the Print dialog too. Just select “Print to File (PDF)” as the printer name. Then if you click “Properties”, you will be able to select paper size, orientation and margins.

**Comment by texjunky** [comment]
Thanks!
