### ISSUE TITLE
License discrepancy?

### ISSUE THREAD

**Issue by mhmdanas** [retext-project/retext#620]
According to the README and from a quick look at the source code's license headers, ReText is under GPLv2 or later. However, LICENSE_GPL contains the text of the GPLv3. Is this a mistake?

**Comment by mitya57** [comment]
Well, GPLv3 is one of possible “GPLv2 or later” variants.

Both GPLv2 and GPLv3 are fine, but when deciding which version to put into a LICENSE file, I put the latest version.

But if there is a valid reason to replace file with GPLv2, I will do it.

**Comment by mhmdanas** [comment]
I don't know if it's incorrect to put GPLv3 in this case, but I can say that it's unusual (I've never seen somebody do this before) and also somewhat confusing.

**Comment by mhmdanas** [comment]
Furthermore, GitHub detects the project's license from its license file, and thus confusingly show ReText's license as "GPL-3.0."
