### ISSUE TITLE
Ctrl+Tab and Ctrl+Shift+Tab for tab switching

### ISSUE THREAD

**Issue by donjan** [retext-project/retext#622]
I know some apps try to heed the HIG, but the [official Qt shortcuts](https://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts) as well as most sane desktop environments (i.e. all except Gnome) use Ctrl+Tab instead of Ctrl+PageDown for tab switching.

Please?

```diff
retext/ReText/window.py
@@ -112,9 +112,9 @@
 		self.actionSaveAs = self.act(self.tr('Save as'), 'document-save-as',
 			self.saveFileAs, shct=QKeySequence.StandardKey.SaveAs)
 		self.actionNextTab = self.act(self.tr('Next tab'), 'go-next',
-			lambda: self.switchTab(1), shct=Qt.Modifier.CTRL | Qt.Key.Key_PageDown)
+			lambda: self.switchTab(1), shct=Qt.Modifier.CTRL | Qt.Key.Key_Tab)
 		self.actionPrevTab = self.act(self.tr('Previous tab'), 'go-previous',
-			lambda: self.switchTab(-1), shct=Qt.Modifier.CTRL | Qt.Key.Key_PageUp)
+			lambda: self.switchTab(-1), shct=Qt.Modifier.CTRL | Qt.Modifier.SHIFT | Qt.Key.Key_Tab)
 		self.actionCloseCurrentTab = self.act(self.tr('Close tab'), 'window-close',
 			lambda: self.closeTab(self.ind), shct=QKeySequence.StandardKey.Close)
 		self.actionPrint = self.act(self.tr('Print'), 'document-print',
```

(or at least make it configurable)

**Comment by mitya57** [comment]
Can you please test if the linked commit works for you?

Either clone the repository with `issue622` branch, or download the [patch](https://github.com/retext-project/retext/commit/85d8ace6ac188b9ea4a632cb0256815fade0ff4c.patch) and apply it manually to your installation.

**Comment by donjan** [comment]
Works perfectly, thanks!
