### ISSUE TITLE
strike-through

### ISSUE THREAD

**Issue by fastrgv** [retext-project/retext#632]
I would like to request adding strike-thru text. Apparently the following should show as text with strikeout font:

~~this is a line of strikeout text~~

Thx,
Rod

**Comment by fastrgv** [comment]
I have since found that html tags work for me (v7.1.0):
<s>this is a line of strikeout text</s>
so I will close this issue.

**Comment by mitya57** [comment]
Yes, out of the box you can use HTML tags. If you want to use tilde syntax, you can try this third-party extension:
https://facelessuser.github.io/pymdown-extensions/extensions/tilde/

See [this wiki page](https://github.com/retext-project/retext/wiki/Markdown-extensions) for details on how to enable extensions. Extension name here would be `pymdownx.tilde`.
