### ISSUE TITLE
Headings navigation

### ISSUE THREAD

**Issue by winterwolf** [retext-project/retext#635]
Navigation by headings in a document does not work (in preview).

```markdown
# Example

## Table of contents

- [test 1](#header-1)
- [test 2](#header-2)

... some text ...

## Header 1

... some text ...

## Header 2

... some text ...
```

Document should scroll to headers when you click test links in example above.

It also would be great to provide popup assist with available headers in document when you type `#` in link, like VSCode does.

**Comment by mitya57** [comment]
To get table of contents, you should use the [`toc` extension][1], not try to do it manually.

Without that extension, headers do not get IDs assigned to them.

See the [wiki][2] for details on how to enable extensions.

[1]: https://python-markdown.github.io/extensions/toc/
[2]: https://github.com/retext-project/retext/wiki/Markdown-extensions
