### ISSUE TITLE
App crashes when clicking the tiny box at the bottom with the cursor line and position.

### ISSUE THREAD

**Issue by parkdweller** [retext-project/retext#637]
So, I was trying to add some text to the bottom of the document I'm editing. To to so, I clicked the end of the last line of text, which was underneath that little box in the lower right corner (the one which tells you which line the cursor is in). And then, crash!

Even with a new, blank document, clicking the cursed box of terror will crash the app. It does so everytime.

I'm using ReText 8.0.0 (using PyMarkups 4.0.0), it's what I got from the Debian repository.

Let me know if I can provide anymore info. And by the way, that tiny box is of no use to me, it would be nice if I could go into settings and hide it.

Thanks for the great work, ReText is very nice!

**Comment by mitya57** [comment]
Fixed, thank you for the report!

I will try to make a new release soon, and upload it to Debian (unstable/testing).

Unfortunately, at the moment there is no way to disable that box completely, however if there are remaining reasons why you would want to do that, I can add a setting for that.

**Comment by parkdweller** [comment]
Hey, that was quick, you're amazing! As to hiding the box, it doesn't do anything useful to me, so I'd like to hide it just to have a cleaner interface. On the other hand, having the box doesn't really bother me that much, so only add  the option to hide it if you really feel like doing extra work for a very insignificant reason :)
Have a great day! 
Diego 

On March 12, 2024 8:35:57 AM GMT-03:00, Dmitry Shachnev ***@***.***> wrote:
>Fixed, thank you for the report!
>
>I will try to make a new release soon, and upload it to Debian (unstable/testing).
>
>Unfortunately, at the moment there is no way to disable that box completely, however if there are remaining reasons why you would want to do that, I can add a setting for that.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/retext-project/retext/issues/637#issuecomment-1991449409
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
