### ISSUE TITLE
[BUG]module markups

### ISSUE THREAD

**Issue by Fr-Dae** [retext-project/retext#641]
**on Lubuntu 24.04**
sources download from github, extract and make executable (chmod -R 775 ./) 
move to folder
and ...
```python
dae@dae-gl753vd:~/Script/retext-8.0.2$ python3 ./retext.py 
Traceback (most recent call last):
  File "/home/dae/Script/retext-8.0.2/./retext.py", line 3, in <module>
    from ReText.__main__ import main
  File "/home/dae/Script/retext-8.0.2/ReText/__init__.py", line 19, in <module>
    import markups
ModuleNotFoundError: No module named 'markups'
```
could you be more specifique on readme for "how to install, how to start" please ?

**Comment by mitya57** [comment]
The recommended way is installing it via your distro's package manager (`sudo apt install retext`) or using pip (`pip install ReText`, for this method you should either use virtualenv or pass `--user --break-system-packages` to pip).

If you chose to clone the repo, you can install the dependencies manually, e.g. using `pip install docutils Markdown Markups Pygments PyQt6`.

By the way, there is no need to mark files executable, you are really executing `python3`.

I will try to update the README a bit later.

**Comment by Fr-Dae** [comment]
work th
