### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by rodajc** [retext-project/retext#642]
I like Retext a lot but it would be even better with a few keyboard shortcuts, e.g. Ctrl Alt PageUp to switch to the next tab to the left like gedit has.

Is it possible to configure keyboard shortcuts and if so, how?

**Comment by mitya57** [comment]
Hi!

The shortcuts are not configurable, unfortunately.

However, I can add <kbd>Ctrl</kbd>+<kbd>PageUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PageDown</kbd> as alternative shortcuts to switch tabs. This is what browsers support (I have just checked both Chromium and Firefox).

This is without <kbd>Alt</kbd> key: on many modern laptops PageUp and PageDown are themselves combinations with <kbd>Fn</kbd>-keys, so my combination becomes a combination of three physical keys, with <kbd>Alt</kbd> it would be four physical keys.

**Comment by mitya57** [comment]
> However, I can add <kbd>Ctrl</kbd>+<kbd>PageUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PageDown</kbd> as alternative shortcuts to switch tabs.

Done, pushed a commit for that to master branch.

**Comment by rodajc** [comment]
Excellent! Thank you.

**Comment by mitya57** [comment]
If you need more shortcuts, I can consider adding them. If no, can we close this issue?

**Comment by rodajc** [comment]
You can close it.
