### ISSUE TITLE
Can't install ReText on Ubuntu 22.04

### ISSUE THREAD

**Issue by JAQuent** [retext-project/retext#645]
I am using Ubuntu 22.04.4 LTS and I am unable to install ReText on my laptop. Please let me know if you need any further information. I am using ReText on my other machines and I'd really love to have it on my laptop as well. 

python3 --version
`Python 3.10.12`

and get the following error:
pip3 --default-timeout=1000 install ReText
```
Defaulting to user installation because normal site-packages is not writeable
Collecting ReText
  Using cached ReText-8.0.2.tar.gz (546 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2_vwr3bj/retext_4f1521b52f21468eafbfc511c8217061/setup.py", line 24, in <module>
          from setuptools.command.build import build
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mitya57** [comment]
Thank you for the bug report!

It looks like in f1482116638b1d9d3e3ce41d602e1ef72f1a39cb, I started using functionality that is only available in setuptools ≥ 62.4.0. But Ubuntu 22.04 has setuptools 59.6.0.

You can try to run this command:

    pip3 install --upgrade setuptools pip packaging

and then try to install ReText again.

Or you can install `ReText==8.0.1`, the previous release which does not have this problem. Or install retext from Ubuntu packages.

I will add the necessary metadata in the next release.
