### ISSUE TITLE
Ability to make new line without slash

### ISSUE THREAD

**Issue by toboil-features** [retext-project/retext#646]
I want it to be as it was did in Obsidian. Currently ReText can't into that.
https://github.com/user-attachments/assets/b8fc5814-bbb9-4be6-99e6-69346250f9d9

**Comment by mitya57** [comment]
ReText follows the Markdown specification by default, which [says][1] that:

> When you _do_ want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

But there is a built-in extension called [nl2br][2] which changes that behavior and converts all new lines to breaks. For example, you can add `<!-- Required extensions: nl2br -->` on top of your file. See the [Markdown extensions][3] wiki page for more ways to enable extensions.

[1]: https://daringfireball.net/projects/markdown/syntax#p
[2]: https://python-markdown.github.io/extensions/nl2br/
[3]: https://github.com/retext-project/retext/wiki/Markdown-extensions

**Comment by toboil-features** [comment]
Thanks, added `nl2br` to `$HOME/.config/markdown-extensions.txt` and now it works as expected.
