### ISSUE TITLE
Syncronized scrolling doesn't work

### ISSUE THREAD

**Issue by toboil-features** [retext-project/retext#647]
Although it was enabled in settings
https://github.com/user-attachments/assets/f6b0fb95-1daf-4099-ac19-5ac2c0fc22f7

**Comment by mitya57** [comment]
Please make sure that you have “Use WebEngine (Chromium) renderer” option selected in Edit menu.

If that option is inactive, to make it available install [PyQt6-WebEngine](https://pypi.org/project/PyQt6-WebEngine/) package from PyPI or [python3-pyqt6.qtwebengine](https://packages.debian.org/sid/python3-pyqt6.qtwebengine) from Debian/Ubuntu packages.

**Comment by toboil-features** [comment]
Installed [python-pyqt6-webengine](https://archlinux.org/packages/extra/x86_64/python-pyqt6-webengine) and now it works fine.
