### ISSUE TITLE
Automatic paste of image files

### ISSUE THREAD

**Issue by toboil-features** [retext-project/retext#649]
I want ReText to paste image files as in `![](file.png)`, because it is convinient.
I want it to support at least .svg .jpeg .jpg .png .gif .webp etc.

https://github.com/user-attachments/assets/ab57ab9b-52b2-4429-a4cd-8afe0282d307

**Comment by mitya57** [comment]
Fixed in master branch, please test if possible.

**Comment by toboil-features** [comment]
Can you make it also for video and audio files too?

**Comment by mitya57** [comment]
There is no specific Markdown syntax for audio and video. Do you want me to use HTML markup for them (`<audio>` and `<video>`)?

**Comment by toboil-features** [comment]
Sory for delay, yes.
