### ISSUE TITLE
ArrowUp and ArrowDown doesn't moves to start and end points of writing respectively

### ISSUE THREAD

**Issue by toboil-features** [retext-project/retext#650]
This mechanism is minor but slightly convinient as in KWrite. I wish to see it in ReText.

For comparison:
|KWrite|ReText|
|---|---|
|https://github.com/user-attachments/assets/e75fa95d-20d4-4a01-95bb-7da2ecc4b32a|https://github.com/user-attachments/assets/d4ff2574-d03d-4c0b-8d2b-84b9127436ec|

**Comment by mitya57** [comment]
Fixed this one too.
