### ISSUE TITLE
Project / Filesystem Plugin

### ISSUE THREAD

**Issue by mitya57** [retext-project/retext#77]
Looks like there is a "gap in the market" for a software that can edit "wiki-like" documents directly from filesystem, without leaving editor for opening the next document. Also with some kind of link support.

Here is what I think ReText can do to fill that gap.
- Define a concept of project or at least a base directory, so that links can be setup as relative to the project home or the base directory.
- A concept of namespaces can be used to enhance the above point, so that it sets standards on how pages are organised on disk; a namespace would equate to a sub-folder within the project.
- A system of attachments, especially for the purpose of attaching and inserting images would make a huge difference. Here we can keep all attachments for a page in a "_attachments" folder (or something of the like).
- Document tree view or to make it simpler, we can use the directory structure in a file-browser. The latter has the added advantage (if done right) to integrate with shell-extensions (on windows, not sure if there is an equivalent on Linux and other desktops) like TortoiseSVN, which makes it easier to interact with source control systems etc. 

I do like web-based wiki software, but I do not like the idea of having the data stored in an entirely different repository, outside the source tree. Above all, the approach mentioned above will make it possible to edit docs offline.

Reported by: codemedic

Original Ticket: [retext/tickets/77](https://sourceforge.net/p/retext/tickets/77)

**Comment by kwill** [comment]
A simple solution might be to:
* define a project root
* list all subfolders in that root
* list all Markdown files in those folders
* display this as a tree in a separate pane

...this would solve the need for a "project" overview without getting into parsing headers within files. I think this was the original suggestion in #47, but that seems to have evolved into a parsing headers within files.

**Comment by BeatLink** [comment]
Are there any updates on this? I'd be really interested in this feature, so much so that this is the only real showstopper for me

**Comment by mitya57** [comment]
Directory tree pane was added in #531 which is included in ReText ≥ 7.2.0, so closing this issue.
